list(APPEND CMAKE_MODULE_PATH
    ${CMAKE_CURRENT_LIST_DIR}/.
    ${CMAKE_CURRENT_LIST_DIR}/../../CMSIS/Include
    ${CMAKE_CURRENT_LIST_DIR}/../../components/lists
    ${CMAKE_CURRENT_LIST_DIR}/../../components/serial_manager
    ${CMAKE_CURRENT_LIST_DIR}/../../components/slcd_engine
    ${CMAKE_CURRENT_LIST_DIR}/../../components/slcd_engine/GDH-1247WP
    ${CMAKE_CURRENT_LIST_DIR}/../../components/uart
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/adc16
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/afe
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/cmp
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/common
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/crc
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/dma
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/dmamux
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/ewm
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/flash
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/gpio
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/i2c
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/irtc
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/llwu
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/lptmr
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/lpuart
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/mmau
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/pdb
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/pit
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/pmc
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/port
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/qtmr_2
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/rcm
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/rnga
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/sim
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/slcd
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/smc
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/spi
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/sysmpu
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/uart
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/vref
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/wdog
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/xbar
    ${CMAKE_CURRENT_LIST_DIR}/../../middleware/mmcau
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/assert
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/debug_console
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/debug_console_lite
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/misc_utilities
    ${CMAKE_CURRENT_LIST_DIR}/drivers
    ${CMAKE_CURRENT_LIST_DIR}/utilities
)


# Copy the cmake components into projects
mcux_include_from_kconfig(driver_llwu)
mcux_include_from_kconfig(CMSIS_Include_dsp)
mcux_include_from_kconfig(driver_i2c)
mcux_include_from_kconfig(driver_port)
mcux_include_from_kconfig(driver_dmamux)
mcux_include_from_kconfig(driver_lptmr)
mcux_include_from_kconfig(driver_gpio)
mcux_include_from_kconfig(component_lists)
mcux_include_from_kconfig(device_system)
mcux_include_from_kconfig(driver_irtc)
mcux_include_from_kconfig(driver_cmp)
mcux_include_from_kconfig(device_startup)
mcux_include_from_kconfig(driver_pdb)
mcux_include_from_kconfig(driver_adc16)
mcux_include_from_kconfig(driver_clock)
mcux_include_from_kconfig(utility_debug_console_lite)
mcux_include_from_kconfig(driver_i2c_dma)
mcux_include_from_kconfig(driver_lpuart_dma)
mcux_include_from_kconfig(driver_ewm)
mcux_include_from_kconfig(driver_lpuart)
mcux_include_from_kconfig(middleware_mmcau_common_files)
mcux_include_from_kconfig(driver_rnga)
mcux_include_from_kconfig(utility_shell)
mcux_include_from_kconfig(utility_notifier)
mcux_include_from_kconfig(driver_wdog)
mcux_include_from_kconfig(CMSIS_Include_core_cm0plus)
mcux_include_from_kconfig(driver_sim)
mcux_include_from_kconfig(driver_vref)
mcux_include_from_kconfig(driver_mmau)
mcux_include_from_kconfig(driver_spi)
mcux_include_from_kconfig(driver_sysmpu)
mcux_include_from_kconfig(driver_flash)
mcux_include_from_kconfig(component_uart_adapter)
mcux_include_from_kconfig(utility_assert)
mcux_include_from_kconfig(middleware_mmcau_cm0p)
mcux_include_from_kconfig(component_serial_manager_MKM35Z7)
mcux_include_from_kconfig(utility_assert_lite_MKM35Z7)
mcux_include_from_kconfig(utility_debug_console)
mcux_include_from_kconfig(device_CMSIS)
mcux_include_from_kconfig(driver_uart)
mcux_include_from_kconfig(driver_qtmr_2)
mcux_include_from_kconfig(component_serial_manager_uart_MKM35Z7)
mcux_include_from_kconfig(utilities_misc_utilities)
mcux_include_from_kconfig(CMSIS_Include_common)
mcux_include_from_kconfig(driver_common)
mcux_include_from_kconfig(driver_uart_dma)
mcux_include_from_kconfig(driver_smc)
mcux_include_from_kconfig(driver_crc)
mcux_include_from_kconfig(driver_spi_dma)
mcux_include_from_kconfig(driver_dma)
mcux_include_from_kconfig(driver_slcd)
mcux_include_from_kconfig(driver_pit)
mcux_include_from_kconfig(driver_afe)
mcux_include_from_kconfig(driver_slcd_gdh_1247wp)
mcux_include_from_kconfig(driver_pmc)
mcux_include_from_kconfig(driver_rcm)
mcux_include_from_kconfig(driver_slcd_engine)
mcux_include_from_kconfig(driver_xbar)
