ISSDK: sensors/fxpq3115_drv.h File Reference
fxpq3115_drv.h File Reference
The fxpq3115_drv.h file describes the fxpq3115 driver interface and structures.
#include <stdint.h>
#include "fxpq3115.h"
#include "sensor_io_i2c.h"
#include "register_io_i2c.h"
Data Structures
struct fxpq3115_i2c_sensorhandle_t
This defines the sensor specific information.
struct fxpq3115_pressuredata_t
This structure defines the fxpq3115 data buffer in Pressure Mode.
struct fxpq3115_altitudedata_t
This structure defines the fxpq3115 data buffer in Altitude Mode.
Macros
#define FXPQ3115_PRESSURE_CONV_FACTOR (64) /* Will give Pascals */
#define FXPQ3115_ALTITUDE_CONV_FACTOR (65536) /* Will give meters above MSL */
#define FXPQ3115_TEMPERATURE_CONV_FACTOR (256) /* Will give °C */
Functions
int32_t FXPQ3115_I2C_Initialize (fxpq3115_i2c_sensorhandle_t *pSensorHandle, ARM_DRIVER_I2C *pBus, uint8_t index, uint16_t sAddress, uint8_t whoAmi)
The interface function to initialize the sensor.
void FXPQ3115_I2C_SetIdleTask (fxpq3115_i2c_sensorhandle_t *pSensorHandle, registeridlefunction_t idleTask, void *userParam)
: The interface function to set the I2C Idle Task.
int32_t FXPQ3115_I2C_Configure (fxpq3115_i2c_sensorhandle_t *pSensorHandle, const registerwritelist_t *pRegWriteList)
The interface function to configure he sensor.
int32_t FXPQ3115_I2C_ReadData (fxpq3115_i2c_sensorhandle_t *pSensorHandle, const registerreadlist_t *pReadList, uint8_t *pBuffer)
The interface function to read the sensor data.
int32_t FXPQ3115_I2C_DeInit (fxpq3115_i2c_sensorhandle_t *pSensorHandle)
The interface function to De Initialize sensor..
Detailed Description
The fxpq3115_drv.h file describes the fxpq3115 driver interface and structures.
Definition in file fxpq3115_drv.h.
Macro Definition Documentation
FXPQ3115_ALTITUDE_CONV_FACTOR
#define FXPQ3115_ALTITUDE_CONV_FACTOR (65536) /* Will give meters above MSL */
Definition at line 29 of file fxpq3115_drv.h.
Referenced by main().
FXPQ3115_PRESSURE_CONV_FACTOR
#define FXPQ3115_PRESSURE_CONV_FACTOR (64) /* Will give Pascals */
Definition at line 28 of file fxpq3115_drv.h.
Referenced by main().
FXPQ3115_TEMPERATURE_CONV_FACTOR
#define FXPQ3115_TEMPERATURE_CONV_FACTOR (256) /* Will give °C */
Definition at line 30 of file fxpq3115_drv.h.
Referenced by main().
Function Documentation
FXPQ3115_I2C_Configure()
int32_t FXPQ3115_I2C_Configure (fxpq3115_i2c_sensorhandle_t * pSensorHandle, const registerwritelist_t * pRegWriteList)
The interface function to configure he sensor.
This function configure the sensor with requested ODR, Range and registers in the regsiter pair array.
Parameters
[in] pSensorHandle handle to the sensor.
[in] pRegWriteList pointer to the register list.
Constraints:
This can be called any number of times only after FXPQ3115_I2C_Initialize(). Application has to ensure that previous instances of these APIs have exited before invocation. No
Returns
FXPQ3115_I2C_Configure() returns the status.
Validate for the correct handle and register write list.
Check whether sensor handle is initialized before applying configuration.
Put the device into standby mode so that configuration can be applied.
Apply the Sensor Configuration based on the Register Write List
Put the device into active mode and ready for reading data.
Definition at line 61 of file fxpq3115_drv.c.
References fxpq3115_i2c_sensorhandle_t::deviceInfo, FXPQ3115_CTRL_REG1, FXPQ3115_CTRL_REG1_SBYB_ACTIVE, FXPQ3115_CTRL_REG1_SBYB_MASK, FXPQ3115_CTRL_REG1_SBYB_STANDBY, int32_t(), fxpq3115_i2c_sensorhandle_t::isInitialized, fxpq3115_i2c_sensorhandle_t::pCommDrv, Register_I2C_Write(), SENSOR_ERROR_INIT, SENSOR_ERROR_INVALID_PARAM, SENSOR_ERROR_NONE, SENSOR_ERROR_WRITE, Sensor_I2C_Write(), fxpq3115_i2c_sensorhandle_t::slaveAddress, and status.
Referenced by main().
FXPQ3115_I2C_DeInit()
int32_t FXPQ3115_I2C_DeInit (fxpq3115_i2c_sensorhandle_t * pSensorHandle)
The interface function to De Initialize sensor..
This function made sensor in a power safe state and de initialize its handle.
Parameters
[in] pSensorHandle handle to the sensor.
Constraints:
This can be called only after FXPQ3115_I2C_Initialize() has been called. Application has to ensure that previous instances of these APIs have exited before invocation. No
Returns
FXPQ3115_I2C_DeInit() returns the status.
Check whether sensor handle is initialized before triggering sensor reset.
Trigger sensor device reset.
De-initialize sensor handle.
Definition at line 135 of file fxpq3115_drv.c.
References fxpq3115_i2c_sensorhandle_t::deviceInfo, FXPQ3115_CTRL_REG1, FXPQ3115_CTRL_REG1_RST_EN, FXPQ3115_CTRL_REG1_RST_MASK, int32_t(), fxpq3115_i2c_sensorhandle_t::isInitialized, fxpq3115_i2c_sensorhandle_t::pCommDrv, Register_I2C_Write(), SENSOR_ERROR_INIT, SENSOR_ERROR_INVALID_PARAM, SENSOR_ERROR_NONE, SENSOR_ERROR_WRITE, fxpq3115_i2c_sensorhandle_t::slaveAddress, and status.
FXPQ3115_I2C_Initialize()
int32_t FXPQ3115_I2C_Initialize (fxpq3115_i2c_sensorhandle_t * pSensorHandle, ARM_DRIVER_I2C * pBus, uint8_t index, uint16_t sAddress, uint8_t whoAmi)
The interface function to initialize the sensor.
This function initialize the sensor and sensor handle.
Parameters
[in] pSensorHandle handle to the sensor.
[in] pBus pointer to the CMSIS API compatible I2C bus object.
[in] index the I2C device number.
[in] sAddress slave address of the device on the bus.
[in] whoami WHO_AM_I value of the device.
Constraints:
This should be the first API to be called. Application has to ensure that previous instances of these APIs have exited before invocation. No
Returns
FXPQ3115_I2C_Initialize() returns the status.
Check the input parameters.
Read and store the device's WHO_AM_I.
Initialize the sensor handle.
Definition at line 22 of file fxpq3115_drv.c.
References fxpq3115_i2c_sensorhandle_t::deviceInfo, registerDeviceInfo_t::deviceInstance, registerDeviceInfo_t::functionParam, FXPQ3115_WHO_AM_I, registerDeviceInfo_t::idleFunction, int32_t(), fxpq3115_i2c_sensorhandle_t::isInitialized, fxpq3115_i2c_sensorhandle_t::pCommDrv, Register_I2C_Read(), SENSOR_ERROR_INIT, SENSOR_ERROR_INVALID_PARAM, SENSOR_ERROR_NONE, fxpq3115_i2c_sensorhandle_t::slaveAddress, and status.
Referenced by main().
FXPQ3115_I2C_ReadData()
int32_t FXPQ3115_I2C_ReadData (fxpq3115_i2c_sensorhandle_t * pSensorHandle, const registerreadlist_t * pReadList, uint8_t * pBuffer)
The interface function to read the sensor data.
This function read the sensor data out from the device and returns raw data in a byte stream.
Parameters
[in] pSensorHandle handle to the sensor.
[in] pReadList pointer to the list of device registers and values to read.
[out] pBuffer buffer which holds raw sensor data.This buffer may be back to back databuffer based command read in the list.
Constraints:
This can be called only after FXPQ3115_I2C_Initialize(). Application has to ensure that previous instances of these APIs have exited before invocation. No
Returns
FXPQ3115_I2C_ReadData() returns the status .
Validate for the correct handle and register read list.
Check whether sensor handle is initialized before reading sensor data.
Parse through the read list and read the data one by one.
Definition at line 106 of file fxpq3115_drv.c.
References fxpq3115_i2c_sensorhandle_t::deviceInfo, int32_t(), fxpq3115_i2c_sensorhandle_t::isInitialized, fxpq3115_i2c_sensorhandle_t::pCommDrv, SENSOR_ERROR_INIT, SENSOR_ERROR_INVALID_PARAM, SENSOR_ERROR_NONE, SENSOR_ERROR_READ, Sensor_I2C_Read(), fxpq3115_i2c_sensorhandle_t::slaveAddress, and status.
Referenced by main().
FXPQ3115_I2C_SetIdleTask()
void FXPQ3115_I2C_SetIdleTask (fxpq3115_i2c_sensorhandle_t * pSensorHandle, registeridlefunction_t idleTask, void * userParam)
: The interface function to set the I2C Idle Task.
Parameters
[in] fxpq3115_i2c_sensorhandle_t *pSensorHandle, handle to the sensor handle.
[in] registeridlefunction_t idleTask, function pointer to the function to execute on I2C Idle Time.
[in] void *userParam, the pointer to the user idle ftask parameters.
Returns
void.
Constraints:
This can be called any number of times only after FXPQ3115_I2C_Initialize(). Application has to ensure that previous instances of these APIs have exited before invocation. No
Definition at line 53 of file fxpq3115_drv.c.
References fxpq3115_i2c_sensorhandle_t::deviceInfo, registerDeviceInfo_t::functionParam, and registerDeviceInfo_t::idleFunction.
Referenced by main().