ISSDK: sensors/mag3110_drv.c File Reference
mag3110_drv.c File Reference
The mag3110_drv.c file implements the MAG3110 sensor driver interfaces.
#include "mag3110_drv.h"
Functions
int32_t MAG3110_I2C_Initialize (mag3110_i2c_sensorhandle_t *pSensorHandle, ARM_DRIVER_I2C *pBus, uint8_t index, uint16_t sAddress, uint8_t whoAmi)
The interface function to initialize the sensor.
void MAG3110_I2C_SetIdleTask (mag3110_i2c_sensorhandle_t *pSensorHandle, registeridlefunction_t idleTask, void *userParam)
: The interface function to set the I2C Idle Task.
int32_t MAG3110_I2C_Configure (mag3110_i2c_sensorhandle_t *pSensorHandle, const registerwritelist_t *pRegWriteList)
The interface function to configure he sensor.
int32_t MAG3110_I2C_ReadData (mag3110_i2c_sensorhandle_t *pSensorHandle, const registerreadlist_t *pReadList, uint8_t *pBuffer)
The interface function to read the sensor data.
int32_t MAG3110_I2C_DeInit (mag3110_i2c_sensorhandle_t *pSensorHandle)
The interface function to De Initialize sensor..
void MAG3110_CalibrateHardIronOffset (int16_t *xValue, int16_t *yValue, int16_t *zValue)
Calibrates the magnetometer reading by determining the current hard iron offset.
Detailed Description
The mag3110_drv.c file implements the MAG3110 sensor driver interfaces.
Definition in file mag3110_drv.c.
Function Documentation
MAG3110_CalibrateHardIronOffset()
void MAG3110_CalibrateHardIronOffset (int16_t * xValue, int16_t * yValue, int16_t * zValue)
Calibrates the magnetometer reading by determining the current hard iron offset.
This function must be periodically called during the program execution to constantly calibrate the magnetometer sensor.
Parameters
[in/out] xValue Magnetometer X-axis reading.
[in/out] yValue Magnetometer Y-Axis reading.
[in/out] zValue Magnetometer Z-Axis reading.
Constraints:
This function should be called after each ODR on acquired data. No
Returns
void
Definition at line 164 of file mag3110_drv.c.
Referenced by main().
MAG3110_I2C_Configure()
int32_t MAG3110_I2C_Configure (mag3110_i2c_sensorhandle_t * pSensorHandle, const registerwritelist_t * pRegWriteList)
The interface function to configure he sensor.
This function configure the sensor with requested ODR, Range and registers in the regsiter pair array.
Parameters
[in] pSensorHandle handle to the sensor.
[in] pRegWriteList pointer to the register list.
Constraints:
This can be called any number of times only after MAG3110_I2C_Initialize(). Application has to ensure that previous instances of these APIs have exited before invocation. No
Returns
MAG3110_I2C_Configure() returns the status.
Validate for the correct handle and register write list.
Check whether sensor handle is initialized before applying configuration.
Put the device into standby mode so that configuration can be applied.
Apply the Sensor Configuration based on the Register Write List
Put the device into active mode and ready for reading data.
Definition at line 61 of file mag3110_drv.c.
References mag3110_i2c_sensorhandle_t::deviceInfo, int32_t(), mag3110_i2c_sensorhandle_t::isInitialized, MAG3110_CTRL_REG1, MAG3110_CTRL_REG1_AC_ACTIVE, MAG3110_CTRL_REG1_AC_MASK, MAG3110_CTRL_REG1_AC_STANDBY, mag3110_i2c_sensorhandle_t::pCommDrv, Register_I2C_Write(), SENSOR_ERROR_INIT, SENSOR_ERROR_INVALID_PARAM, SENSOR_ERROR_NONE, SENSOR_ERROR_WRITE, Sensor_I2C_Write(), mag3110_i2c_sensorhandle_t::slaveAddress, and status.
Referenced by main().
MAG3110_I2C_DeInit()
int32_t MAG3110_I2C_DeInit (mag3110_i2c_sensorhandle_t * pSensorHandle)
The interface function to De Initialize sensor..
This function made sensor in a power safe state and de initialize its handle.
Parameters
[in] pSensorHandle handle to the sensor.
Constraints:
This can be called only after MAG3110_I2C_Initialize() has been called. Application has to ensure that previous instances of these APIs have exited before invocation. No
Returns
MAG3110_I2C_DeInit() returns the status.
Check whether sensor handle is initialized before triggering sensor reset.
Trigger sensor device reset.
De-initialize sensor handle.
Definition at line 133 of file mag3110_drv.c.
References mag3110_i2c_sensorhandle_t::deviceInfo, int32_t(), mag3110_i2c_sensorhandle_t::isInitialized, MAG3110_CTRL_REG2, MAG3110_CTRL_REG2_MAG_RST_EN, MAG3110_CTRL_REG2_MAG_RST_MASK, mag3110_i2c_sensorhandle_t::pCommDrv, Register_I2C_Write(), SENSOR_ERROR_INIT, SENSOR_ERROR_INVALID_PARAM, SENSOR_ERROR_NONE, SENSOR_ERROR_WRITE, mag3110_i2c_sensorhandle_t::slaveAddress, and status.
MAG3110_I2C_Initialize()
int32_t MAG3110_I2C_Initialize (mag3110_i2c_sensorhandle_t * pSensorHandle, ARM_DRIVER_I2C * pBus, uint8_t index, uint16_t sAddress, uint8_t whoAmi)
The interface function to initialize the sensor.
This function initialize the sensor and sensor handle.
Parameters
[in] pSensorHandle handle to the sensor.
[in] pBus pointer to the CMSIS API compatible I2C bus object.
[in] index the I2C device number.
[in] sAddress slave address of the device on the bus.
[in] whoami WHO_AM_I value of the device.
Constraints:
This should be the first API to be called. Application has to ensure that previous instances of these APIs have exited before invocation. No
Returns
MAG3110_I2C_Initialize() returns the status.
Check the input parameters.
Read and store the device's WHO_AM_I.
Initialize the sensor handle.
Definition at line 22 of file mag3110_drv.c.
References mag3110_i2c_sensorhandle_t::deviceInfo, registerDeviceInfo_t::deviceInstance, registerDeviceInfo_t::functionParam, registerDeviceInfo_t::idleFunction, int32_t(), mag3110_i2c_sensorhandle_t::isInitialized, MAG3110_WHO_AM_I, mag3110_i2c_sensorhandle_t::pCommDrv, Register_I2C_Read(), SENSOR_ERROR_INIT, SENSOR_ERROR_INVALID_PARAM, SENSOR_ERROR_NONE, mag3110_i2c_sensorhandle_t::slaveAddress, and status.
Referenced by main().
MAG3110_I2C_ReadData()
int32_t MAG3110_I2C_ReadData (mag3110_i2c_sensorhandle_t * pSensorHandle, const registerreadlist_t * pReadList, uint8_t * pBuffer)
The interface function to read the sensor data.
This function read the sensor data out from the device and returns raw data in a byte stream.
Parameters
[in] pSensorHandle handle to the sensor.
[in] pReadList pointer to the list of device registers and values to read.
[out] pBuffer buffer which holds raw sensor data.This buffer may be back to back databuffer based command read in the list.
Constraints:
This can be called any number of times only after MAG3110_I2C_Initialize(). Application has to ensure that previous instances of these APIs have exited before invocation. No
Returns
MAG3110_I2C_ReadData() returns the status .
Validate for the correct handle and register read list.
Check whether sensor handle is initialized before reading sensor data.
Parse through the read list and read the data one by one.
Definition at line 104 of file mag3110_drv.c.
References mag3110_i2c_sensorhandle_t::deviceInfo, int32_t(), mag3110_i2c_sensorhandle_t::isInitialized, mag3110_i2c_sensorhandle_t::pCommDrv, SENSOR_ERROR_INIT, SENSOR_ERROR_INVALID_PARAM, SENSOR_ERROR_NONE, SENSOR_ERROR_READ, Sensor_I2C_Read(), mag3110_i2c_sensorhandle_t::slaveAddress, and status.
Referenced by main().
MAG3110_I2C_SetIdleTask()
void MAG3110_I2C_SetIdleTask (mag3110_i2c_sensorhandle_t * pSensorHandle, registeridlefunction_t idleTask, void * userParam)
: The interface function to set the I2C Idle Task.
Parameters
[in] mag3110_i2c_sensorhandle_t *pSensorHandle, handle to the sensor handle.
[in] registeridlefunction_t idleTask, function pointer to the function to execute on I2C Idle Time.
[in] void *userParam, the pointer to the user idle ftask parameters.
Returns
void.
Constraints:
This can be called any number of times only after MAG3110_I2C_Initialize(). Application has to ensure that previous instances of these APIs have exited before invocation. No
Definition at line 53 of file mag3110_drv.c.
References mag3110_i2c_sensorhandle_t::deviceInfo, registerDeviceInfo_t::functionParam, and registerDeviceInfo_t::idleFunction.
Referenced by main().