ISSDK: driverexamples/mma845x/mma845x_fifo.c File Reference
mma845x_fifo.c File Reference
The mma845x_fifo.c file implements the ISSDK MMA845x sensor driver example demonstration with FIFO mode.
#include "pin_mux.h"
#include "clock_config.h"
#include "board.h"
#include "fsl_debug_console.h"
#include "Driver_I2C.h"
#include "issdk_hal.h"
#include "mma845x_drv.h"
Macros
#define FIFO_SIZE 4
The watermark value configured for MMA845x FIFO Buffer.
Functions
int main (void)
Main function.
Variables
const registerwritelist_t mma845x_Config_Fifo []
const registerreadlist_t mma845x_Fifo_Status [] = {{.readFrom = MMA845x_F_STATUS, .numBytes = 1}, __END_READ_DATA__}
const registerreadlist_t mma845x_Output_Values []
Detailed Description
The mma845x_fifo.c file implements the ISSDK MMA845x sensor driver example demonstration with FIFO mode.
Definition in file mma845x_fifo.c.
Macro Definition Documentation
FIFO_SIZE
#define FIFO_SIZE 4
The watermark value configured for MMA845x FIFO Buffer.
Definition at line 38 of file mma845x_fifo.c.
Referenced by main().
Function Documentation
main()
int main (void)
Main function.
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize the MMA845x sensor driver.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the MMA845x sensor driver with FIFO mode.
Wait for data ready from the MMA845x.
Read the raw sensor data from the MMA845x.
Convert the raw sensor data to signed 16-bit container for display to the debug port.
Definition at line 66 of file mma845x_fifo.c.
References mma845x_acceldata_t::accel, ASK_USER_TO_RESUME, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), data, FIFO_SIZE, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, I2Cdrv, int32_t(), MMA8451_WHO_AM_I_WHOAMI_VALUE, MMA845x_ACCEL_DATA_SIZE, MMA845x_F_STATUS_F_WMRK_FLAG_MASK, MMA845x_I2C_ADDR, MMA845x_I2C_Configure(), MMA845x_I2C_Initialize(), MMA845x_I2C_ReadData(), MMA845x_I2C_SetIdleTask(), rawData, SENSOR_ERROR_NONE, SMC, SMC_SetPowerModeVlpr(), and status.
Variable Documentation
mma845x_Config_Fifo
const registerwritelist_t mma845x_Config_Fifo[]
Initial value:
= {
    {MMA845x_CTRL_REG1, MMA845x_CTRL_REG1_MODE_STANDBY | MMA845x_CTRL_REG1_DR_12DOT5HZ, 0},
    {MMA845x_F_SETUP, MMA845x_F_SETUP_F_MODE_FIFOSTOP | FIFO_SIZE, 0},
    {MMA845x_CTRL_REG2, MMA845x_CTRL_REG2_MODS_HIGHRES, 0},
    __END_WRITE_DATA__}
Prepare the register write list to configure MMA845x in FIFO mode.
Definition at line 44 of file mma845x_fifo.c.
mma845x_Fifo_Status
const registerreadlist_t mma845x_Fifo_Status[] = {{.readFrom = MMA845x_F_STATUS, .numBytes = 1}, __END_READ_DATA__}
Prepare the register read list to read the FIFO event from MMA845x.
Definition at line 54 of file mma845x_fifo.c.
mma845x_Output_Values
const registerreadlist_t mma845x_Output_Values[]
Initial value:
= {
    {.readFrom = MMA845x_OUT_X_MSB, .numBytes = MMA845x_ACCEL_DATA_SIZE * FIFO_SIZE}, __END_READ_DATA__}
Prepare the register read list to read the raw Accel data from MMA845x.
Definition at line 57 of file mma845x_fifo.c.