ISSDK: driverexamples/fxps7250a4/fxps7250a4_interrupt.c File Reference
fxps7250a4_interrupt.c File Reference
The fxps7250a4_interrupt.c file implements the ISSDK FXPS7250A4 analog sensor driver example demonstration with interrupt mode.
#include "pin_mux.h"
#include "clock_config.h"
#include "board.h"
#include "fsl_lptmr.h"
#include "fsl_adc12.h"
#include "fsl_debug_console.h"
#include "issdk_hal.h"
#include "gpio_driver.h"
Macros
#define pa7250_odr_callback PWT_LPTMR0_IRQHandler
#define adc12_irq_callback ADC0_IRQHandler
#define FXPS7250A4_ODR_ms 1000U
Functions
void KE15Z_LPTMR0_ADC0_Initialize (void)
float analog_output_transfer_fn (float volt)
void pa7250_odr_callback (void)
void adc12_irq_callback (void)
int main (void)
Main function.
Variables
volatile uint32_t gAdcConversionValue
volatile bool bAdcCompletedFlag = false
adc12_channel_config_t gAdcChannelConfigStruct
Detailed Description
The fxps7250a4_interrupt.c file implements the ISSDK FXPS7250A4 analog sensor driver example demonstration with interrupt mode.
Definition in file fxps7250a4_interrupt.c.
Macro Definition Documentation
adc12_irq_callback
#define adc12_irq_callback ADC0_IRQHandler
Definition at line 36 of file fxps7250a4_interrupt.c.
FXPS7250A4_ODR_ms
#define FXPS7250A4_ODR_ms 1000U
Definition at line 39 of file fxps7250a4_interrupt.c.
Referenced by KE15Z_LPTMR0_ADC0_Initialize().
pa7250_odr_callback
#define pa7250_odr_callback PWT_LPTMR0_IRQHandler
Definition at line 34 of file fxps7250a4_interrupt.c.
Function Documentation
adc12_irq_callback()
void adc12_irq_callback (void)
Definition at line 67 of file fxps7250a4_interrupt.c.
References bAdcCompletedFlag, FXPS7250A4_ADC12_CHANNEL_GROUP, and gAdcConversionValue.
analog_output_transfer_fn()
float analog_output_transfer_fn (float volt)
Definition at line 107 of file fxps7250a4_interrupt.c.
References FXPS7250A4_OFFSET.
Referenced by main().
KE15Z_LPTMR0_ADC0_Initialize()
void KE15Z_LPTMR0_ADC0_Initialize (void)
Definition at line 74 of file fxps7250a4_interrupt.c.
References FXPS7250A4_ADC12_CHANNEL, FXPS7250A4_ODR_ms, and gAdcChannelConfigStruct.
Referenced by main().
main()
int main (void)
Main function.
Initialize GREEN LED pin used by FRDM board
Definition at line 118 of file fxps7250a4_interrupt.c.
References analog_output_transfer_fn(), ASK_USER_TO_RESUME, bAdcCompletedFlag, BIT12RES, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), Driver_GPIO_KSDK, gAdcConversionValue, GPIO_DIRECTION_OUT, GREEN_LED, KE15Z_LPTMR0_ADC0_Initialize(), GENERIC_DRIVER_GPIO::pin_init, SMC, SMC_SetPowerModeWait(), GENERIC_DRIVER_GPIO::toggle_pin, and VCC.
pa7250_odr_callback()
void pa7250_odr_callback (void)
Definition at line 59 of file fxps7250a4_interrupt.c.
References FXPS7250A4_ADC12_CHANNEL_GROUP, and gAdcChannelConfigStruct.
Variable Documentation
bAdcCompletedFlag
volatile bool bAdcCompletedFlag = false
Definition at line 45 of file fxps7250a4_interrupt.c.
Referenced by adc12_irq_callback(), and main().
gAdcChannelConfigStruct
adc12_channel_config_t gAdcChannelConfigStruct
Definition at line 46 of file fxps7250a4_interrupt.c.
Referenced by KE15Z_LPTMR0_ADC0_Initialize(), and pa7250_odr_callback().
gAdcConversionValue
volatile uint32_t gAdcConversionValue
Definition at line 44 of file fxps7250a4_interrupt.c.
Referenced by adc12_irq_callback(), and main().