ISSDK: driverexamples/fxps7250d4/dbap_app.c File Reference
dbap_app.c File Reference
The dbap_app.c file implements the DBAP sensor driver example.
#include "pin_mux.h"
#include "clock_config.h"
#include "board.h"
#include "fsl_debug_console.h"
#include "systick_utils.h"
#include "issdk_hal.h"
#include "Driver_I2C.h"
#include "dbap_drv.h"
Macros
#define FXPS7250D4 1
#define DBAP_I2C_ADDR 0x60
#define DBAP_DATA_SIZE 0x3
#define TO_LSB 68
#define TO_SEN 1
#define PABSOffLSB 28661.6
#define PABSSENS 30.42
Functions
int main (void)
Main function.
Variables
const registerwritelist_t cDBAPConfig []
Register settings for confirmation.
const registerreadlist_t cDBAPPartNumber []
Address of Part Number.
const registerreadlist_t cDBAPPTData []
Address and size of Raw Pressure data and TemperatureData.
const registerreadlist_t cDBAPDeviceStatus []
Address of Device Status.
Detailed Description
The dbap_app.c file implements the DBAP sensor driver example.
Definition in file dbap_app.c.
Macro Definition Documentation
DBAP_DATA_SIZE
#define DBAP_DATA_SIZE 0x3
Definition at line 33 of file dbap_app.c.
Referenced by main().
DBAP_I2C_ADDR
#define DBAP_I2C_ADDR 0x60
Definition at line 32 of file dbap_app.c.
Referenced by main().
FXPS7250D4
#define FXPS7250D4 1
Definition at line 31 of file dbap_app.c.
PABSOffLSB
#define PABSOffLSB 28661.6
Definition at line 37 of file dbap_app.c.
Referenced by main().
PABSSENS
#define PABSSENS 30.42
Definition at line 38 of file dbap_app.c.
Referenced by main().
TO_LSB
#define TO_LSB 68
Definition at line 34 of file dbap_app.c.
Referenced by main().
TO_SEN
#define TO_SEN 1
Definition at line 35 of file dbap_app.c.
Referenced by main().
Function Documentation
main()
int main (void)
Main function.
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the DBAP sensor.
Read new raw sensor data from the DBAP.
Process the sample and convert the raw sensor data.
Definition at line 81 of file dbap_app.c.
References ASK_USER_TO_RESUME, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), BOARD_SystickEnable(), data, DBAP_DATA_SIZE, DBAP_I2C_ADDR, DBAP_I2C_Configure(), DBAP_I2C_Initialize(), DBAP_I2C_ReadData(), DBAP_I2C_SetIdleTask(), FXPS7250D4_WHOAMI_VALUE, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, I2Cdrv, int32_t(), PABSOffLSB, PABSSENS, dbap_pressuredata_t::pressure, rawData, SENSOR_ERROR_NONE, SMC, SMC_SetPowerModeVlpr(), status, dbap_pressuredata_t::temperature, TO_LSB, and TO_SEN.
Variable Documentation
cDBAPConfig
const registerwritelist_t cDBAPConfig[]
Initial value:
= {
    {FXPS7250_DSP_CFG_U1, FXPS7250_DSP_CFG_U1_LPF_370HZ_2POLE, FXPS7250_DSP_CFG_U1_LPF_MASK},
    __END_WRITE_DATA__}
Register settings for confirmation.
Definition at line 54 of file dbap_app.c.
cDBAPDeviceStatus
const registerreadlist_t cDBAPDeviceStatus[]
Initial value:
= {
    {.readFrom = FXPS7250_DEVSTAT_COPY, .numBytes = 1},
    __END_READ_DATA__}
Address of Device Status.
Definition at line 72 of file dbap_app.c.
cDBAPPartNumber
const registerreadlist_t cDBAPPartNumber[]
Initial value:
= {
    {.readFrom = FXPS7250_PN0, .numBytes = 2},
    __END_READ_DATA__}
Address of Part Number.
Definition at line 59 of file dbap_app.c.
cDBAPPTData
const registerreadlist_t cDBAPPTData[]
Initial value:
= {
    {.readFrom = FXPS7250_SNSDATA0_L, .numBytes = 2},
                {.readFrom = FXPS7250_TEMPERATURE, .numBytes = 1},
     __END_READ_DATA__}
Address and size of Raw Pressure data and TemperatureData.
Definition at line 65 of file dbap_app.c.