ISSDK: driverexamples/dp5004/dp5004_interrupt.c File Reference
dp5004_interrupt.c File Reference
The dp5004_interrupt.c file implements the ISSDK MPXVDP5004 analog sensor driver example demonstration with interrupt mode.
#include "pin_mux.h"
#include "clock_config.h"
#include "board.h"
#include "fsl_lptmr.h"
#include "fsl_adc12.h"
#include "fsl_debug_console.h"
#include "issdk_hal.h"
#include "gpio_driver.h"
Macros
#define dp5004_odr_callback PWT_LPTMR0_IRQHandler
#define adc12_irq_callback ADC0_IRQHandler
#define MPXV5004DR_ODR_ms 1000U
Functions
void dp5004_odr_callback (void)
void adc12_irq_callback (void)
void KE15Z_LPTMR0_ADC0_Initialize (void)
int main (void)
Main function.
Variables
volatile uint32_t gAdcConversionValue
volatile bool bAdcCompletedFlag = false
adc12_channel_config_t gAdcChannelConfigStruct
Detailed Description
The dp5004_interrupt.c file implements the ISSDK MPXVDP5004 analog sensor driver example demonstration with interrupt mode.
Definition in file dp5004_interrupt.c.
Macro Definition Documentation
adc12_irq_callback
#define adc12_irq_callback ADC0_IRQHandler
Definition at line 37 of file dp5004_interrupt.c.
dp5004_odr_callback
#define dp5004_odr_callback PWT_LPTMR0_IRQHandler
Definition at line 35 of file dp5004_interrupt.c.
MPXV5004DR_ODR_ms
#define MPXV5004DR_ODR_ms 1000U
Definition at line 40 of file dp5004_interrupt.c.
Referenced by KE15Z_LPTMR0_ADC0_Initialize().
Function Documentation
adc12_irq_callback()
void adc12_irq_callback (void)
Definition at line 61 of file dp5004_interrupt.c.
References bAdcCompletedFlag, gAdcConversionValue, and MPXVDP5004_ADC12_CHANNEL_GROUP.
dp5004_odr_callback()
void dp5004_odr_callback (void)
Definition at line 53 of file dp5004_interrupt.c.
References gAdcChannelConfigStruct, and MPXVDP5004_ADC12_CHANNEL_GROUP.
KE15Z_LPTMR0_ADC0_Initialize()
void KE15Z_LPTMR0_ADC0_Initialize (void)
Definition at line 68 of file dp5004_interrupt.c.
References gAdcChannelConfigStruct, MPXV5004DR_ODR_ms, and MPXVDP5004_ADC12_CHANNEL.
Referenced by main().
main()
int main (void)
Main function.
Initialize GREEN LED pin used by FRDM board
Definition at line 104 of file dp5004_interrupt.c.
References ASK_USER_TO_RESUME, bAdcCompletedFlag, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), Driver_GPIO_KSDK, gAdcConversionValue, GPIO_DIRECTION_OUT, GREEN_LED, KE15Z_LPTMR0_ADC0_Initialize(), MPXV5004DP_PRESSURE_FROM_ADC_VALUE, GENERIC_DRIVER_GPIO::pin_init, SMC, SMC_SetPowerModeWait(), and GENERIC_DRIVER_GPIO::toggle_pin.
Variable Documentation
bAdcCompletedFlag
volatile bool bAdcCompletedFlag = false
Definition at line 46 of file dp5004_interrupt.c.
Referenced by adc12_irq_callback(), and main().
gAdcChannelConfigStruct
adc12_channel_config_t gAdcChannelConfigStruct
Definition at line 47 of file dp5004_interrupt.c.
Referenced by dp5004_odr_callback(), and KE15Z_LPTMR0_ADC0_Initialize().
gAdcConversionValue
volatile uint32_t gAdcConversionValue
Definition at line 45 of file dp5004_interrupt.c.
Referenced by adc12_irq_callback(), and main().