ISSDK: driverexamples/fxpq3115/fxpq3115_fifo.c File Reference
fxpq3115_fifo.c File Reference
The fxpq3115_fifo.c file implements the ISSDK FXPQ3115BV sensor driver example demonstration with fifo mode.
#include "pin_mux.h"
#include "clock_config.h"
#include "board.h"
#include "fsl_debug_console.h"
#include "Driver_I2C.h"
#include "issdk_hal.h"
#include "fxpq3115_drv.h"
Macros
#define FIFO_WMRK_SIZE (8) /* Buffer 8 Samples. */
#define FXPQ3115_DATA_SIZE (5) /* 3 byte Pressure/Altitude and 2 byte Temperature. */
#define FXPQ3115_SAMPLING_EXPONENT (0) /* 1 second. */
Functions
int main (void)
Main function.
Variables
const registerwritelist_t B3115ConfigFIFO []
Register settings for FIFO (buffered) mode @ default 1 sample per second.
const registerreadlist_t B3115Status [] = {{.readFrom = FXPQ3115_STATUS, .numBytes = 1}, __END_READ_DATA__}
Address of Status Register.
const registerreadlist_t B3115OutputFIFO []
Address and size of Pressure+Temperature Data in FIFO Mode.
Detailed Description
The fxpq3115_fifo.c file implements the ISSDK FXPQ3115BV sensor driver example demonstration with fifo mode.
Definition in file fxpq3115_fifo.c.
Macro Definition Documentation
FIFO_WMRK_SIZE
#define FIFO_WMRK_SIZE (8) /* Buffer 8 Samples. */
Definition at line 35 of file fxpq3115_fifo.c.
Referenced by main().
FXPQ3115_DATA_SIZE
#define FXPQ3115_DATA_SIZE (5) /* 3 byte Pressure/Altitude and 2 byte Temperature. */
Definition at line 36 of file fxpq3115_fifo.c.
Referenced by main().
FXPQ3115_SAMPLING_EXPONENT
#define FXPQ3115_SAMPLING_EXPONENT (0) /* 1 second. */
In FXPQ3115 the Auto Acquisition Time Step (ODR) can be set only in powers of 2 (i.e. 2^x, where x is the SAMPLING_EXPONENT). This gives a range of 1 second to 2^15 seconds (9 hours).
Definition at line 40 of file fxpq3115_fifo.c.
Function Documentation
main()
int main (void)
Main function.
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize FXPQ3115 sensor driver.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the FXPQ3115 sensor.
Wait for data ready from the FXPQ3115.
Read new raw sensor data from the FXPQ3115.
Process all samples and convert the raw sensor data.
Definition at line 72 of file fxpq3115_fifo.c.
References ASK_USER_TO_RESUME, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), data, FIFO_WMRK_SIZE, FXPQ3115_DATA_SIZE, FXPQ3115_F_STATUS_F_WMKF_FLAG_MASK, FXPQ3115_I2C_ADDR, FXPQ3115_I2C_Configure(), FXPQ3115_I2C_Initialize(), FXPQ3115_I2C_ReadData(), FXPQ3115_I2C_SetIdleTask(), FXPQ3115_PRESSURE_CONV_FACTOR, FXPQ3115_TEMPERATURE_CONV_FACTOR, FXPQ3115_WHOAMI_VALUE, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, I2Cdrv, int32_t(), fxpq3115_pressuredata_t::pressure, rawData, SENSOR_ERROR_NONE, SMC, SMC_SetPowerModeVlpr(), status, and fxpq3115_pressuredata_t::temperature.
Variable Documentation
B3115ConfigFIFO
const registerwritelist_t B3115ConfigFIFO[]
Initial value:
= {
    {FXPQ3115_F_SETUP, FXPQ3115_F_SETUP_F_MODE_STOP_MODE | FIFO_WMRK_SIZE,
     FXPQ3115_F_SETUP_F_MODE_MASK | FXPQ3115_F_SETUP_F_WMRK_MASK},
    {FXPQ3115_PT_DATA_CFG,
     FXPQ3115_PT_DATA_CFG_TDEFE_ENABLED | FXPQ3115_PT_DATA_CFG_PDEFE_ENABLED | FXPQ3115_PT_DATA_CFG_DREM_ENABLED,
     FXPQ3115_PT_DATA_CFG_TDEFE_MASK | FXPQ3115_PT_DATA_CFG_PDEFE_MASK | FXPQ3115_PT_DATA_CFG_DREM_MASK},
    {FXPQ3115_CTRL_REG1, FXPQ3115_CTRL_REG1_OS_OSR_128, FXPQ3115_CTRL_REG1_OS_MASK},
    {FXPQ3115_CTRL_REG2, FXPQ3115_SAMPLING_EXPONENT, FXPQ3115_CTRL_REG2_ST_MASK},
    __END_WRITE_DATA__}
Register settings for FIFO (buffered) mode @ default 1 sample per second.
Definition at line 46 of file fxpq3115_fifo.c.
B3115OutputFIFO
const registerreadlist_t B3115OutputFIFO[]
Initial value:
= {
    {.readFrom = FXPQ3115_OUT_P_MSB, .numBytes = FXPQ3115_DATA_SIZE * FIFO_WMRK_SIZE}, __END_READ_DATA__}
Address and size of Pressure+Temperature Data in FIFO Mode.
Definition at line 63 of file fxpq3115_fifo.c.
B3115Status
const registerreadlist_t B3115Status[] = {{.readFrom = FXPQ3115_STATUS, .numBytes = 1}, __END_READ_DATA__}
Address of Status Register.
Definition at line 60 of file fxpq3115_fifo.c.