ISSDK: drivers/gpio/kinetis/gpio_driver_irq_kl27z.c File Reference
gpio_driver_irq_kl27z.c File Reference
The gpio_driver_irq_kl27z.c file containes the Generic IRQ implmentation for the FRDM-KL27Z GPIO.
#include "fsl_gpio.h"
#include "frdm_kl27z.h"
Functions
void ksdk_gpio_handle_interrupt (GPIO_Type *base, port_number_t portNumber)
void PORTA_IRQHandler (void)
void PORTB_PORTC_PORTD_PORTE_IRQHandler (void)
Detailed Description
The gpio_driver_irq_kl27z.c file containes the Generic IRQ implmentation for the FRDM-KL27Z GPIO.
The gpio_driver_irq_kL27z.c file containes the Generic IRQ implmentation for the FRDM-KL27Z GPIO.
Definition in file gpio_driver_irq_kl27z.c.
Function Documentation
ksdk_gpio_handle_interrupt()
void ksdk_gpio_handle_interrupt (GPIO_Type * base, port_number_t portNumber)
Definition at line 153 of file gpio_driver.c.
Referenced by PORTA_IRQHandler(), and PORTB_PORTC_PORTD_PORTE_IRQHandler().
PORTA_IRQHandler()
void PORTA_IRQHandler (void)
Definition at line 22 of file gpio_driver_irq_kl27z.c.
References ksdk_gpio_handle_interrupt(), and PORTA_NUM.
PORTB_PORTC_PORTD_PORTE_IRQHandler()
void PORTB_PORTC_PORTD_PORTE_IRQHandler (void)
Definition at line 26 of file gpio_driver_irq_kl27z.c.
References GPIO_PORT_NUM, GPIO_TYPE, and ksdk_gpio_handle_interrupt().