ISSDK: driverexamples/imx/mekmimx8qm/isl29023/isl29023_poll.c File Reference
isl29023_poll.c File Reference
The isl29023_poll.c file implements the ISSDK ISL29023 sensor driver example demonstration in poll mode.
#include "pin_mux.h"
#include "clock_config.h"
#include "board.h"
#include "fsl_debug_console.h"
#include "fsl_irqsteer.h"
#include "Driver_I2C.h"
#include "issdk_hal.h"
#include "isl29023_drv.h"
Macros
#define ISL29023_DATA_SIZE (2) /* 2 bytes of information */
The size of the ISL29023 sensor data.
#define ISL29023_INT_HT_DATA (11000) /* HI-IRQ treshold value (relative to 16-bit res.)*/
#define ISL29023_INT_LT_DATA (5000) /* LO-IRQ treshold value (relative to 16-bit res.)*/
Functions
int main (void)
Main function.
Variables
const registerwritelist_t ISL29023_Config_Poll []
const registerreadlist_t ISL29023_Status [] = {{.readFrom = ISL29023_CMD_I, .numBytes = 1}, __END_READ_DATA__}
const registerreadlist_t ISL29023_Output_Values []
Detailed Description
The isl29023_poll.c file implements the ISSDK ISL29023 sensor driver example demonstration in poll mode.
Definition in file isl29023_poll.c.
Macro Definition Documentation
ISL29023_DATA_SIZE
#define ISL29023_DATA_SIZE (2) /* 2 bytes of information */
The size of the ISL29023 sensor data.
Definition at line 34 of file isl29023_poll.c.
Referenced by main().
ISL29023_INT_HT_DATA
#define ISL29023_INT_HT_DATA (11000) /* HI-IRQ treshold value (relative to 16-bit res.)*/
Definition at line 43 of file isl29023_poll.c.
ISL29023_INT_LT_DATA
#define ISL29023_INT_LT_DATA (5000) /* LO-IRQ treshold value (relative to 16-bit res.)*/
Definition at line 44 of file isl29023_poll.c.
Function Documentation
main()
int main (void)
Main function.
Initialize the MCU hardware.
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize the ISL29023 sensor driver.
Configure the ISL29023 sensor driver.
Wait for clear IRQ flag bit.
Read the raw sensor data from the ISL29023.
Convert the raw sensor data to signed 16-bit container for display to the debug port.
Definition at line 78 of file isl29023_poll.c.
References ASK_USER_TO_RESUME, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), data, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, I2Cdrv, int32_t(), ISL29023_CMD_I_FLAG_MASK, ISL29023_DATA_SIZE, ISL29023_I2C_ADDRESS, ISL29023_I2C_Configure(), ISL29023_I2C_Initialize(), ISL29023_I2C_ReadData(), ISL29023_I2C_TEST_VALUE, isl29023_lightdata_t::light, rawData, SENSOR_ERROR_NONE, and status.
Variable Documentation
ISL29023_Config_Poll
const registerwritelist_t ISL29023_Config_Poll[]
Initial value:
= {
    {ISL29023_CMD_I, ISL29023_CMD_I_PRST_1 | ISL29023_CMD_I_OP_ALS_CONT,
                     ISL29023_CMD_I_PRST_MASK | ISL29023_CMD_I_OP_MASK},
    {ISL29023_CMD_II, ISL29023_CMD_II_RANGE_1 | ISL29023_CMD_II_RES_16,
                      ISL29023_CMD_II_RANGE_MASK | ISL29023_CMD_II_RES_MASK},
    {ISL29023_INT_LT_LSB, (ISL29023_INT_LT_DATA & 0x00FF), 0xFF},
    {ISL29023_INT_LT_MSB, ((ISL29023_INT_LT_DATA & 0xFF00)>>8), 0xFF},
    {ISL29023_INT_HT_LSB, (ISL29023_INT_HT_DATA & 0x00FF), 0xFF},
    {ISL29023_INT_HT_MSB, ((ISL29023_INT_HT_DATA & 0xFF00)>>8), 0xFF},
    __END_WRITE_DATA__}
Prepare the register write list to configure ISL29023 in 16-bits ALS continuous mode.
Definition at line 50 of file isl29023_poll.c.
ISL29023_Output_Values
const registerreadlist_t ISL29023_Output_Values[]
Initial value:
= {
    {.readFrom = ISL29023_DATA_LSB, .numBytes = ISL29023_DATA_SIZE}, __END_READ_DATA__}
Prepare the register read list to read the raw ADC data from the ISL29023.
Definition at line 69 of file isl29023_poll.c.
ISL29023_Status
const registerreadlist_t ISL29023_Status[] = {{.readFrom = ISL29023_CMD_I, .numBytes = 1}, __END_READ_DATA__}
Prepare the register read list to read ISL29023 IRQ flag bit.
Definition at line 66 of file isl29023_poll.c.