ISSDK: drivers/gpio/kinetis/gpio_driver_irq_ke15z.c File Reference
gpio_driver_irq_ke15z.c File Reference
The gpio_driver_irq_ke15z.c file containes the Generic IRQ implmentation for the FRDM-KE15Z GPIO.
#include "fsl_gpio.h"
#include "frdm_ke15z.h"
Functions
void ksdk_gpio_handle_interrupt (GPIO_Type *base, port_number_t portNumber)
void PORTAE_IRQHandler (void)
void PORTBCD_IRQHandler (void)
Detailed Description
The gpio_driver_irq_ke15z.c file containes the Generic IRQ implmentation for the FRDM-KE15Z GPIO.
Definition in file gpio_driver_irq_ke15z.c.
Function Documentation
ksdk_gpio_handle_interrupt()
void ksdk_gpio_handle_interrupt (GPIO_Type * base, port_number_t portNumber)
Definition at line 153 of file gpio_driver.c.
Referenced by PORTAE_IRQHandler(), and PORTBCD_IRQHandler().
PORTAE_IRQHandler()
void PORTAE_IRQHandler (void)
Definition at line 22 of file gpio_driver_irq_ke15z.c.
References GPIO_PORT_NUM, GPIO_TYPE, and ksdk_gpio_handle_interrupt().
PORTBCD_IRQHandler()
void PORTBCD_IRQHandler (void)
Definition at line 27 of file gpio_driver_irq_ke15z.c.
References GPIO_PORT_NUM, GPIO_TYPE, and ksdk_gpio_handle_interrupt().