ISSDK: drivers/host/data_format_service.h File Reference
data_format_service.h File Reference
The format_service.h file describes the interface and structures for the data-format standards.
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
Data Structures
struct _comm_handle_
struct _data_format_interface_
Macros
#define DATA_FORMAT_OK 0
Operation succeeded.
Typedefs
typedef struct _comm_handle_ comm_handle_t
typedef void(* DATA_FORMAT_Event_t) (void *pData)
typedef int32_t() DATA_FORMAT_Init_t(DATA_FORMAT_Event_t event, void *pInitializeData)
The interface function to initialize the data-format service.
typedef int32_t() DATA_FORMAT_Serialize_t(void *pData, uint32_t size, void *pDataElement)
The interface function to serialize the data.
typedef int32_t() DATA_FORMAT_Deserialize_t(void *pData, uint32_t size, void *pDataElement)
The interface function to deserialize the data.
typedef uint32_t size
typedef uint32_t void * pDataElement
typedef struct _data_format_interface_ data_format_interface_t
Functions
typedef int32_t (DATA_FORMAT_Append_t))(void *pData
The interface function to append the data on the formated stream.
Detailed Description
The format_service.h file describes the interface and structures for the data-format standards.
Definition in file data_format_service.h.
Macro Definition Documentation
DATA_FORMAT_OK
#define DATA_FORMAT_OK 0
Operation succeeded.
Definition at line 19 of file data_format_service.h.
Typedef Documentation
comm_handle_t
typedef struct _comm_handle_ comm_handle_t
DATA_FORMAT_Deserialize_t
typedef int32_t() DATA_FORMAT_Deserialize_t(void *pData, uint32_t size, void *pDataElement)
The interface function to deserialize the data.
Definition at line 41 of file data_format_service.h.
DATA_FORMAT_Event_t
typedef void(* DATA_FORMAT_Event_t) (void *pData)
Definition at line 34 of file data_format_service.h.
DATA_FORMAT_Init_t
typedef int32_t() DATA_FORMAT_Init_t(DATA_FORMAT_Event_t event, void *pInitializeData)
The interface function to initialize the data-format service.
Definition at line 37 of file data_format_service.h.
data_format_interface_t
typedef struct _data_format_interface_ data_format_interface_t
DATA_FORMAT_Serialize_t
typedef int32_t() DATA_FORMAT_Serialize_t(void *pData, uint32_t size, void *pDataElement)
The interface function to serialize the data.
Definition at line 39 of file data_format_service.h.
pDataElement
typedef uint32_t void* pDataElement
Definition at line 43 of file data_format_service.h.
size
typedef uint32_t size
Definition at line 43 of file data_format_service.h.
Function Documentation
int32_t()
typedef int32_t (DATA_FORMAT_Append_t)
The interface function to append the data on the formated stream.
Referenced by ADS_DeInitI2CBuses(), ADS_DeInitSPIBus(), ADS_DetectFRDM(), ADS_DetectLPC(), ADS_DetectQN(), ADS_DetectShield(), ADS_DIFF_PQuery(), ADS_FXLC95000Query(), ADS_FXLS8471Query(), ADS_FXLS8962Query(), ADS_InitI2CBuses(), ADS_InitSPIBus(), ADS_MMA9553Query(), apply_register_read(), apply_register_readall(), apply_register_write(), BOARD_DELAY_ms(), BOARD_RunADS(), BOARD_SystickElapsedTicks(), CreateAndSendPackets(), DBAP_I2C_Configure(), DBAP_I2C_Initialize(), DBAP_I2C_ReadData(), FXAS21002_I2C_Configure(), FXAS21002_I2C_Deinit(), FXAS21002_I2C_Initialize(), FXAS21002_I2C_ReadData(), FXAS21002_SPI_Configure(), FXAS21002_SPI_Deinit(), FXAS21002_SPI_Initialize(), FXAS21002_SPI_ReadData(), fxlc95000_enSensor(), FXLC95000_I2C_CheckRomMode(), FXLC95000_I2C_CommandResponse(), FXLC95000_I2C_FlashCommands(), FXLC95000_I2C_FlashPayload(), FXLC95000_I2C_Initialize(), FXLC95000_SPI_CommandResponse(), FXLC95000_SPI_Initialize(), FXLS8471Q_Idle(), FXLS8471Q_Init(), FXLS8471Q_SPI_Configure(), FXLS8471Q_SPI_Initialize(), FXLS8471Q_SPI_ReadData(), FXLS8962_I2C_Configure(), FXLS8962_I2C_DeInit(), FXLS8962_I2C_Initialize(), FXLS8962_I2C_ReadData(), FXLS8962_SPI_Configure(), FXLS8962_SPI_Deinit(), FXLS8962_SPI_Initialize(), FXLS8962_SPI_ReadData(), FXLS896x_I2C_Configure(), FXLS896x_I2C_DeInit(), FXLS896x_I2C_Initialize(), FXLS896x_I2C_ReadData(), FXLS896x_SPI_Configure(), FXLS896x_SPI_Deinit(), FXLS896x_SPI_Initialize(), FXLS896x_SPI_ReadData(), FXLS8974_I2C_Configure(), FXLS8974_I2C_DeInit(), FXLS8974_I2C_Initialize(), FXLS8974_I2C_ReadData(), FXLS8974_SPI_Configure(), FXLS8974_SPI_Deinit(), FXLS8974_SPI_Initialize(), FXLS8974_SPI_ReadData(), FXOS8700_I2C_Configure(), FXOS8700_I2C_Initialize(), FXOS8700_I2C_ReadData(), FXOS8700_Idle(), FXOS8700_Init(), FXOS8700_ReadMagData(), FXOS8700_SPI_Configure(), FXOS8700_SPI_Initialize(), FXOS8700_SPI_ReadData(), FXPQ3115_I2C_Configure(), FXPQ3115_I2C_DeInit(), FXPQ3115_I2C_Initialize(), FXPQ3115_I2C_ReadData(), HOST_Configure(), HOST_Initialize(), Host_IO_Receive(), HOST_Receive(), HOST_Send(), ISL29023_I2C_Configure(), ISL29023_I2C_DeInit(), ISL29023_I2C_Initialize(), ISL29023_I2C_ReadData(), MAG3110_I2C_Configure(), MAG3110_I2C_DeInit(), MAG3110_I2C_Initialize(), MAG3110_I2C_ReadData(), MAG3110_Idle(), MAG3110_Init(), main(), MMA845x_I2C_Configure(), MMA845x_I2C_Initialize(), MMA845x_I2C_ReadData(), MMA8491Q_I2C_Initialize(), MMA8491Q_I2C_ReadData(), MMA865x_I2C_Configure(), MMA865x_I2C_DeInit(), MMA865x_I2C_Initialize(), MMA865x_I2C_ReadData(), MMA9553_I2C_CommandResponse(), MMA9553_I2C_Configure(), MMA9553_I2C_DeInit(), MMA9553_I2C_Initialize(), MMA9553_SPI_CommandResponse(), MMA9553_SPI_Configure(), MMA9553_SPI_DeInit(), MMA9553_SPI_Initialize(), MPL3115_I2C_Configure(), MPL3115_I2C_DeInit(), MPL3115_I2C_Initialize(), MPL3115_I2C_ReadData(), perform_selftest(), Register_I2C_BlockWrite(), Register_I2C_Read(), Register_I2C_Write(), Register_SPI_BlockWrite(), Register_SPI_Read(), Register_SPI_Write(), Sensor_I2C_BlockWrite(), Sensor_I2C_Read(), Sensor_I2C_Write(), Sensor_SPI_BlockWrite(), Sensor_SPI_Read(), Sensor_SPI_Write(), and update_dropdown_selection().