ISSDK: drivers/gpio/kinetis/gpio_driver_irq_kw41z.c File Reference
gpio_driver_irq_kw41z.c File Reference
#include "fsl_gpio.h"
#include "frdm_kw41z.h"
Functions
void ksdk_gpio_handle_interrupt (GPIO_Type *base, port_number_t portNumber)
void PORTA_IRQHandler (void)
void PORTB_PORTC_IRQHandler (void)
Function Documentation
ksdk_gpio_handle_interrupt()
void ksdk_gpio_handle_interrupt (GPIO_Type * base, port_number_t portNumber)
Definition at line 153 of file gpio_driver.c.
Referenced by PORTA_IRQHandler(), and PORTB_PORTC_IRQHandler().
PORTA_IRQHandler()
void PORTA_IRQHandler (void)
Definition at line 22 of file gpio_driver_irq_kw41z.c.
References ksdk_gpio_handle_interrupt(), and PORTA_NUM.
PORTB_PORTC_IRQHandler()
void PORTB_PORTC_IRQHandler (void)
Definition at line 26 of file gpio_driver_irq_kw41z.c.
References GPIO_PORT_NUM, GPIO_TYPE, and ksdk_gpio_handle_interrupt().