ISSDK: algorithms/sensorfusion/sources/calibration_storage.c File Reference
calibration_storage.c File Reference
Provides functions to store calibration to NVM.
#include <stdio.h>
#include "sensor_fusion.h"
#include "driver_KSDK_NVM.h"
#include "calibration_storage.h"
Functions
void SaveMagCalibrationToNVM (SensorFusionGlobals *sfg)
void SaveGyroCalibrationToNVM (SensorFusionGlobals *sfg)
void SaveAccelCalibrationToNVM (SensorFusionGlobals *sfg)
void EraseMagCalibrationFromNVM (void)
void EraseGyroCalibrationFromNVM (void)
void EraseAccelCalibrationFromNVM (void)
Detailed Description
Provides functions to store calibration to NVM.
Users who are not using NXP hardware will need to supply their own drivers in place of those defined here.
Definition in file calibration_storage.c.
Function Documentation
EraseAccelCalibrationFromNVM()
void EraseAccelCalibrationFromNVM (void)
Definition at line 170 of file calibration_storage.c.
References ACCEL_NVM_OFFSET, CALIBRATION_NVM_ADDR, and NVM_SetBlockFlash().
Referenced by DecodeCommandBytes().
EraseGyroCalibrationFromNVM()
void EraseGyroCalibrationFromNVM (void)
Definition at line 149 of file calibration_storage.c.
References CALIBRATION_NVM_ADDR, GYRO_NVM_OFFSET, and NVM_SetBlockFlash().
Referenced by DecodeCommandBytes().
EraseMagCalibrationFromNVM()
void EraseMagCalibrationFromNVM (void)
Definition at line 128 of file calibration_storage.c.
References CALIBRATION_NVM_ADDR, MAG_NVM_OFFSET, and NVM_SetBlockFlash().
Referenced by DecodeCommandBytes().
SaveAccelCalibrationToNVM()
void SaveAccelCalibrationToNVM (SensorFusionGlobals * sfg)
Definition at line 94 of file calibration_storage.c.
References ACCEL_NVM_OFFSET, CALIBRATION_NVM_ADDR, and NVM_SetBlockFlash().
Referenced by DecodeCommandBytes().
SaveGyroCalibrationToNVM()
void SaveGyroCalibrationToNVM (SensorFusionGlobals * sfg)
Definition at line 55 of file calibration_storage.c.
References CALIBRATION_NVM_ADDR, F_6DOF_GY_KALMAN, GYRO_NVM_OFFSET, and NVM_SetBlockFlash().
Referenced by DecodeCommandBytes().
SaveMagCalibrationToNVM()
void SaveMagCalibrationToNVM (SensorFusionGlobals * sfg)
Definition at line 21 of file calibration_storage.c.
References CALIBRATION_NVM_ADDR, MAG_NVM_OFFSET, SensorFusionGlobals::MagCal, and NVM_SetBlockFlash().
Referenced by DecodeCommandBytes().