ISSDK: boardkit/mek-mimx8qm/mekmimx8qm.h File Reference
mekmimx8qm.h File Reference
The mekmimx8qm.h file defines GPIO pin mappings and on-board sensors information for mekmimx8qm board.
#include "pin_mux.h"
#include "RTE_Device.h"
#include "gpio_driver.h"
#include "main/imx8qm_pads.h"
#include "svc/pad/pad_api.h"
Macros
#define I2C_BB_SCL_PIN SC_P_HDMI_TX0_TS_SCL
#define I2C_BB_SDA_PIN SC_P_HDMI_TX0_TS_SDA
#define I2C_BB_DRIVER Driver_I2C2
#define I2C_BB_DEVICE_INDEX I2C2_INDEX
#define I2C_BB_SIGNAL_EVENT I2C2_SignalEvent_t
#define HOST_S_DRIVER Driver_USART0
#define HOST_S_SIGNAL_EVENT HOST_SignalEvent_t
#define FXOS8700_BB_I2C_ADDR 0x1E
#define FXAS21002_BB_I2C_ADDR 0x20
#define MPL3115_BB_I2C_ADDR 0x60
#define ASK_USER_TO_RESUME(x)
#define I2C2 LPI2C2
#define I2C_Type LPI2C_Type
#define I2C_BASE_PTRS LPI2C_BASE_PTRS
#define SPI1 LPSPI1
#define SPI_Type LPSPI_Type
#define SPI_BASE_PTRS LPSPI_BASE_PTRS
#define FXAS21002_I2C_ADDR FXAS21002_BB_I2C_ADDR
#define FXOS8700_I2C_ADDR FXOS8700_BB_I2C_ADDR
#define MPL3115_I2C_ADDR MPL3115_BB_I2C_ADDR
#define SMC NULL
Functions
status_t SMC_SetPowerModeWait (void *)
Configures the system to WAIT power mode. API name used from Kinetis family to maintain compatibility.
status_t SMC_SetPowerModeVlpr (void *)
Configures the system to VLPR power mode. API name used from Kinetis family to maintain compatibility.
Detailed Description
The mekmimx8qm.h file defines GPIO pin mappings and on-board sensors information for mekmimx8qm board.
Definition in file mekmimx8qm.h.
Macro Definition Documentation
ASK_USER_TO_RESUME
#define ASK_USER_TO_RESUME (x)
Value:
static volatile bool askResume = true;                                             \
    static uint16_t samplesToProcess = x - 1;                                          \
    if (askResume && !samplesToProcess--)                                              \
    {                                                                                  \
        PRINTF("\r\n Specified samples processed, press any key to continue... \r\n"); \
        GETCHAR();                                                                     \
        askResume = false;                                                             \
    }
Definition at line 49 of file mekmimx8qm.h.
FXAS21002_BB_I2C_ADDR
#define FXAS21002_BB_I2C_ADDR 0x20
Definition at line 39 of file mekmimx8qm.h.
FXAS21002_I2C_ADDR
#define FXAS21002_I2C_ADDR FXAS21002_BB_I2C_ADDR
Definition at line 68 of file mekmimx8qm.h.
FXOS8700_BB_I2C_ADDR
#define FXOS8700_BB_I2C_ADDR 0x1E
Definition at line 34 of file mekmimx8qm.h.
FXOS8700_I2C_ADDR
#define FXOS8700_I2C_ADDR FXOS8700_BB_I2C_ADDR
Definition at line 69 of file mekmimx8qm.h.
HOST_S_DRIVER
#define HOST_S_DRIVER Driver_USART0
Definition at line 30 of file mekmimx8qm.h.
HOST_S_SIGNAL_EVENT
#define HOST_S_SIGNAL_EVENT HOST_SignalEvent_t
Definition at line 31 of file mekmimx8qm.h.
I2C2
#define I2C2 LPI2C2
Definition at line 60 of file mekmimx8qm.h.
I2C_BASE_PTRS
#define I2C_BASE_PTRS LPI2C_BASE_PTRS
Definition at line 62 of file mekmimx8qm.h.
I2C_BB_DEVICE_INDEX
#define I2C_BB_DEVICE_INDEX I2C2_INDEX
Definition at line 26 of file mekmimx8qm.h.
I2C_BB_DRIVER
#define I2C_BB_DRIVER Driver_I2C2
Definition at line 25 of file mekmimx8qm.h.
I2C_BB_SCL_PIN
#define I2C_BB_SCL_PIN SC_P_HDMI_TX0_TS_SCL
Definition at line 23 of file mekmimx8qm.h.
I2C_BB_SDA_PIN
#define I2C_BB_SDA_PIN SC_P_HDMI_TX0_TS_SDA
Definition at line 24 of file mekmimx8qm.h.
I2C_BB_SIGNAL_EVENT
#define I2C_BB_SIGNAL_EVENT I2C2_SignalEvent_t
Definition at line 27 of file mekmimx8qm.h.
I2C_Type
#define I2C_Type LPI2C_Type
Definition at line 61 of file mekmimx8qm.h.
MPL3115_BB_I2C_ADDR
#define MPL3115_BB_I2C_ADDR 0x60
Definition at line 44 of file mekmimx8qm.h.
MPL3115_I2C_ADDR
#define MPL3115_I2C_ADDR MPL3115_BB_I2C_ADDR
Definition at line 70 of file mekmimx8qm.h.
SMC
#define SMC NULL
Definition at line 73 of file mekmimx8qm.h.
SPI1
#define SPI1 LPSPI1
Definition at line 63 of file mekmimx8qm.h.
SPI_BASE_PTRS
#define SPI_BASE_PTRS LPSPI_BASE_PTRS
Definition at line 65 of file mekmimx8qm.h.
SPI_Type
#define SPI_Type LPSPI_Type
Definition at line 64 of file mekmimx8qm.h.
Function Documentation
SMC_SetPowerModeVlpr()
status_t SMC_SetPowerModeVlpr (void * arg)
Configures the system to VLPR power mode. API name used from Kinetis family to maintain compatibility.
Parameters
Power peripheral base address (dummy).
Returns
Configuration error code.
Definition at line 169 of file lpc54114.c.
Referenced by BOARD_BootClockVLPR(), fxlc95000_enSensor(), and main().
SMC_SetPowerModeWait()
status_t SMC_SetPowerModeWait (void * arg)
Configures the system to WAIT power mode. API name used from Kinetis family to maintain compatibility.
Parameters
Power peripheral base address (dummy).
Returns
Configuration error code.
Definition at line 155 of file lpc54114.c.
Referenced by main().