ISSDK: algorithms/sensorfusion/sources/control_lpc.c File Reference
control_lpc.c File Reference
Defines control sub-system for LPC54114.
#include "fsl_debug_console.h"
#include "board.h"
#include "pin_mux.h"
#include "fsl_usart.h"
#include "sensor_fusion.h"
#include "control.h"
Functions
void myUART_WriteByte (USART_Type *base, uint8_t data)
int8_t writeControlPort (ControlSubsystem *pComm, uint8_t buffer[], uint16_t nbytes)
void WIRED_USART_IRQHandler (void)
int8_t initializeControlPort (ControlSubsystem *pComm)
Initialize the control subsystem and all related hardware.
Variables
uint8_t sUARTOutputBuffer [256]
main output buffer defined in control.c
SensorFusionGlobals sfg
This is the primary sensor fusion data structure.
Detailed Description
Defines control sub-system for LPC54114.
This file contains a USART implementation of the control subsystem. The command interpreter and streaming functions are contained in two separate files. So you can easily swap those out with only minor changes here.
Definition in file control_lpc.c.
Function Documentation
initializeControlPort()
int8_t initializeControlPort (ControlSubsystem * pComm)
Initialize the control subsystem and all related hardware.
Call this once to initialize structures, ports, etc.
Parameters
pComm pointer to the control subystem structure
Definition at line 69 of file control_lpc.c.
References ControlSubsystem::AccelCalPacketOn, ControlSubsystem::AltPacketOn, ControlSubsystem::AngularVelocityPacketOn, BOARD_DEBUG_UART_BAUDRATE, BOARD_DEBUG_UART_CLK_ATTACH, CreateAndSendPackets(), ControlSubsystem::DebugPacketOn, ControlSubsystem::DefaultQuaternionPacketType, Q3, ControlSubsystem::QuaternionPacketType, ControlSubsystem::RPCPacketOn, ControlSubsystem::stream, WIRED_USART, WIRED_USART_CLK_FREQ, WIRED_USART_IRQn, ControlSubsystem::write, and writeControlPort().
myUART_WriteByte()
void myUART_WriteByte (USART_Type * base, uint8_t data)
Definition at line 33 of file control_lpc.c.
Referenced by writeControlPort().
WIRED_USART_IRQHandler()
void WIRED_USART_IRQHandler (void)
Definition at line 55 of file control_lpc.c.
References data, DecodeCommandBytes(), and WIRED_USART.
writeControlPort()
int8_t writeControlPort (ControlSubsystem * pComm, uint8_t buffer[], uint16_t nbytes)
Definition at line 44 of file control_lpc.c.
References myUART_WriteByte(), and WIRED_USART.
Referenced by initializeControlPort().
Variable Documentation
sfg
SensorFusionGlobals sfg
This is the primary sensor fusion data structure.
Definition at line 75 of file orientaion_application_baremetal_agm01.c.
sUARTOutputBuffer
uint8_t sUARTOutputBuffer[256]
main output buffer defined in control.c
Definition at line 24 of file control_lpc.c.