ISSDK: algorithms/sensorfusion/sources/approximations.h File Reference
approximations.h File Reference
Math approximations file.
Functions
float fasin_deg (float x)
float facos_deg (float x)
float fatan_deg (float x)
float fatan2_deg (float y, float x)
float fatan_15deg (float x)
Detailed Description
Math approximations file.
Significant efficiencies were found by creating a set of trig functions which trade off precision for improved power/CPU performance. Full details are included in Application Note AN5015: Trigonometry Approximations
Definition in file approximations.h.
Function Documentation
facos_deg()
float facos_deg (float x)
Definition at line 43 of file approximations.c.
References fatan_deg().
Referenced by fAndroidAnglesDegFromRotationMatrix(), fNEDAnglesDegFromRotationMatrix(), and fWin8AnglesDegFromRotationMatrix().
fasin_deg()
float fasin_deg (float x)
Definition at line 28 of file approximations.c.
References fatan_deg().
Referenced by fAndroidAnglesDegFromRotationMatrix(), feCompassAndroid(), feCompassNED(), feCompassWin8(), fNEDAnglesDegFromRotationMatrix(), and fWin8AnglesDegFromRotationMatrix().
fatan2_deg()
float fatan2_deg (float y, float x)
Definition at line 109 of file approximations.c.
References fatan_deg().
Referenced by fAndroidAnglesDegFromRotationMatrix(), fNEDAnglesDegFromRotationMatrix(), and fWin8AnglesDegFromRotationMatrix().
fatan_15deg()
float fatan_15deg (float x)
Definition at line 139 of file approximations.c.
References PADE_A, PADE_B, and PADE_C.
Referenced by fatan_deg().
fatan_deg()
float fatan_deg (float x)
Definition at line 59 of file approximations.c.
References fatan_15deg(), TAN15DEG, and TAN30DEG.
Referenced by facos_deg(), fasin_deg(), fatan2_deg(), and fWin8AnglesDegFromRotationMatrix().