ISSDK: algorithms/sensorfusion/sources/driver_systick.c File Reference
driver_systick.c File Reference
Encapsulates the ARM sysTick counter, which is used for benchmarking.
#include "sensor_fusion.h"
#include "drivers.h"
Macros
#define SYST_CSR SysTick->CTRL
#define SYST_RVR SysTick->LOAD
#define SYST_CVR SysTick->VAL
Functions
void ARM_systick_enable (void)
void ARM_systick_start_ticks (int32 *pstart)
int32 ARM_systick_elapsed_ticks (int32 start_ticks)
void ARM_systick_delay_ms (uint32 iSystemCoreClock, uint32 delay_ms)
Detailed Description
Encapsulates the ARM sysTick counter, which is used for benchmarking.
Definition in file driver_systick.c.
Macro Definition Documentation
SYST_CSR
#define SYST_CSR SysTick->CTRL
Definition at line 17 of file driver_systick.c.
Referenced by ARM_systick_enable().
SYST_CVR
#define SYST_CVR SysTick->VAL
Definition at line 19 of file driver_systick.c.
Referenced by ARM_systick_elapsed_ticks(), and ARM_systick_start_ticks().
SYST_RVR
#define SYST_RVR SysTick->LOAD
Definition at line 18 of file driver_systick.c.
Referenced by ARM_systick_elapsed_ticks(), and ARM_systick_enable().
Function Documentation
ARM_systick_delay_ms()
void ARM_systick_delay_ms (uint32 iSystemCoreClock, uint32 delay_ms)
Definition at line 54 of file driver_systick.c.
References ARM_systick_elapsed_ticks(), and ARM_systick_start_ticks().
Referenced by initializeFusionEngine().
ARM_systick_elapsed_ticks()
int32 ARM_systick_elapsed_ticks (int32 start_ticks)
Definition at line 43 of file driver_systick.c.
References SYST_CVR, and SYST_RVR.
Referenced by ARM_systick_delay_ms(), and fFuseSensors().
ARM_systick_enable()
void ARM_systick_enable (void)
Definition at line 26 of file driver_systick.c.
References SYST_CSR, and SYST_RVR.
Referenced by initializeFusionEngine().
ARM_systick_start_ticks()
void ARM_systick_start_ticks (int32 * pstart)
Definition at line 34 of file driver_systick.c.
References SYST_CVR.
Referenced by ARM_systick_delay_ms(), and fFuseSensors().