ISSDK: algorithms/sensorfusion/sources/main_baremetal.c File Reference
main_baremetal.c File Reference
Bare metal implementation of sensor fusion on FRDM-K64F.
#include "fsl_debug_console.h"
#include "pin_mux.h"
#include "clock_config.h"
#include "board.h"
#include "fsl_port.h"
#include "fsl_pit.h"
#include "fsl_i2c.h"
#include "register_io_i2c.h"
#include "fsl_i2c_cmsis.h"
#include "fxas21002.h"
#include "mpl3115.h"
#include "fxos8700.h"
#include "sensor_fusion.h"
#include "control.h"
#include "status.h"
#include "drivers.h"
#include "driver_pit.h"
Functions
int main (void)
This is a bare-metal implementation of the NXP sensor fusion demo build.
Variables
registerDeviceInfo_t i2cBusInfo
SensorFusionGlobals sfg
This is the primary sensor fusion data structure.
struct ControlSubsystem controlSubsystem
used for serial communications
struct StatusSubsystem statusSubsystem
provides visual (usually LED) status indicator
struct PhysicalSensor sensors [3]
This implementation uses up to 3 sensors.
Detailed Description
Bare metal implementation of sensor fusion on FRDM-K64F.
This file shows the recommended way to incorporate sensor fusion capabilities into a bare metal (no RTOS) project.
Definition in file main_baremetal.c.
Function Documentation
main()
int main (void)
This is a bare-metal implementation of the NXP sensor fusion demo build.
Definition at line 55 of file main_baremetal.c.
References SensorFusionGlobals::applyPerturbation, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), SensorFusionGlobals::conditionSensorReadings, controlSubsystem, FUSION_HZ, FXAS21002_I2C_ADDR, FXAS21002_Init(), FXAS21002_Read(), FXOS8700_I2C_ADDR, FXOS8700_Init(), FXOS8700_Read(), I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, I2Cdrv, initializeControlPort(), SensorFusionGlobals::initializeFusionEngine, initializeStatusSubsystem(), initSensorFusionGlobals(), SensorFusionGlobals::installSensor, SensorFusionGlobals::loopcounter, MPL3115_I2C_ADDR, MPL3115_Init(), MPL3115_Read(), NORMAL, SensorFusionGlobals::pControlSubsystem, pit_init(), pitIsrFlag, SensorFusionGlobals::queueStatus, SensorFusionGlobals::readSensors, SensorFusionGlobals::runFusion, sensors, SensorFusionGlobals::setStatus, statusSubsystem, ControlSubsystem::stream, sUARTOutputBuffer, and SensorFusionGlobals::updateStatus.
Variable Documentation
controlSubsystem
struct ControlSubsystem controlSubsystem
used for serial communications
Definition at line 50 of file main_baremetal.c.
Referenced by main().
i2cBusInfo
registerDeviceInfo_t i2cBusInfo
Initial value:
= {
    .deviceInstance     = I2C_S_DEVICE_INDEX,
    .functionParam      = SMC,
    .idleFunction       = (registeridlefunction_t) SMC_SetPowerModeWait
}
Definition at line 42 of file main_baremetal.c.
sensors
struct PhysicalSensor sensors[3]
This implementation uses up to 3 sensors.
Definition at line 52 of file main_baremetal.c.
Referenced by main().
sfg
SensorFusionGlobals sfg
This is the primary sensor fusion data structure.
Definition at line 49 of file main_baremetal.c.
statusSubsystem
struct StatusSubsystem statusSubsystem
provides visual (usually LED) status indicator
Definition at line 51 of file main_baremetal.c.
Referenced by main().