ISSDK: algorithms/sensorfusion/sources/driver_KSDK_NVM.c File Reference
driver_KSDK_NVM.c File Reference
middleware driver for NVM on Kinetis devices
#include "sensor_fusion.h"
#include "driver_KSDK_NVM.h"
#include "fsl_flash.h"
Macros
#define ERROR 1
#define SUCCESS 0;
Functions
byte NVM_SetBlockFlash (uint8_t *Source, uint32_t Dest, uint16_t Count)
Detailed Description
middleware driver for NVM on Kinetis devices
Definition in file driver_KSDK_NVM.c.
Macro Definition Documentation
ERROR
#define ERROR 1
Definition at line 21 of file driver_KSDK_NVM.c.
Referenced by NVM_SetBlockFlash().
SUCCESS
#define SUCCESS 0;
Definition at line 22 of file driver_KSDK_NVM.c.
Referenced by NVM_SetBlockFlash().
Function Documentation
NVM_SetBlockFlash()
byte NVM_SetBlockFlash (uint8_t * Source, uint32_t Dest, uint16_t Count)
Definition at line 24 of file driver_KSDK_NVM.c.
References CALIBRATION_NVM_ADDR, ERROR, FLASH_ERASE_KEY, FLASH_SECTOR_SIZE_PROPERTY, NVM_PAGE_NUMBER, NVM_SECTOR_NUMBER, NVM_SetBlockFlash(), SUCCESS, and SystemCoreClock.
Referenced by EraseAccelCalibrationFromNVM(), EraseGyroCalibrationFromNVM(), EraseMagCalibrationFromNVM(), NVM_SetBlockFlash(), SaveAccelCalibrationToNVM(), SaveGyroCalibrationToNVM(), and SaveMagCalibrationToNVM().