ISSDK: algorithms/sensorfusion/sources/main_agmp03_freertos_two_tasks.c File Reference
main_agmp03_freertos_two_tasks.c File Reference
FreeRTOS (two task) implementation of sensor fusion.
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "timers.h"
#include "event_groups.h"
#include "fsl_debug_console.h"
#include "pin_mux.h"
#include "clock_config.h"
#include "board.h"
#include "fsl_port.h"
#include "fsl_i2c.h"
#include "fxas21002.h"
#include "fxls8962.h"
#include "mag3110.h"
#include "register_io_i2c.h"
#include "fsl_i2c_cmsis.h"
#include "sensor_fusion.h"
#include "control.h"
#include "status.h"
#include "drivers.h"
Functions
int main (void)
This is a FreeRTOS (dual task) implementation of the NXP sensor fusion demo build.
Variables
SensorFusionGlobals sfg
This is the primary sensor fusion data structure.
ControlSubsystem controlSubsystem
used for serial communications
StatusSubsystem statusSubsystem
provides visual (usually LED) status indicator
struct PhysicalSensor sensors [4]
This implementation uses four physical sensors.
EventGroupHandle_t event_group = NULL
registerDeviceInfo_t i2cBusInfo
Detailed Description
FreeRTOS (two task) implementation of sensor fusion.
This file shows one recommended way to incorporate sensor fusion capabilities into a FreeRTOS project.
Definition in file main_agmp03_freertos_two_tasks.c.
Function Documentation
main()
int main (void)
This is a FreeRTOS (dual task) implementation of the NXP sensor fusion demo build.
Definition at line 61 of file main_agmp03_freertos_two_tasks.c.
References BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), event_group, FXAS21002_I2C_ADDR, FXAS21002_Init(), FXAS21002_Read(), FXLS8962_I2C_ADDR, FXLS8962_Init(), FXLS8962_Read(), I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, I2Cdrv, initializeControlPort(), SensorFusionGlobals::initializeFusionEngine, initializeStatusSubsystem(), initSensorFusionGlobals(), SensorFusionGlobals::installSensor, MAG3110_I2C_ADDR, MAG3110_Init(), MAG3110_Read(), MPL3115_I2C_ADDR, MPL3115_Init(), MPL3115_Read(), and sensors.
Variable Documentation
controlSubsystem
ControlSubsystem controlSubsystem
used for serial communications
Definition at line 46 of file main_agmp03_freertos_two_tasks.c.
event_group
EventGroupHandle_t event_group = NULL
Definition at line 49 of file main_agmp03_freertos_two_tasks.c.
Referenced by main().
i2cBusInfo
registerDeviceInfo_t i2cBusInfo
Initial value:
= {
    .deviceInstance     = I2C_S_DEVICE_INDEX,
    .functionParam      = NULL,
    .idleFunction       = NULL
}
Definition at line 51 of file main_agmp03_freertos_two_tasks.c.
sensors
struct PhysicalSensor sensors[4]
This implementation uses four physical sensors.
Definition at line 48 of file main_agmp03_freertos_two_tasks.c.
Referenced by main().
sfg
SensorFusionGlobals sfg
This is the primary sensor fusion data structure.
Definition at line 45 of file main_agmp03_freertos_two_tasks.c.
statusSubsystem
StatusSubsystem statusSubsystem
provides visual (usually LED) status indicator
Definition at line 47 of file main_agmp03_freertos_two_tasks.c.