ISSDK: algorithms/sensorfusion/sources/main_baremetal_agm04.c File Reference
main_baremetal_agm04.c File Reference
Bare metal implementation of sensor fusion on FRDM-K64F/FRDM-STBC-AGM04 using MMA8652 (Accel), FXAS21002 (Gyro) and MAG3110 (Mag).
#include "fsl_debug_console.h"
#include "board.h"
#include "pin_mux.h"
#include "clock_config.h"
#include "fsl_port.h"
#include "fsl_i2c.h"
#include "fsl_i2c_cmsis.h"
#include "fsl_dspi_cmsis.h"
#include "register_io_i2c.h"
#include "fsl_pit.h"
#include "sensor_fusion.h"
#include "control.h"
#include "status.h"
#include "drivers.h"
#include "driver_pit.h"
Functions
int main (void)
This is a FreeRTOS (dual task) implementation of the NXP sensor fusion demo build.
Variables
SensorFusionGlobals sfg
This is the primary sensor fusion data structure.
ControlSubsystem controlSubsystem
used for serial communications
StatusSubsystem statusSubsystem
provides visual (usually LED) status indicator
struct PhysicalSensor sensors [3]
This implementation uses three physical sensors.
registerDeviceInfo_t i2cBusInfo
Detailed Description
Bare metal implementation of sensor fusion on FRDM-K64F/FRDM-STBC-AGM04 using MMA8652 (Accel), FXAS21002 (Gyro) and MAG3110 (Mag).
Note
This file shows one recommended way to incorporate sensor fusion capabilities into a bare metal project.
Definition in file main_baremetal_agm04.c.
Function Documentation
main()
int main (void)
This is a FreeRTOS (dual task) implementation of the NXP sensor fusion demo build.
Definition at line 49 of file main_baremetal_agm04.c.
References SensorFusionGlobals::applyPerturbation, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), SensorFusionGlobals::conditionSensorReadings, FUSION_HZ, FXAS21002_I2C_ADDR, FXAS21002_Init(), FXAS21002_Read(), I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, I2Cdrv, initializeControlPort(), SensorFusionGlobals::initializeFusionEngine, initializeStatusSubsystem(), initSensorFusionGlobals(), SensorFusionGlobals::installSensor, SensorFusionGlobals::loopcounter, MAG3110_I2C_ADDR, MAG3110_Init(), MAG3110_Read(), MMA8652_I2C_ADDR, MMA8652_Init(), MMA8652_Read(), NORMAL, SensorFusionGlobals::pControlSubsystem, pit_init(), pitIsrFlag, SensorFusionGlobals::queueStatus, SensorFusionGlobals::readSensors, SensorFusionGlobals::runFusion, sensors, SensorFusionGlobals::setStatus, ControlSubsystem::stream, sUARTOutputBuffer, and SensorFusionGlobals::updateStatus.
Variable Documentation
controlSubsystem
ControlSubsystem controlSubsystem
used for serial communications
Definition at line 38 of file main_baremetal_agm04.c.
i2cBusInfo
registerDeviceInfo_t i2cBusInfo
Initial value:
= {
    .deviceInstance     = I2C_S_DEVICE_INDEX,
    .functionParam      = NULL,
    .idleFunction       = NULL
}
Definition at line 42 of file main_baremetal_agm04.c.
sensors
struct PhysicalSensor sensors[3]
This implementation uses three physical sensors.
Definition at line 40 of file main_baremetal_agm04.c.
Referenced by main().
sfg
SensorFusionGlobals sfg
This is the primary sensor fusion data structure.
Definition at line 37 of file main_baremetal_agm04.c.
statusSubsystem
StatusSubsystem statusSubsystem
provides visual (usually LED) status indicator
Definition at line 39 of file main_baremetal_agm04.c.