ISSDK: algorithms/sensorfusion/sources/status.h File Reference
status.h File Reference
Application-specific status subsystem.
Data Structures
struct StatusSubsystem
StatusSubsystem() provides an object-like interface for communicating status to the user.
Typedefs
typedef struct StatusSubsystem StatusSubsystem
StatusSubsystem() provides an object-like interface for communicating status to the user.
Functions
void initializeStatusSubsystem (StatusSubsystem *pStatus)
Detailed Description
Application-specific status subsystem.
Applications may change how they choose to display status information. The default implementation here uses LEDs on NXP Freedom boards. You may swap out implementations as long as the "Required" methods and states are retained.
Definition in file status.h.
Typedef Documentation
StatusSubsystem
typedef struct StatusSubsystem StatusSubsystem
StatusSubsystem() provides an object-like interface for communicating status to the user.
Function Documentation
initializeStatusSubsystem()
void initializeStatusSubsystem (StatusSubsystem * pStatus)
initializeStatusSubsystem() should be called once at startup to initialize the data structure and to put hardware into the proper state for communicating status.
Parameters
pStatus pointer to the status subsystem
Definition at line 165 of file status.c.
References BOARD_LED_GREEN_GPIO_PIN, BOARD_LED_GREEN_GPIO_PORT, BOARD_LED_RED_GPIO_PIN, BOARD_LED_RED_GPIO_PORT, gpioHandleKSDK::clockName, GREEN_LED, LED_GREEN_INIT, LED_RED_INIT, LOGIC_LED_OFF, OFF, StatusSubsystem::previous, StatusSubsystem::queue, RED_LED, StatusSubsystem::set, ssQueueStatus(), ssSetStatus(), ssTest(), ssUpdateStatus(), StatusSubsystem::test, StatusSubsystem::toggle, and StatusSubsystem::update.
Referenced by main().