ISSDK: GENERIC_DRIVER_GPIO Struct Reference
GENERIC_DRIVER_GPIO Struct Reference
Access structure of the GPIO Driver.
#include <Driver_GPIO.h>
Data Fields
GENERIC_DRIVER_VERSION(* GetVersion)(void)
void(* pin_init)(pinID_t aPinId, gpio_direction_t dir, void *apPinConfig, gpio_isr_handler_t aIsrHandler, void *apUserData)
void(* set_pin)(pinID_t aPinId)
void(* clr_pin)(pinID_t aPinId)
void(* toggle_pin)(pinID_t aPinId)
void(* write_pin)(pinID_t aPinId, uint8_t aValue)
uint32_t(* read_pin)(pinID_t aPinId)
Detailed Description
Access structure of the GPIO Driver.
Definition at line 38 of file Driver_GPIO.h.
Field Documentation
clr_pin
void(* clr_pin) (pinID_t aPinId)
Pointer to clear the pin.
Definition at line 47 of file Driver_GPIO.h.
Referenced by ADS_InitSPI_DIFF_P(), ADS_InitSPI_FXLS8471(), ADS_InitSPI_FXLS8962(), FXAS21002_SPI_Initialize(), fxlc95000_enSensor(), FXLC95000_SPI_Initialize(), FXLS8471Q_SPI_Initialize(), FXLS8962_SPI_Initialize(), FXLS896x_SPI_Initialize(), FXLS8974_SPI_Initialize(), FXOS8700_SPI_Initialize(), main(), MMA9553_SPI_Initialize(), process_host_command(), and register_spi_control().
GetVersion
GENERIC_DRIVER_VERSION(* GetVersion) (void)
Pointer to get driver version.
Definition at line 40 of file Driver_GPIO.h.
pin_init
void(* pin_init) (pinID_t aPinId, gpio_direction_t dir, void *apPinConfig, gpio_isr_handler_t aIsrHandler, void *apUserData)
Pointer to Initialize gpio Interface.
Definition at line 41 of file Driver_GPIO.h.
Referenced by ADS_DetectShield(), ADS_InitSPI_DIFF_P(), ADS_InitSPI_FXLS8471(), ADS_InitSPI_FXLS8962(), FXAS21002_SPI_Initialize(), FXLC95000_SPI_Initialize(), FXLS8471Q_Init(), FXLS8471Q_SPI_Initialize(), FXLS8962_SPI_Initialize(), FXLS896x_SPI_Initialize(), FXLS8974_SPI_Initialize(), FXOS8700_SPI_Initialize(), main(), and MMA9553_SPI_Initialize().
read_pin
uint32_t(* read_pin) (pinID_t aPinId)
< read the pin value.
Definition at line 50 of file Driver_GPIO.h.
Referenced by main().
set_pin
void(* set_pin) (pinID_t aPinId)
Pointer to set the pin.
Definition at line 46 of file Driver_GPIO.h.
Referenced by ADS_DetectShield(), ADS_InitSPI_DIFF_P(), ADS_InitSPI_FXLS8471(), ADS_InitSPI_FXLS8962(), FXAS21002_SPI_Initialize(), fxlc95000_enSensor(), FXLC95000_SPI_Initialize(), FXLS8471Q_SPI_Initialize(), FXLS8962_SPI_Initialize(), FXLS896x_SPI_Initialize(), FXLS8974_SPI_Initialize(), FXOS8700_SPI_Initialize(), main(), MMA9553_SPI_Initialize(), process_host_command(), and register_spi_control().
toggle_pin
void(* toggle_pin) (pinID_t aPinId)
Pointer to toggle the pin.
Definition at line 48 of file Driver_GPIO.h.
Referenced by main(), and process_host_command().
write_pin
void(* write_pin) (pinID_t aPinId, uint8_t aValue)
< read the pin value.
Definition at line 49 of file Driver_GPIO.h.
The documentation for this struct was generated from the following file:
drivers/gpio/Driver_GPIO.h