ISSDK: boardkit/evk-mimxrt1170/clock_config.c File Reference
clock_config.c File Reference
#include "clock_config.h"
#include "fsl_iomuxc.h"
#include "board.h"
Macros
#define DCDC_TARGET_VOLTAGE_1V 1000
#define DCDC_TARGET_VOLTAGE_1P15V 1150
#define DCDC_TARGET_VOLTAGE DCDC_TARGET_VOLTAGE_1P15V
Functions
void BOARD_InitBootClocks (void)
This function executes default configuration of clocks.
uint32_t dcdc_get_target_voltage ()
void dcdc_trim_target_1p0 (uint32_t target_voltage)
void BOARD_BootClockRUN (void)
This function executes configuration of clocks.
Variables
uint32_t SystemCoreClock
Macro Definition Documentation
DCDC_TARGET_VOLTAGE
#define DCDC_TARGET_VOLTAGE DCDC_TARGET_VOLTAGE_1P15V
Definition at line 46 of file clock_config.c.
Referenced by BOARD_BootClockRUN().
DCDC_TARGET_VOLTAGE_1P15V
#define DCDC_TARGET_VOLTAGE_1P15V 1150
Definition at line 43 of file clock_config.c.
DCDC_TARGET_VOLTAGE_1V
#define DCDC_TARGET_VOLTAGE_1V 1000
Definition at line 41 of file clock_config.c.
Function Documentation
BOARD_BootClockRUN()
void BOARD_BootClockRUN (void)
This function executes configuration of clocks.
This function executes configuration of clocks.
Parameters
void
Returns
void
Definition at line 87 of file clock_config.c.
References armPllConfig, DCDC_TARGET_VOLTAGE, dcdc_trim_target_1p0(), mcgConfig_BOARD_BootClockRUN, oscConfig_BOARD_BootClockRUN, sysPllConfig, and SystemCoreClock.
BOARD_InitBootClocks()
void BOARD_InitBootClocks (void)
This function executes default configuration of clocks.
Definition at line 25 of file clock_config.c.
References BOARD_BootClockFROHF96M(), and BOARD_BootClockRUN().
dcdc_get_target_voltage()
uint32_t dcdc_get_target_voltage ()
Definition at line 57 of file clock_config.c.
dcdc_trim_target_1p0()
void dcdc_trim_target_1p0 (uint32_t target_voltage)
Definition at line 67 of file clock_config.c.
Referenced by BOARD_BootClockRUN().
Variable Documentation
SystemCoreClock
uint32_t SystemCoreClock