ISSDK: boardkit/evk-mimxrt1170/board.h File Reference
board.h File Reference
#include "clock_config.h"
#include "fsl_common.h"
#include "fsl_gpio.h"
#include "fsl_clock.h"
Macros
#define BOARD_NAME "MIMXRT1170-EVK"
The board name.
#define DEBUG_CONSOLE_UART_INDEX 1
#define BOARD_DEBUG_UART_TYPE kSerialPort_Uart
#define BOARD_DEBUG_UART_CLK_FREQ 24000000
#define BOARD_DEBUG_UART_BASEADDR (uint32_t) LPUART1
#define BOARD_DEBUG_UART_INSTANCE 1U
#define BOARD_UART_IRQ LPUART1_IRQn
#define BOARD_UART_IRQ_HANDLER LPUART1_IRQHandler
#define BOARD_DEBUG_UART_BAUDRATE (115200U)
#define MU_IRQ_PRIORITY (2)
#define LOGIC_LED_ON (0U)
The USER_LED used for board.
#define LOGIC_LED_OFF (1U)
#define BOARD_USER_LED_GPIO GPIO9
#define BOARD_USER_LED_GPIO_PIN (3U)
#define USER_LED_INIT(output)
#define USER_LED_OFF() GPIO_PortClear(BOARD_USER_LED_GPIO, 1U << BOARD_USER_LED_GPIO_PIN)
#define USER_LED_ON() GPIO_PortSet(BOARD_USER_LED_GPIO, 1U << BOARD_USER_LED_GPIO_PIN)
#define USER_LED_TOGGLE()
#define BOARD_USER_BUTTON_GPIO GPIO13
Define the port interrupt number for the board switches.
#define BOARD_USER_BUTTON_GPIO_PIN (0U)
#define BOARD_USER_BUTTON_IRQ GPIO13_Combined_0_31_IRQn
#define BOARD_USER_BUTTON_IRQ_HANDLER GPIO13_Combined_0_31_IRQHandler
#define BOARD_USER_BUTTON_NAME "SW7"
#define BOARD_FLASH_SIZE (0x1000000U)
The board flash size.
#define BOARD_ENET0_PHY_ADDRESS (0x02U) /* Phy address of enet port 0. */
The ENET PHY address.
#define BOARD_SMARTCARD_MODULE (EMVSIM1)
#define BOARD_SMARTCARD_MODULE_IRQ (EMVSIM1_IRQn)
#define BOARD_SMARTCARD_CLOCK_MODULE_CLK_FREQ (CLOCK_GetRootClockFreq(kCLOCK_Root_Emv1))
#define BOARD_SMARTCARD_CLOCK_VALUE (4000000U)
#define BOARD_USB_PHY_D_CAL (0x0CU)
#define BOARD_USB_PHY_TXCAL45DP (0x06U)
#define BOARD_USB_PHY_TXCAL45DM (0x06U)
#define BOARD_ARDUINO_INT_IRQ (GPIO1_INT3_IRQn)
#define BOARD_ARDUINO_I2C_IRQ (LPI2C1_IRQn)
#define BOARD_ARDUINO_I2C_INDEX (1)
#define BOARD_USDHC1_BASEADDR USDHC1
#define BOARD_USDHC2_BASEADDR USDHC2
#define BOARD_USDHC_CD_GPIO_BASE GPIO9
#define BOARD_USDHC_CD_GPIO_PIN 2
#define BOARD_USDHC_CD_PORT_IRQ GPIO2_Combined_16_31_IRQn
#define BOARD_USDHC_CD_PORT_IRQ_HANDLER GPIO2_Combined_16_31_IRQHandler
#define BOARD_USDHC_CD_STATUS() (GPIO_PinRead(BOARD_USDHC_CD_GPIO_BASE, BOARD_USDHC_CD_GPIO_PIN))
#define BOARD_USDHC_CD_INTERRUPT_STATUS() (GPIO_PortGetInterruptFlags(BOARD_USDHC_CD_GPIO_BASE))
#define BOARD_USDHC_CD_CLEAR_INTERRUPT(flag) (GPIO_PortClearInterruptFlags(BOARD_USDHC_CD_GPIO_BASE, flag))
#define BOARD_USDHC_CD_GPIO_INIT()
#define BOARD_HAS_SDCARD (1U)
#define BOARD_SD_POWER_RESET_GPIO (GPIO9)
#define BOARD_SD_POWER_RESET_GPIO_PIN (14U)
#define BOARD_USDHC_CARD_INSERT_CD_LEVEL (0U)
#define BOARD_USDHC_MMCCARD_POWER_CONTROL(state)
#define BOARD_USDHC_MMCCARD_POWER_CONTROL_INIT()
#define BOARD_USDHC_SDCARD_POWER_CONTROL_INIT()
#define BOARD_USDHC_SDCARD_POWER_CONTROL(state) (GPIO_PinWrite(BOARD_SD_POWER_RESET_GPIO, BOARD_SD_POWER_RESET_GPIO_PIN, state == true ? false : true))
#define BOARD_USDHC1_CLK_FREQ 400000000U
#define BOARD_USDHC2_CLK_FREQ (CLOCK_GetSysPfdFreq(kCLOCK_Pfd0) / (CLOCK_GetDiv(kCLOCK_Usdhc2Div) + 1U))
#define BOARD_SD_HOST_BASEADDR BOARD_USDHC1_BASEADDR
#define BOARD_SD_HOST_CLK_FREQ BOARD_USDHC1_CLK_FREQ
#define BOARD_SD_HOST_IRQ USDHC1_IRQn
#define BOARD_MMC_HOST_BASEADDR BOARD_USDHC2_BASEADDR
#define BOARD_MMC_HOST_CLK_FREQ BOARD_USDHC2_CLK_FREQ
#define BOARD_MMC_HOST_IRQ USDHC2_IRQn
#define BOARD_MMC_VCCQ_SUPPLY kMMC_VoltageWindow170to195
#define BOARD_MMC_VCC_SUPPLY kMMC_VoltageWindows270to360
#define BOARD_MMC_SUPPORT_8BIT_BUS (1U)
#define BOARD_SD_HOST_SUPPORT_SDR104_FREQ (200000000U)
#define BOARD_SD_HOST_SUPPORT_HS200_FREQ (180000000U)
#define BOARD_INITGT202SHIELD_PWRON_GPIO GPIO1
The WIFI-QCA shield pin.
#define BOARD_INITGT202SHIELD_PWRON_PORT 1U
#define BOARD_INITGT202SHIELD_PWRON_GPIO_PIN 3U
#define BOARD_INITGT202SHIELD_PWRON_PIN_NAME GPIO1_3
#define BOARD_INITGT202SHIELD_PWRON_LABEL "PWRON"
#define BOARD_INITGT202SHIELD_PWRON_NAME "PWRON"
#define BOARD_INITGT202SHIELD_PWRON_DIRECTION kGPIO_DigitalOutput
#define BOARD_INITGT202SHIELD_IRQ_GPIO GPIO1
#define BOARD_INITGT202SHIELD_IRQ_PORT 1U
#define BOARD_INITGT202SHIELD_IRQ_GPIO_PIN 19U
#define BOARD_INITGT202SHIELD_IRQ_PIN_NAME GPIO1_19
#define BOARD_INITGT202SHIELD_IRQ_LABEL "IRQ"
#define BOARD_INITGT202SHIELD_IRQ_NAME "IRQ"
#define BOARD_INITGT202SHIELD_IRQ_DIRECTION kGPIO_DigitalInput
#define BOARD_INITSILEX2401SHIELD_PWRON_GPIO GPIO1
#define BOARD_INITSILEX2401SHIELD_PWRON_PORT 1U
#define BOARD_INITSILEX2401SHIELD_PWRON_GPIO_PIN 9U
#define BOARD_INITSILEX2401SHIELD_PWRON_PIN_NAME GPIO1_9
#define BOARD_INITSILEX2401SHIELD_PWRON_LABEL "PWRON"
#define BOARD_INITSILEX2401SHIELD_PWRON_NAME "PWRON"
#define BOARD_INITSILEX2401SHIELD_PWRON_DIRECTION kGPIO_DigitalOutput
#define BOARD_INITSILEX2401SHIELD_IRQ_GPIO GPIO1
#define BOARD_INITSILEX2401SHIELD_IRQ_PORT 1U
#define BOARD_INITSILEX2401SHIELD_IRQ_GPIO_PIN 11U
#define BOARD_INITSILEX2401SHIELD_IRQ_PIN_NAME GPIO1_11
#define BOARD_INITSILEX2401SHIELD_IRQ_LABEL "IRQ"
#define BOARD_INITSILEX2401SHIELD_IRQ_NAME "IRQ"
#define BOARD_INITSILEX2401SHIELD_IRQ_DIRECTION kGPIO_DigitalInput
#define BOARD_ACCEL_I2C_BASEADDR LPI2C5
#define BOARD_ACCEL_I2C_CLOCK_FREQ (CLOCK_GetRootClockFreq(kCLOCK_Root_Lpi2c5))
#define BOARD_CODEC_I2C_BASEADDR LPI2C5
#define BOARD_CODEC_I2C_INSTANCE 5U
#define BOARD_CODEC_I2C_CLOCK_SOURCE_SELECT (0U)
#define BOARD_CODEC_I2C_CLOCK_SOURCE_DIVIDER (5U)
#define BOARD_CODEC_I2C_CLOCK_FREQ (24000000U)
#define BOARD_CAMERA_I2C_BASEADDR LPI2C6
#define BOARD_CAMERA_I2C_CLOCK_ROOT kCLOCK_Root_Lpi2c6
#define BOARD_CAMERA_I2C_CLOCK_SOURCE (1U) /* OSC24M. */
#define BOARD_CAMERA_I2C_CLOCK_DIVIDER (11U) /* Divider = 12, LPI2C clock frequency 2M. */
#define BOARD_MIPI_PANEL_RST_GPIO GPIO9
The MIPI panel pins.
#define BOARD_MIPI_PANEL_RST_PIN 1
#define BOARD_MIPI_PANEL_POWER_GPIO GPIO11
#define BOARD_MIPI_PANEL_POWER_PIN 16
#define BOARD_MIPI_PANEL_BL_GPIO GPIO9
#define BOARD_MIPI_PANEL_BL_PIN 29
#define BOARD_MIPI_PANEL_TOUCH_I2C_BASEADDR LPI2C5
#define BOARD_MIPI_PANEL_TOUCH_I2C_CLOCK_ROOT kCLOCK_Root_Lpi2c5
#define BOARD_MIPI_PANEL_TOUCH_I2C_CLOCK_SOURCE (1U) /* OSC24M. */
#define BOARD_MIPI_PANEL_TOUCH_I2C_CLOCK_DIVIDER (11U) /* Divider = 12, LPI2C clock frequency 2M. */
#define BOARD_MIPI_PANEL_TOUCH_I2C_CLOCK_FREQ CLOCK_GetRootClockFreq(BOARD_MIPI_PANEL_TOUCH_I2C_CLOCK_ROOT)
#define BOARD_MIPI_PANEL_TOUCH_RST_GPIO GPIO9
#define BOARD_MIPI_PANEL_TOUCH_RST_PIN 0
#define BOARD_MIPI_PANEL_TOUCH_INT_GPIO GPIO8
#define BOARD_MIPI_PANEL_TOUCH_INT_PIN 31
#define BOARD_CAMERA_PWDN_GPIO GPIO9
The camera pins.
#define BOARD_CAMERA_PWDN_PIN 25
#define BOARD_CAMERA_RST_GPIO GPIO11
#define BOARD_CAMERA_RST_PIN 15
#define BOARD_WIFI_SD_DETECT_TYPE kSDMMCHOST_DetectCardByHostDATA3
Functions
uint32_t BOARD_DebugConsoleSrcFreq (void)
void BOARD_InitDebugConsole (void)
void BOARD_ConfigMPU (void)
void BOARD_SD_Pin_Config (uint32_t speed, uint32_t strength)
void BOARD_MMC_Pin_Config (uint32_t speed, uint32_t strength)
Macro Definition Documentation
BOARD_ACCEL_I2C_BASEADDR
#define BOARD_ACCEL_I2C_BASEADDR LPI2C5
Definition at line 236 of file board.h.
BOARD_ACCEL_I2C_CLOCK_FREQ
#define BOARD_ACCEL_I2C_CLOCK_FREQ (CLOCK_GetRootClockFreq(kCLOCK_Root_Lpi2c5))
Definition at line 238 of file board.h.
BOARD_ARDUINO_I2C_INDEX
#define BOARD_ARDUINO_I2C_INDEX (1)
Definition at line 125 of file board.h.
BOARD_ARDUINO_I2C_IRQ
#define BOARD_ARDUINO_I2C_IRQ (LPI2C1_IRQn)
Definition at line 124 of file board.h.
BOARD_ARDUINO_INT_IRQ
#define BOARD_ARDUINO_INT_IRQ (GPIO1_INT3_IRQn)
Definition at line 123 of file board.h.
BOARD_CAMERA_I2C_BASEADDR
#define BOARD_CAMERA_I2C_BASEADDR LPI2C6
Definition at line 247 of file board.h.
Referenced by BOARD_InitDebugConsole().
BOARD_CAMERA_I2C_CLOCK_DIVIDER
#define BOARD_CAMERA_I2C_CLOCK_DIVIDER (11U) /* Divider = 12, LPI2C clock frequency 2M. */
Definition at line 250 of file board.h.
Referenced by BOARD_InitDebugConsole().
BOARD_CAMERA_I2C_CLOCK_ROOT
#define BOARD_CAMERA_I2C_CLOCK_ROOT kCLOCK_Root_Lpi2c6
Definition at line 248 of file board.h.
Referenced by BOARD_InitDebugConsole().
BOARD_CAMERA_I2C_CLOCK_SOURCE
#define BOARD_CAMERA_I2C_CLOCK_SOURCE (1U) /* OSC24M. */
Definition at line 249 of file board.h.
Referenced by BOARD_InitDebugConsole().
BOARD_CAMERA_PWDN_GPIO
#define BOARD_CAMERA_PWDN_GPIO GPIO9
The camera pins.
Definition at line 273 of file board.h.
BOARD_CAMERA_PWDN_PIN
#define BOARD_CAMERA_PWDN_PIN 25
Definition at line 274 of file board.h.
BOARD_CAMERA_RST_GPIO
#define BOARD_CAMERA_RST_GPIO GPIO11
Definition at line 275 of file board.h.
BOARD_CAMERA_RST_PIN
#define BOARD_CAMERA_RST_PIN 15
Definition at line 276 of file board.h.
BOARD_CODEC_I2C_BASEADDR
#define BOARD_CODEC_I2C_BASEADDR LPI2C5
Definition at line 240 of file board.h.
BOARD_CODEC_I2C_CLOCK_FREQ
#define BOARD_CODEC_I2C_CLOCK_FREQ (24000000U)
Definition at line 244 of file board.h.
BOARD_CODEC_I2C_CLOCK_SOURCE_DIVIDER
#define BOARD_CODEC_I2C_CLOCK_SOURCE_DIVIDER (5U)
Definition at line 243 of file board.h.
BOARD_CODEC_I2C_CLOCK_SOURCE_SELECT
#define BOARD_CODEC_I2C_CLOCK_SOURCE_SELECT (0U)
Definition at line 242 of file board.h.
BOARD_CODEC_I2C_INSTANCE
#define BOARD_CODEC_I2C_INSTANCE 5U
Definition at line 241 of file board.h.
BOARD_DEBUG_UART_BASEADDR
#define BOARD_DEBUG_UART_BASEADDR (uint32_t) LPUART1
Definition at line 30 of file board.h.
BOARD_DEBUG_UART_BAUDRATE
#define BOARD_DEBUG_UART_BAUDRATE (115200U)
Definition at line 49 of file board.h.
BOARD_DEBUG_UART_CLK_FREQ
#define BOARD_DEBUG_UART_CLK_FREQ 24000000
Definition at line 27 of file board.h.
BOARD_DEBUG_UART_INSTANCE
#define BOARD_DEBUG_UART_INSTANCE 1U
Definition at line 31 of file board.h.
BOARD_DEBUG_UART_TYPE
#define BOARD_DEBUG_UART_TYPE kSerialPort_Uart
Definition at line 26 of file board.h.
BOARD_ENET0_PHY_ADDRESS
#define BOARD_ENET0_PHY_ADDRESS (0x02U) /* Phy address of enet port 0. */
The ENET PHY address.
Definition at line 110 of file board.h.
BOARD_FLASH_SIZE
#define BOARD_FLASH_SIZE (0x1000000U)
The board flash size.
Definition at line 102 of file board.h.
BOARD_HAS_SDCARD
#define BOARD_HAS_SDCARD (1U)
Definition at line 149 of file board.h.
BOARD_INITGT202SHIELD_IRQ_DIRECTION
#define BOARD_INITGT202SHIELD_IRQ_DIRECTION kGPIO_DigitalInput
Direction
Definition at line 217 of file board.h.
BOARD_INITGT202SHIELD_IRQ_GPIO
#define BOARD_INITGT202SHIELD_IRQ_GPIO GPIO1
GPIO device name: GPIO
Definition at line 211 of file board.h.
BOARD_INITGT202SHIELD_IRQ_GPIO_PIN
#define BOARD_INITGT202SHIELD_IRQ_GPIO_PIN 19U
PIO1 pin index: 19
Definition at line 213 of file board.h.
BOARD_INITGT202SHIELD_IRQ_LABEL
#define BOARD_INITGT202SHIELD_IRQ_LABEL "IRQ"
Label
Definition at line 215 of file board.h.
BOARD_INITGT202SHIELD_IRQ_NAME
#define BOARD_INITGT202SHIELD_IRQ_NAME "IRQ"
Identifier name
Definition at line 216 of file board.h.
BOARD_INITGT202SHIELD_IRQ_PIN_NAME
#define BOARD_INITGT202SHIELD_IRQ_PIN_NAME GPIO1_19
Pin name
Definition at line 214 of file board.h.
BOARD_INITGT202SHIELD_IRQ_PORT
#define BOARD_INITGT202SHIELD_IRQ_PORT 1U
PORT device index: 1
Definition at line 212 of file board.h.
BOARD_INITGT202SHIELD_PWRON_DIRECTION
#define BOARD_INITGT202SHIELD_PWRON_DIRECTION kGPIO_DigitalOutput
Direction
Definition at line 209 of file board.h.
BOARD_INITGT202SHIELD_PWRON_GPIO
#define BOARD_INITGT202SHIELD_PWRON_GPIO GPIO1
The WIFI-QCA shield pin.
GPIO device name: GPIO
Definition at line 203 of file board.h.
BOARD_INITGT202SHIELD_PWRON_GPIO_PIN
#define BOARD_INITGT202SHIELD_PWRON_GPIO_PIN 3U
PIO4 pin index: 3
Definition at line 205 of file board.h.
BOARD_INITGT202SHIELD_PWRON_LABEL
#define BOARD_INITGT202SHIELD_PWRON_LABEL "PWRON"
Label
Definition at line 207 of file board.h.
BOARD_INITGT202SHIELD_PWRON_NAME
#define BOARD_INITGT202SHIELD_PWRON_NAME "PWRON"
Identifier name
Definition at line 208 of file board.h.
BOARD_INITGT202SHIELD_PWRON_PIN_NAME
#define BOARD_INITGT202SHIELD_PWRON_PIN_NAME GPIO1_3
Pin name
Definition at line 206 of file board.h.
BOARD_INITGT202SHIELD_PWRON_PORT
#define BOARD_INITGT202SHIELD_PWRON_PORT 1U
PORT device index: 1
Definition at line 204 of file board.h.
BOARD_INITSILEX2401SHIELD_IRQ_DIRECTION
#define BOARD_INITSILEX2401SHIELD_IRQ_DIRECTION kGPIO_DigitalInput
Direction
Definition at line 233 of file board.h.
BOARD_INITSILEX2401SHIELD_IRQ_GPIO
#define BOARD_INITSILEX2401SHIELD_IRQ_GPIO GPIO1
GPIO device name: GPIO
Definition at line 227 of file board.h.
BOARD_INITSILEX2401SHIELD_IRQ_GPIO_PIN
#define BOARD_INITSILEX2401SHIELD_IRQ_GPIO_PIN 11U
PIO1 pin index: 11
Definition at line 229 of file board.h.
BOARD_INITSILEX2401SHIELD_IRQ_LABEL
#define BOARD_INITSILEX2401SHIELD_IRQ_LABEL "IRQ"
Label
Definition at line 231 of file board.h.
BOARD_INITSILEX2401SHIELD_IRQ_NAME
#define BOARD_INITSILEX2401SHIELD_IRQ_NAME "IRQ"
Identifier name
Definition at line 232 of file board.h.
BOARD_INITSILEX2401SHIELD_IRQ_PIN_NAME
#define BOARD_INITSILEX2401SHIELD_IRQ_PIN_NAME GPIO1_11
Pin name
Definition at line 230 of file board.h.
BOARD_INITSILEX2401SHIELD_IRQ_PORT
#define BOARD_INITSILEX2401SHIELD_IRQ_PORT 1U
PORT device index: 1
Definition at line 228 of file board.h.
BOARD_INITSILEX2401SHIELD_PWRON_DIRECTION
#define BOARD_INITSILEX2401SHIELD_PWRON_DIRECTION kGPIO_DigitalOutput
Direction
Definition at line 225 of file board.h.
BOARD_INITSILEX2401SHIELD_PWRON_GPIO
#define BOARD_INITSILEX2401SHIELD_PWRON_GPIO GPIO1
GPIO device name: GPIO
Definition at line 219 of file board.h.
BOARD_INITSILEX2401SHIELD_PWRON_GPIO_PIN
#define BOARD_INITSILEX2401SHIELD_PWRON_GPIO_PIN 9U
PIO4 pin index: 9
Definition at line 221 of file board.h.
BOARD_INITSILEX2401SHIELD_PWRON_LABEL
#define BOARD_INITSILEX2401SHIELD_PWRON_LABEL "PWRON"
Label
Definition at line 223 of file board.h.
BOARD_INITSILEX2401SHIELD_PWRON_NAME
#define BOARD_INITSILEX2401SHIELD_PWRON_NAME "PWRON"
Identifier name
Definition at line 224 of file board.h.
BOARD_INITSILEX2401SHIELD_PWRON_PIN_NAME
#define BOARD_INITSILEX2401SHIELD_PWRON_PIN_NAME GPIO1_9
Pin name
Definition at line 222 of file board.h.
BOARD_INITSILEX2401SHIELD_PWRON_PORT
#define BOARD_INITSILEX2401SHIELD_PWRON_PORT 1U
PORT device index: 1
Definition at line 220 of file board.h.
BOARD_MIPI_PANEL_BL_GPIO
#define BOARD_MIPI_PANEL_BL_GPIO GPIO9
Definition at line 258 of file board.h.
BOARD_MIPI_PANEL_BL_PIN
#define BOARD_MIPI_PANEL_BL_PIN 29
Definition at line 259 of file board.h.
BOARD_MIPI_PANEL_POWER_GPIO
#define BOARD_MIPI_PANEL_POWER_GPIO GPIO11
Definition at line 255 of file board.h.
BOARD_MIPI_PANEL_POWER_PIN
#define BOARD_MIPI_PANEL_POWER_PIN 16
Definition at line 256 of file board.h.
BOARD_MIPI_PANEL_RST_GPIO
#define BOARD_MIPI_PANEL_RST_GPIO GPIO9
The MIPI panel pins.
Definition at line 253 of file board.h.
BOARD_MIPI_PANEL_RST_PIN
#define BOARD_MIPI_PANEL_RST_PIN 1
Definition at line 254 of file board.h.
BOARD_MIPI_PANEL_TOUCH_I2C_BASEADDR
#define BOARD_MIPI_PANEL_TOUCH_I2C_BASEADDR LPI2C5
Definition at line 262 of file board.h.
Referenced by BOARD_InitDebugConsole().
BOARD_MIPI_PANEL_TOUCH_I2C_CLOCK_DIVIDER
#define BOARD_MIPI_PANEL_TOUCH_I2C_CLOCK_DIVIDER (11U) /* Divider = 12, LPI2C clock frequency 2M. */
Definition at line 265 of file board.h.
Referenced by BOARD_InitDebugConsole().
BOARD_MIPI_PANEL_TOUCH_I2C_CLOCK_FREQ
#define BOARD_MIPI_PANEL_TOUCH_I2C_CLOCK_FREQ CLOCK_GetRootClockFreq(BOARD_MIPI_PANEL_TOUCH_I2C_CLOCK_ROOT)
Definition at line 266 of file board.h.
BOARD_MIPI_PANEL_TOUCH_I2C_CLOCK_ROOT
#define BOARD_MIPI_PANEL_TOUCH_I2C_CLOCK_ROOT kCLOCK_Root_Lpi2c5
Definition at line 263 of file board.h.
Referenced by BOARD_InitDebugConsole().
BOARD_MIPI_PANEL_TOUCH_I2C_CLOCK_SOURCE
#define BOARD_MIPI_PANEL_TOUCH_I2C_CLOCK_SOURCE (1U) /* OSC24M. */
Definition at line 264 of file board.h.
Referenced by BOARD_InitDebugConsole().
BOARD_MIPI_PANEL_TOUCH_INT_GPIO
#define BOARD_MIPI_PANEL_TOUCH_INT_GPIO GPIO8
Definition at line 269 of file board.h.
BOARD_MIPI_PANEL_TOUCH_INT_PIN
#define BOARD_MIPI_PANEL_TOUCH_INT_PIN 31
Definition at line 270 of file board.h.
BOARD_MIPI_PANEL_TOUCH_RST_GPIO
#define BOARD_MIPI_PANEL_TOUCH_RST_GPIO GPIO9
Definition at line 267 of file board.h.
BOARD_MIPI_PANEL_TOUCH_RST_PIN
#define BOARD_MIPI_PANEL_TOUCH_RST_PIN 0
Definition at line 268 of file board.h.
BOARD_MMC_HOST_BASEADDR
#define BOARD_MMC_HOST_BASEADDR BOARD_USDHC2_BASEADDR
Definition at line 188 of file board.h.
BOARD_MMC_HOST_CLK_FREQ
#define BOARD_MMC_HOST_CLK_FREQ BOARD_USDHC2_CLK_FREQ
Definition at line 189 of file board.h.
BOARD_MMC_HOST_IRQ
#define BOARD_MMC_HOST_IRQ USDHC2_IRQn
Definition at line 190 of file board.h.
BOARD_MMC_SUPPORT_8BIT_BUS
#define BOARD_MMC_SUPPORT_8BIT_BUS (1U)
Definition at line 197 of file board.h.
BOARD_MMC_VCC_SUPPLY
#define BOARD_MMC_VCC_SUPPLY kMMC_VoltageWindows270to360
Definition at line 192 of file board.h.
BOARD_MMC_VCCQ_SUPPLY
#define BOARD_MMC_VCCQ_SUPPLY kMMC_VoltageWindow170to195
Definition at line 191 of file board.h.
BOARD_NAME
#define BOARD_NAME "MIMXRT1170-EVK"
The board name.
Definition at line 20 of file board.h.
BOARD_SD_HOST_BASEADDR
#define BOARD_SD_HOST_BASEADDR BOARD_USDHC1_BASEADDR
Definition at line 184 of file board.h.
BOARD_SD_HOST_CLK_FREQ
#define BOARD_SD_HOST_CLK_FREQ BOARD_USDHC1_CLK_FREQ
Definition at line 185 of file board.h.
BOARD_SD_HOST_IRQ
#define BOARD_SD_HOST_IRQ USDHC1_IRQn
Definition at line 186 of file board.h.
BOARD_SD_HOST_SUPPORT_HS200_FREQ
#define BOARD_SD_HOST_SUPPORT_HS200_FREQ (180000000U)
Definition at line 200 of file board.h.
BOARD_SD_HOST_SUPPORT_SDR104_FREQ
#define BOARD_SD_HOST_SUPPORT_SDR104_FREQ (200000000U)
Definition at line 199 of file board.h.
BOARD_SD_POWER_RESET_GPIO
#define BOARD_SD_POWER_RESET_GPIO (GPIO9)
Definition at line 150 of file board.h.
BOARD_SD_POWER_RESET_GPIO_PIN
#define BOARD_SD_POWER_RESET_GPIO_PIN (14U)
Definition at line 151 of file board.h.
BOARD_SMARTCARD_CLOCK_MODULE_CLK_FREQ
#define BOARD_SMARTCARD_CLOCK_MODULE_CLK_FREQ (CLOCK_GetRootClockFreq(kCLOCK_Root_Emv1))
Definition at line 115 of file board.h.
BOARD_SMARTCARD_CLOCK_VALUE
#define BOARD_SMARTCARD_CLOCK_VALUE (4000000U)
SMARTCARD clock frequency
Definition at line 116 of file board.h.
BOARD_SMARTCARD_MODULE
#define BOARD_SMARTCARD_MODULE (EMVSIM1)
SMARTCARD communicational module instance
Definition at line 113 of file board.h.
BOARD_SMARTCARD_MODULE_IRQ
#define BOARD_SMARTCARD_MODULE_IRQ (EMVSIM1_IRQn)
SMARTCARD communicational module IRQ handler
Definition at line 114 of file board.h.
BOARD_UART_IRQ
#define BOARD_UART_IRQ LPUART1_IRQn
Definition at line 32 of file board.h.
BOARD_UART_IRQ_HANDLER
#define BOARD_UART_IRQ_HANDLER LPUART1_IRQHandler
Definition at line 33 of file board.h.
BOARD_USB_PHY_D_CAL
#define BOARD_USB_PHY_D_CAL (0x0CU)
Definition at line 119 of file board.h.
BOARD_USB_PHY_TXCAL45DM
#define BOARD_USB_PHY_TXCAL45DM (0x06U)
Definition at line 121 of file board.h.
BOARD_USB_PHY_TXCAL45DP
#define BOARD_USB_PHY_TXCAL45DP (0x06U)
Definition at line 120 of file board.h.
BOARD_USDHC1_BASEADDR
#define BOARD_USDHC1_BASEADDR USDHC1
Definition at line 126 of file board.h.
BOARD_USDHC1_CLK_FREQ
#define BOARD_USDHC1_CLK_FREQ 400000000U
Definition at line 181 of file board.h.
BOARD_USDHC2_BASEADDR
#define BOARD_USDHC2_BASEADDR USDHC2
Definition at line 127 of file board.h.
BOARD_USDHC2_CLK_FREQ
#define BOARD_USDHC2_CLK_FREQ (CLOCK_GetSysPfdFreq(kCLOCK_Pfd0) / (CLOCK_GetDiv(kCLOCK_Usdhc2Div) + 1U))
Definition at line 182 of file board.h.
BOARD_USDHC_CARD_INSERT_CD_LEVEL
#define BOARD_USDHC_CARD_INSERT_CD_LEVEL (0U)
Definition at line 153 of file board.h.
BOARD_USDHC_CD_CLEAR_INTERRUPT
#define BOARD_USDHC_CD_CLEAR_INTERRUPT (flag) (GPIO_PortClearInterruptFlags(BOARD_USDHC_CD_GPIO_BASE, flag))
Definition at line 136 of file board.h.
BOARD_USDHC_CD_GPIO_BASE
#define BOARD_USDHC_CD_GPIO_BASE GPIO9
Definition at line 128 of file board.h.
BOARD_USDHC_CD_GPIO_INIT
#define BOARD_USDHC_CD_GPIO_INIT ()
Value:
{                                                                                       \
        gpio_pin_config_t sw_config = {                                                     \
            kGPIO_DigitalInput,                                                             \
            0,                                                                              \
            kGPIO_IntRisingOrFallingEdge,                                                   \
        };                                                                                  \
        GPIO_PinInit(BOARD_USDHC_CD_GPIO_BASE, BOARD_USDHC_CD_GPIO_PIN, &sw_config);        \
        GPIO_PortEnableInterrupts(BOARD_USDHC_CD_GPIO_BASE, 1U << BOARD_USDHC_CD_GPIO_PIN); \
        GPIO_PortClearInterruptFlags(BOARD_USDHC_CD_GPIO_BASE, ~0);                         \
    }
Definition at line 138 of file board.h.
BOARD_USDHC_CD_GPIO_PIN
#define BOARD_USDHC_CD_GPIO_PIN 2
Definition at line 129 of file board.h.
BOARD_USDHC_CD_INTERRUPT_STATUS
#define BOARD_USDHC_CD_INTERRUPT_STATUS () (GPIO_PortGetInterruptFlags(BOARD_USDHC_CD_GPIO_BASE))
Definition at line 135 of file board.h.
BOARD_USDHC_CD_PORT_IRQ
#define BOARD_USDHC_CD_PORT_IRQ GPIO2_Combined_16_31_IRQn
Definition at line 130 of file board.h.
BOARD_USDHC_CD_PORT_IRQ_HANDLER
#define BOARD_USDHC_CD_PORT_IRQ_HANDLER GPIO2_Combined_16_31_IRQHandler
Definition at line 131 of file board.h.
BOARD_USDHC_CD_STATUS
#define BOARD_USDHC_CD_STATUS () (GPIO_PinRead(BOARD_USDHC_CD_GPIO_BASE, BOARD_USDHC_CD_GPIO_PIN))
Definition at line 133 of file board.h.
BOARD_USDHC_MMCCARD_POWER_CONTROL
#define BOARD_USDHC_MMCCARD_POWER_CONTROL (state)
Definition at line 155 of file board.h.
BOARD_USDHC_MMCCARD_POWER_CONTROL_INIT
#define BOARD_USDHC_MMCCARD_POWER_CONTROL_INIT ()
Value:
{                                                                                       \
        gpio_pin_config_t sw_config = {                                                     \
            kGPIO_DigitalOutput,                                                            \
            0,                                                                              \
            kGPIO_NoIntmode,                                                                \
        };                                                                                  \
        GPIO_PinInit(BOARD_SD_POWER_RESET_GPIO, BOARD_SD_POWER_RESET_GPIO_PIN, &sw_config); \
        GPIO_PinWrite(BOARD_SD_POWER_RESET_GPIO, BOARD_SD_POWER_RESET_GPIO_PIN, true);      \
    }
Definition at line 157 of file board.h.
BOARD_USDHC_SDCARD_POWER_CONTROL
#define BOARD_USDHC_SDCARD_POWER_CONTROL (state) (GPIO_PinWrite(BOARD_SD_POWER_RESET_GPIO, BOARD_SD_POWER_RESET_GPIO_PIN, state == true ? false : true))
Definition at line 178 of file board.h.
BOARD_USDHC_SDCARD_POWER_CONTROL_INIT
#define BOARD_USDHC_SDCARD_POWER_CONTROL_INIT ()
Value:
{                                                                                       \
        gpio_pin_config_t sw_config = {                                                     \
            kGPIO_DigitalOutput,                                                            \
            0,                                                                              \
            kGPIO_NoIntmode,                                                                \
        };                                                                                  \
        GPIO_PinInit(BOARD_SD_POWER_RESET_GPIO, BOARD_SD_POWER_RESET_GPIO_PIN, &sw_config); \
    }
Definition at line 168 of file board.h.
BOARD_USER_BUTTON_GPIO
#define BOARD_USER_BUTTON_GPIO GPIO13
Define the port interrupt number for the board switches.
Definition at line 92 of file board.h.
BOARD_USER_BUTTON_GPIO_PIN
#define BOARD_USER_BUTTON_GPIO_PIN (0U)
Definition at line 95 of file board.h.
BOARD_USER_BUTTON_IRQ
#define BOARD_USER_BUTTON_IRQ GPIO13_Combined_0_31_IRQn
Definition at line 97 of file board.h.
BOARD_USER_BUTTON_IRQ_HANDLER
#define BOARD_USER_BUTTON_IRQ_HANDLER GPIO13_Combined_0_31_IRQHandler
Definition at line 98 of file board.h.
BOARD_USER_BUTTON_NAME
#define BOARD_USER_BUTTON_NAME "SW7"
Definition at line 99 of file board.h.
BOARD_USER_LED_GPIO
#define BOARD_USER_LED_GPIO GPIO9
Definition at line 69 of file board.h.
BOARD_USER_LED_GPIO_PIN
#define BOARD_USER_LED_GPIO_PIN (3U)
Definition at line 72 of file board.h.
BOARD_WIFI_SD_DETECT_TYPE
#define BOARD_WIFI_SD_DETECT_TYPE kSDMMCHOST_DetectCardByHostDATA3
Definition at line 279 of file board.h.
DEBUG_CONSOLE_UART_INDEX
#define DEBUG_CONSOLE_UART_INDEX 1
Definition at line 22 of file board.h.
LOGIC_LED_OFF
#define LOGIC_LED_OFF (1U)
Definition at line 67 of file board.h.
LOGIC_LED_ON
#define LOGIC_LED_ON (0U)
The USER_LED used for board.
Definition at line 66 of file board.h.
MU_IRQ_PRIORITY
#define MU_IRQ_PRIORITY (2)
Definition at line 63 of file board.h.
USER_LED_INIT
#define USER_LED_INIT (output)
Value:
GPIO_PinWrite(BOARD_USER_LED_GPIO, BOARD_USER_LED_GPIO_PIN, output); \
    BOARD_USER_LED_GPIO->GDIR |= (1U << BOARD_USER_LED_GPIO_PIN)
Enable target USER_LED
Definition at line 75 of file board.h.
USER_LED_OFF
#define USER_LED_OFF () GPIO_PortClear(BOARD_USER_LED_GPIO, 1U << BOARD_USER_LED_GPIO_PIN)
Turn off target USER_LED
Definition at line 80 of file board.h.
USER_LED_ON
#define USER_LED_ON () GPIO_PortSet(BOARD_USER_LED_GPIO, 1U << BOARD_USER_LED_GPIO_PIN)
Turn on target USER_LED
Definition at line 83 of file board.h.
USER_LED_TOGGLE
#define USER_LED_TOGGLE ()
Value:
GPIO_PinWrite(BOARD_USER_LED_GPIO, BOARD_USER_LED_GPIO_PIN, \
                  0x1 ^ GPIO_PinRead(BOARD_USER_LED_GPIO, BOARD_USER_LED_GPIO_PIN))
Toggle target USER_LED
Definition at line 84 of file board.h.
Function Documentation
BOARD_ConfigMPU()
void BOARD_ConfigMPU (void)
Definition at line 52 of file board.c.
References BOARD_ACCEL_I2C_BASEADDR, BOARD_ACCEL_I2C_CLOCK_FREQ, BOARD_CODEC_I2C_BASEADDR, BOARD_CODEC_I2C_CLOCK_FREQ, and data.
BOARD_DebugConsoleSrcFreq()
uint32_t BOARD_DebugConsoleSrcFreq (void)
Definition at line 25 of file board.c.
Referenced by BOARD_InitDebugConsole(), and LPUART1_GetFreq().
BOARD_InitDebugConsole()
void BOARD_InitDebugConsole (void)
Definition at line 15 of file board.c.
References BOARD_ACCEL_I2C_BASEADDR, BOARD_ACCEL_I2C_CLOCK_FREQ, BOARD_CAMERA_I2C_BASEADDR, BOARD_CAMERA_I2C_CLOCK_DIVIDER, BOARD_CAMERA_I2C_CLOCK_ROOT, BOARD_CAMERA_I2C_CLOCK_SOURCE, BOARD_CODEC_I2C_BASEADDR, BOARD_CODEC_I2C_CLOCK_FREQ, BOARD_DEBUG_UART_BASEADDR, BOARD_DEBUG_UART_BAUDRATE, BOARD_DEBUG_UART_CLK_ATTACH, BOARD_DEBUG_UART_CLK_FREQ, BOARD_DEBUG_UART_CLKSRC, BOARD_DEBUG_UART_FRG_CLK, BOARD_DEBUG_UART_INSTANCE, BOARD_DEBUG_UART_RST, BOARD_DEBUG_UART_TYPE, BOARD_DebugConsoleSrcFreq(), BOARD_MIPI_PANEL_TOUCH_I2C_BASEADDR, BOARD_MIPI_PANEL_TOUCH_I2C_CLOCK_DIVIDER, BOARD_MIPI_PANEL_TOUCH_I2C_CLOCK_ROOT, BOARD_MIPI_PANEL_TOUCH_I2C_CLOCK_SOURCE, BOARD_PMIC_I2C_BASEADDR, BOARD_PMIC_I2C_CLOCK_FREQ, data, I2C_Type, and status.
Referenced by main().
BOARD_MMC_Pin_Config()
void BOARD_MMC_Pin_Config (uint32_t speed, uint32_t strength)
Definition at line 84 of file board.c.
BOARD_SD_Pin_Config()
void BOARD_SD_Pin_Config (uint32_t speed, uint32_t strength)
Definition at line 51 of file board.c.