ISSDK: driverexamples/fxas21002/fxas21002_fifo.c File Reference
fxas21002_fifo.c File Reference
#include "pin_mux.h"
#include "clock_config.h"
#include "board.h"
#include "fsl_debug_console.h"
#include "Driver_I2C.h"
#include "issdk_hal.h"
#include "fxas21002_drv.h"
Macros
#define FIFO_SIZE 4
The watermark value configured for FXAS21002 FIFO Buffer.
Functions
int main (void)
Main function.
Variables
const registerwritelist_t fxas21002_Config_with_Fifo []
const registerreadlist_t fxas21002_Fifo_Event [] = {{.readFrom = FXAS21002_F_EVENT, .numBytes = 1}, __END_READ_DATA__}
const registerreadlist_t fxas21002_Output_Values []
Macro Definition Documentation
FIFO_SIZE
#define FIFO_SIZE 4
The watermark value configured for FXAS21002 FIFO Buffer.
Definition at line 35 of file fxas21002_fifo.c.
Referenced by main().
Function Documentation
main()
int main (void)
Main function.
Initialize the MCU hardware.
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize the FXAS21002 sensor driver.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the FXAS21002 sensor driver.
Wait for the FIFO watermark event.
Read the raw sensor data from the FXAS21002.
Convert the raw sensor data to signed 16-bit container for display to the debug port.
Definition at line 63 of file fxas21002_fifo.c.
References ASK_USER_TO_RESUME, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), data, FIFO_SIZE, FXAS21002_F_EVENT_F_EVENT_MASK, FXAS21002_GYRO_DATA_SIZE, FXAS21002_I2C_ADDR, FXAS21002_I2C_Configure(), FXAS21002_I2C_Initialize(), FXAS21002_I2C_ReadData(), FXAS21002_WHO_AM_I_WHOAMI_PROD_VALUE, fxas21002_gyrodata_t::gyro, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, I2Cdrv, int32_t(), rawData, SENSOR_ERROR_NONE, and status.
Variable Documentation
fxas21002_Config_with_Fifo
const registerwritelist_t fxas21002_Config_with_Fifo[]
Initial value:
= {
    {FXAS21002_CTRL_REG1, FXAS21002_CTRL_REG1_DR_12_5HZ, FXAS21002_CTRL_REG1_DR_MASK},
    {FXAS21002_F_SETUP, FXAS21002_F_SETUP_F_MODE_STOP_MODE | (FIFO_SIZE << FXAS21002_F_SETUP_F_WMRK_SHIFT),
     FXAS21002_F_SETUP_F_MODE_MASK | FXAS21002_F_SETUP_F_WMRK_MASK},
    {FXAS21002_CTRL_REG3, FXAS21002_CTRL_REG3_WRAPTOONE_ROLL_DATA, FXAS21002_CTRL_REG3_WRAPTOONE_MASK},
    __END_WRITE_DATA__}
Prepare the register write list to configure FXAS21002 in FIFO mode.
Definition at line 41 of file fxas21002_fifo.c.
fxas21002_Fifo_Event
const registerreadlist_t fxas21002_Fifo_Event[] = {{.readFrom = FXAS21002_F_EVENT, .numBytes = 1}, __END_READ_DATA__}
Prepare the register read list to read FXAS21002 FIFO event.
Definition at line 51 of file fxas21002_fifo.c.
fxas21002_Output_Values
const registerreadlist_t fxas21002_Output_Values[]
Initial value:
= {
    {.readFrom = FXAS21002_OUT_X_MSB, .numBytes = FXAS21002_GYRO_DATA_SIZE * FIFO_SIZE}, __END_READ_DATA__}
Prepare the register read list to read the raw gyro data from the FXAS21002.
Definition at line 54 of file fxas21002_fifo.c.