ISSDK: drivers/ads/qn/auto_detection_service.h File Reference
auto_detection_service.h File Reference
#include <stdio.h>
Data Structures
struct mcuDEVID_t
This defines a record type to store the expected field values of the LPC device ID.
struct sensorAccess_t
This defines a record type to store the communication channel info and WHO_AM_I address/value for various Sensor Shields.
struct ADSFlashRecord_t
This defines a record type to store ADS results string in Flash memory.
Macros
#define ADS_NO_WHO_AM_I (0xFFFF)
#define ADS_MAX_STRING_LENGTH (64)
#define ADS_FLASH_STRING_LENGTH (128)
#define ADS_NO_SHIELD_DETECTED (0xFFFFFFFF)
#define ADS_COOKIE_VALUE (0xDEADBEEF)
Typedefs
typedef enum ADS_Status ADS_Status_t
This defines the return status.
typedef enum ADS_Channel ADS_Channel_t
This defines the allowed communications channels.
typedef enum ADS_Sensor ADS_Sensor_t
This defines the allowed communications channels.
Enumerations
enum ADS_Status {
ADS_OK, ADS_FAIL, ADS_NULL, ADS_OK,
ADS_FAIL, ADS_NULL, ADS_OK, ADS_FAIL,
ADS_NULL
}
This defines the return status.
enum ADS_Channel {
ADS_I2C_INT, ADS_I2C_EXT, ADS_SPI_DEV, ADS_I2C_INT,
ADS_I2C_EXT, ADS_SPI_DEV, ADS_I2C_INT, ADS_I2C_EXT,
ADS_SPI_DEV
}
This defines the allowed communications channels.
enum ADS_Sensor {
FXAS21002, FXLC95000, FXLS8471, FXLS8962,
FXOS8700, FXPQ3115, MAG3110, MMA845x,
MMA865x, MMA8491, MMA9553, MPL3115,
DIFF_P, FXAS21002, FXLC95000, FXLS8471,
FXLS8962, FXOS8700, FXPQ3115, MAG3110,
MMA845x, MMA865x, MMA8491, MMA9553,
MPL3115, DIFF_P, FXAS21002, FXLC95000,
FXLS8471, FXLS8962, FXOS8700, FXPQ3115,
MAG3110, MMA845x, MMA865x, MMA8491,
MMA9553, MPL3115, DIFF_P
}
This defines the allowed communications channels.
enum ADS_SupportedBoards_t {
ADS_LPC_54113J128, ADS_LPC_54113J256, ADS_LPC_54114J256, ADS_NO_BOARD_DETECTED,
ADS_FRDM_KW41Z, ADS_FRDM_KE15Z, ADS_FRDM_KL25Z, ADS_FRDM_KL27Z,
ADS_FRDM_K22F, ADS_FRDM_K64F, ADS_RD_KL25_AGMP01, ADS_NO_BOARD_DETECTED,
ADS_QN_9020, ADS_QN_9080, ADS_NO_BOARD_DETECTED
}
This enumeration defines the FRDM boards that ADS can detect.
enum ADS_FlashStatus_t {
ADS_NO_FLASH_RECORD, ADS_FLASH_RECORD_CHANGE, ADS_FLASH_RECORD_NO_CHANGE, ADS_NO_FLASH_RECORD,
ADS_FLASH_RECORD_CHANGE, ADS_FLASH_RECORD_NO_CHANGE, ADS_NO_FLASH_RECORD, ADS_FLASH_RECORD_CHANGE,
ADS_FLASH_RECORD_NO_CHANGE
}
This enumeration defines the ADS Flash storage status.
Functions
void BOARD_RunADS (const char *appName, char *boardString, char *shieldString, size_t bufferLength)
The function to register Application Name and initialte ADS.
Macro Definition Documentation
ADS_COOKIE_VALUE
#define ADS_COOKIE_VALUE (0xDEADBEEF)
Definition at line 27 of file auto_detection_service.h.
ADS_FLASH_STRING_LENGTH
#define ADS_FLASH_STRING_LENGTH (128)
Definition at line 25 of file auto_detection_service.h.
ADS_MAX_STRING_LENGTH
#define ADS_MAX_STRING_LENGTH (64)
Definition at line 24 of file auto_detection_service.h.
ADS_NO_SHIELD_DETECTED
#define ADS_NO_SHIELD_DETECTED (0xFFFFFFFF)
Definition at line 26 of file auto_detection_service.h.
ADS_NO_WHO_AM_I
#define ADS_NO_WHO_AM_I (0xFFFF)
Definition at line 23 of file auto_detection_service.h.
Typedef Documentation
ADS_Channel_t
typedef enum ADS_Channel ADS_Channel_t
This defines the allowed communications channels.
ADS_Sensor_t
typedef enum ADS_Sensor ADS_Sensor_t
This defines the allowed communications channels.
ADS_Status_t
typedef enum ADS_Status ADS_Status_t
This defines the return status.
Enumeration Type Documentation
ADS_Channel
enum ADS_Channel
This defines the allowed communications channels.
Enumerator
ADS_I2C_INT
ADS_I2C_EXT
ADS_SPI_DEV
ADS_I2C_INT
ADS_I2C_EXT
ADS_SPI_DEV
ADS_I2C_INT
ADS_I2C_EXT
ADS_SPI_DEV
Definition at line 42 of file auto_detection_service.h.
ADS_FlashStatus_t
enum ADS_FlashStatus_t
This enumeration defines the ADS Flash storage status.
Enumerator
ADS_NO_FLASH_RECORD
ADS_FLASH_RECORD_CHANGE
ADS_FLASH_RECORD_NO_CHANGE
ADS_NO_FLASH_RECORD
ADS_FLASH_RECORD_CHANGE
ADS_FLASH_RECORD_NO_CHANGE
ADS_NO_FLASH_RECORD
ADS_FLASH_RECORD_CHANGE
ADS_FLASH_RECORD_NO_CHANGE
Definition at line 82 of file auto_detection_service.h.
ADS_Sensor
enum ADS_Sensor
This defines the allowed communications channels.
Enumerator
FXAS21002
FXLC95000
FXLS8471
FXLS8962
FXOS8700
FXPQ3115
MAG3110
MMA845x
MMA865x
MMA8491
MMA9553
MPL3115
DIFF_P
FXAS21002
FXLC95000
FXLS8471
FXLS8962
FXOS8700
FXPQ3115
MAG3110
MMA845x
MMA865x
MMA8491
MMA9553
MPL3115
DIFF_P
FXAS21002
FXLC95000
FXLS8471
FXLS8962
FXOS8700
FXPQ3115
MAG3110
MMA845x
MMA865x
MMA8491
MMA9553
MPL3115
DIFF_P
Definition at line 52 of file auto_detection_service.h.
ADS_Status
enum ADS_Status
This defines the return status.
Enumerator
ADS_OK
ADS_FAIL
ADS_NULL
ADS_OK
ADS_FAIL
ADS_NULL
ADS_OK
ADS_FAIL
ADS_NULL
Definition at line 32 of file auto_detection_service.h.
ADS_SupportedBoards_t
enum ADS_SupportedBoards_t
This enumeration defines the FRDM boards that ADS can detect.
Enumerator
ADS_LPC_54113J128
ADS_LPC_54113J256
ADS_LPC_54114J256
ADS_NO_BOARD_DETECTED
ADS_FRDM_KW41Z
ADS_FRDM_KE15Z
ADS_FRDM_KL25Z
ADS_FRDM_KL27Z
ADS_FRDM_K22F
ADS_FRDM_K64F
ADS_RD_KL25_AGMP01
ADS_NO_BOARD_DETECTED
ADS_QN_9020
ADS_QN_9080
ADS_NO_BOARD_DETECTED
Definition at line 72 of file auto_detection_service.h.
Function Documentation
BOARD_RunADS()
void BOARD_RunADS (const char * appName, char * boardString, char * shieldString, size_t bufferLength)
The function to register Application Name and initialte ADS.
The API will read the Application Name from the user and return the result string with the ADS detection results. It will also update the FLASH with the new results.
Parameters
[in] pAppName - pointer to a buffer where the application name is placed.
Definition at line 917 of file auto_detection_service.c.
References ADS_DetectFRDM(), ADS_DetectLPC(), ADS_DetectQN(), ADS_DetectShield(), ADS_FAIL, ADS_FLASH_RECORD_NO_CHANGE, ADS_FLASH_STRING_LENGTH, ADS_FlashCompare(), ADS_FlashUpdate(), ADS_OK, int32_t(), and status.
Referenced by main().