ISSDK: driverexamples/mpl3115/mpl3115_fifo.c File Reference
mpl3115_fifo.c File Reference
#include "pin_mux.h"
#include "clock_config.h"
#include "board.h"
#include "fsl_debug_console.h"
#include "Driver_I2C.h"
#include "issdk_hal.h"
#include "mpl3115_drv.h"
Macros
#define FIFO_WMRK_SIZE (8) /* Buffer 8 Samples. */
#define MPL3115_DATA_SIZE (5) /* 3 byte Pressure/Altitude and 2 byte Temperature. */
#define MPL3115_SAMPLING_EXPONENT (0) /* 1 second. */
Functions
int main (void)
Main function.
Variables
const registerwritelist_t cMpl3115ConfigFIFO []
Register settings for FIFO (buffered) mode @ default 1 sample per second.
const registerreadlist_t cMpl3115Status [] = {{.readFrom = MPL3115_STATUS, .numBytes = 1}, __END_READ_DATA__}
Address of Status Register.
const registerreadlist_t cMpl3115OutputFIFO []
Address and size of Pressure+Temperature Data in FIFO Mode.
Macro Definition Documentation
FIFO_WMRK_SIZE
#define FIFO_WMRK_SIZE (8) /* Buffer 8 Samples. */
Definition at line 35 of file mpl3115_fifo.c.
Referenced by main().
MPL3115_DATA_SIZE
#define MPL3115_DATA_SIZE (5) /* 3 byte Pressure/Altitude and 2 byte Temperature. */
Definition at line 36 of file mpl3115_fifo.c.
Referenced by main().
MPL3115_SAMPLING_EXPONENT
#define MPL3115_SAMPLING_EXPONENT (0) /* 1 second. */
In MPL3115 the Auto Acquisition Time Step (ODR) can be set only in powers of 2 (i.e. 2^x, where x is the SAMPLING_EXPONENT). This gives a range of 1 second to 2^15 seconds (9 hours).
Definition at line 40 of file mpl3115_fifo.c.
Function Documentation
main()
int main (void)
Main function.
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize MPL3115 sensor driver.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the MPL3115 sensor.
Wait for data ready from the MPL3115.
Read new raw sensor data from the MPL3115.
Process all samples and convert the raw sensor data.
Definition at line 72 of file mpl3115_fifo.c.
References ASK_USER_TO_RESUME, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), data, FIFO_WMRK_SIZE, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, I2Cdrv, int32_t(), MPL3115_DATA_SIZE, MPL3115_F_STATUS_F_WMKF_FLAG_MASK, MPL3115_I2C_ADDR, MPL3115_I2C_Configure(), MPL3115_I2C_Initialize(), MPL3115_I2C_ReadData(), MPL3115_I2C_SetIdleTask(), MPL3115_PRESSURE_CONV_FACTOR, MPL3115_TEMPERATURE_CONV_FACTOR, MPL3115_WHOAMI_VALUE, mpl3115_pressuredata_t::pressure, rawData, SENSOR_ERROR_NONE, SMC, SMC_SetPowerModeVlpr(), status, and mpl3115_pressuredata_t::temperature.
Variable Documentation
cMpl3115ConfigFIFO
const registerwritelist_t cMpl3115ConfigFIFO[]
Initial value:
= {
    {MPL3115_F_SETUP, MPL3115_F_SETUP_F_MODE_STOP_MODE | FIFO_WMRK_SIZE,
     MPL3115_F_SETUP_F_MODE_MASK | MPL3115_F_SETUP_F_WMRK_MASK},
    {MPL3115_PT_DATA_CFG,
     MPL3115_PT_DATA_CFG_TDEFE_ENABLED | MPL3115_PT_DATA_CFG_PDEFE_ENABLED | MPL3115_PT_DATA_CFG_DREM_ENABLED,
     MPL3115_PT_DATA_CFG_TDEFE_MASK | MPL3115_PT_DATA_CFG_PDEFE_MASK | MPL3115_PT_DATA_CFG_DREM_MASK},
    {MPL3115_CTRL_REG1, MPL3115_CTRL_REG1_OS_OSR_128, MPL3115_CTRL_REG1_OS_MASK},
    {MPL3115_CTRL_REG2, MPL3115_SAMPLING_EXPONENT, MPL3115_CTRL_REG2_ST_MASK},
    __END_WRITE_DATA__}
Register settings for FIFO (buffered) mode @ default 1 sample per second.
Definition at line 46 of file mpl3115_fifo.c.
cMpl3115OutputFIFO
const registerreadlist_t cMpl3115OutputFIFO[]
Initial value:
= {
    {.readFrom = MPL3115_OUT_P_MSB, .numBytes = MPL3115_DATA_SIZE * FIFO_WMRK_SIZE}, __END_READ_DATA__}
Address and size of Pressure+Temperature Data in FIFO Mode.
Definition at line 63 of file mpl3115_fifo.c.
cMpl3115Status
const registerreadlist_t cMpl3115Status[] = {{.readFrom = MPL3115_STATUS, .numBytes = 1}, __END_READ_DATA__}
Address of Status Register.
Definition at line 60 of file mpl3115_fifo.c.