ISSDK: drivers/gpio/kinetis/gpio_driver_irq.c File Reference
gpio_driver_irq.c File Reference
#include "fsl_gpio.h"
#include "gpio_driver.h"
Functions
void ksdk_gpio_handle_interrupt (GPIO_Type *base, port_number_t portNumber)
void PORTA_IRQHandler (void)
void PORTB_IRQHandler (void)
void PORTC_IRQHandler (void)
void PORTD_IRQHandler (void)
void PORTE_IRQHandler (void)
Function Documentation
ksdk_gpio_handle_interrupt()
void ksdk_gpio_handle_interrupt (GPIO_Type * base, port_number_t portNumber)
Definition at line 153 of file gpio_driver.c.
Referenced by GPIOA_IRQHandler(), GPIOB_IRQHandler(), PORTA_IRQHandler(), PORTB_IRQHandler(), PORTC_IRQHandler(), PORTD_IRQHandler(), and PORTE_IRQHandler().
PORTA_IRQHandler()
void PORTA_IRQHandler (void)
Definition at line 22 of file gpio_driver_irq.c.
References ksdk_gpio_handle_interrupt(), and PORTA_NUM.
PORTB_IRQHandler()
void PORTB_IRQHandler (void)
Definition at line 26 of file gpio_driver_irq.c.
References ksdk_gpio_handle_interrupt(), and PORTB_NUM.
PORTC_IRQHandler()
void PORTC_IRQHandler (void)
Definition at line 30 of file gpio_driver_irq.c.
References ksdk_gpio_handle_interrupt(), and PORTC_NUM.
PORTD_IRQHandler()
void PORTD_IRQHandler (void)
Definition at line 34 of file gpio_driver_irq.c.
References ksdk_gpio_handle_interrupt(), and PORTD_NUM.
PORTE_IRQHandler()
void PORTE_IRQHandler (void)
Definition at line 38 of file gpio_driver_irq.c.
References ksdk_gpio_handle_interrupt(), and PORTE_NUM.