ISSDK: drivers/gpio/i.mx/i.mxrt600/gpio_driver_irq.c File Reference
gpio_driver_irq.c File Reference
#include "fsl_gpio.h"
#include "gpio_driver.h"
Functions
void imxsdk_gpio_handle_interrupt (GPIO_Type *base, port_number_t gpioPortNumber)
void GPIO1_Combined_0_15_IRQHandler (void)
void GPIO1_Combined_16_31_IRQHandler (void)
void GPIO2_Combined_0_15_IRQHandler (void)
void GPIO2_Combined_16_31_IRQHandler (void)
void GPIO3_Combined_0_15_IRQHandler (void)
void GPIO3_Combined_16_31_IRQHandler (void)
void GPIO4_Combined_0_15_IRQHandler (void)
void GPIO4_Combined_16_31_IRQHandler (void)
void GPIO5_Combined_0_15_IRQHandler (void)
void GPIO5_Combined_16_31_IRQHandler (void)
Function Documentation
GPIO1_Combined_0_15_IRQHandler()
void GPIO1_Combined_0_15_IRQHandler (void)
Definition at line 23 of file gpio_driver_irq.c.
References GPIO1_NUM, and imxsdk_gpio_handle_interrupt().
GPIO1_Combined_16_31_IRQHandler()
void GPIO1_Combined_16_31_IRQHandler (void)
Definition at line 28 of file gpio_driver_irq.c.
References GPIO1_NUM, and imxsdk_gpio_handle_interrupt().
GPIO2_Combined_0_15_IRQHandler()
void GPIO2_Combined_0_15_IRQHandler (void)
Definition at line 33 of file gpio_driver_irq.c.
References GPIO2_NUM, and imxsdk_gpio_handle_interrupt().
GPIO2_Combined_16_31_IRQHandler()
void GPIO2_Combined_16_31_IRQHandler (void)
Definition at line 38 of file gpio_driver_irq.c.
References GPIO2_NUM, and imxsdk_gpio_handle_interrupt().
GPIO3_Combined_0_15_IRQHandler()
void GPIO3_Combined_0_15_IRQHandler (void)
Definition at line 43 of file gpio_driver_irq.c.
References GPIO3_NUM, and imxsdk_gpio_handle_interrupt().
GPIO3_Combined_16_31_IRQHandler()
void GPIO3_Combined_16_31_IRQHandler (void)
Definition at line 48 of file gpio_driver_irq.c.
References GPIO3_NUM, and imxsdk_gpio_handle_interrupt().
GPIO4_Combined_0_15_IRQHandler()
void GPIO4_Combined_0_15_IRQHandler (void)
Definition at line 54 of file gpio_driver_irq.c.
References GPIO4_NUM, and imxsdk_gpio_handle_interrupt().
GPIO4_Combined_16_31_IRQHandler()
void GPIO4_Combined_16_31_IRQHandler (void)
Definition at line 59 of file gpio_driver_irq.c.
References GPIO4_NUM, and imxsdk_gpio_handle_interrupt().
GPIO5_Combined_0_15_IRQHandler()
void GPIO5_Combined_0_15_IRQHandler (void)
Definition at line 65 of file gpio_driver_irq.c.
References GPIO5_NUM, and imxsdk_gpio_handle_interrupt().
GPIO5_Combined_16_31_IRQHandler()
void GPIO5_Combined_16_31_IRQHandler (void)
Definition at line 70 of file gpio_driver_irq.c.
References GPIO5_NUM, and imxsdk_gpio_handle_interrupt().
imxsdk_gpio_handle_interrupt()
void imxsdk_gpio_handle_interrupt (GPIO_Type * base, port_number_t gpioPortNumber)
Definition at line 156 of file gpio_driver.c.
References GPIO_NUMBER_OF_PIN, and gpioIsrObj::isrHandle.