ISSDK: drivers/gpio/i.mx/i.mxrt1180/gpio_driver_irq.c File Reference
gpio_driver_irq.c File Reference
#include "fsl_rgpio.h"
#include "gpio_driver.h"
Functions
void imxsdk_gpio_handle_interrupt (RGPIO_Type *base, port_number_t gpioPortNumber)
void GPIO1_0_IRQHandler (void)
void GPIO1_1_IRQHandler (void)
void GPIO2_0_IRQHandler (void)
void GPIO2_1_IRQHandler (void)
void GPIO3_0_IRQHandler (void)
void GPIO3_1_IRQHandler (void)
void GPIO4_0_IRQHandler (void)
void GPIO4_1_IRQHandler (void)
void GPIO5_0_IRQHandler (void)
void GPIO5_1_IRQHandler (void)
Function Documentation
GPIO1_0_IRQHandler()
void GPIO1_0_IRQHandler (void)
Definition at line 22 of file gpio_driver_irq.c.
References GPIO1_NUM, and imxsdk_gpio_handle_interrupt().
GPIO1_1_IRQHandler()
void GPIO1_1_IRQHandler (void)
Definition at line 27 of file gpio_driver_irq.c.
References GPIO1_NUM, and imxsdk_gpio_handle_interrupt().
GPIO2_0_IRQHandler()
void GPIO2_0_IRQHandler (void)
Definition at line 32 of file gpio_driver_irq.c.
References GPIO2_NUM, and imxsdk_gpio_handle_interrupt().
GPIO2_1_IRQHandler()
void GPIO2_1_IRQHandler (void)
Definition at line 37 of file gpio_driver_irq.c.
References GPIO2_NUM, and imxsdk_gpio_handle_interrupt().
GPIO3_0_IRQHandler()
void GPIO3_0_IRQHandler (void)
Definition at line 42 of file gpio_driver_irq.c.
References GPIO3_NUM, and imxsdk_gpio_handle_interrupt().
GPIO3_1_IRQHandler()
void GPIO3_1_IRQHandler (void)
Definition at line 47 of file gpio_driver_irq.c.
References GPIO3_NUM, and imxsdk_gpio_handle_interrupt().
GPIO4_0_IRQHandler()
void GPIO4_0_IRQHandler (void)
Definition at line 53 of file gpio_driver_irq.c.
References GPIO4_NUM, and imxsdk_gpio_handle_interrupt().
GPIO4_1_IRQHandler()
void GPIO4_1_IRQHandler (void)
Definition at line 58 of file gpio_driver_irq.c.
References GPIO4_NUM, and imxsdk_gpio_handle_interrupt().
GPIO5_0_IRQHandler()
void GPIO5_0_IRQHandler (void)
Definition at line 64 of file gpio_driver_irq.c.
References GPIO5_NUM, and imxsdk_gpio_handle_interrupt().
GPIO5_1_IRQHandler()
void GPIO5_1_IRQHandler (void)
Definition at line 69 of file gpio_driver_irq.c.
References GPIO5_NUM, and imxsdk_gpio_handle_interrupt().
imxsdk_gpio_handle_interrupt()
void imxsdk_gpio_handle_interrupt (RGPIO_Type * base, port_number_t gpioPortNumber)
Definition at line 157 of file gpio_driver.c.
References GPIO_NUMBER_OF_PIN, and gpioIsrObj::isrHandle.