ISSDK: drivers/gpio/qn/gpio_driver.c File Reference
gpio_driver.c File Reference
#include "gpio_driver.h"
Macros
#define GPIO_DRV_VERSION ARM_DRIVER_VERSION_MAJOR_MINOR(2, 0) /* driver version */
#define GPIO_NUMBER_OF_PIN 0x20
Functions
GENERIC_DRIVER_VERSION ksdk_gpio_get_version (void)
void ksdk_gpio_set_interrupt (GPIO_Type *base, uint32_t mask, uint8_t interruptMode)
void ksdk_gpio_pin_init (pinID_t aPinId, gpio_direction_t dir, void *apPinConfig, gpio_isr_handler_t aIsrHandler, void *apUserData)
void ksdk_gpio_set_pin (pinID_t aPinId)
void ksdk_gpio_clr_pin (pinID_t aPinId)
void ksdk_gpio_toggle_pin (pinID_t aPinId)
void ksdk_gpio_write_pin (pinID_t aPinId, uint8_t aValue)
uint32_t ksdk_gpio_read_pin (pinID_t aPinId)
void ksdk_gpio_handle_interrupt (GPIO_Type *apBase, port_number_t aPortNumber)
Variables
GENERIC_DRIVER_GPIO Driver_GPIO_KSDK
Macro Definition Documentation
GPIO_DRV_VERSION
#define GPIO_DRV_VERSION ARM_DRIVER_VERSION_MAJOR_MINOR(2, 0) /* driver version */
Definition at line 19 of file gpio_driver.c.
GPIO_NUMBER_OF_PIN
#define GPIO_NUMBER_OF_PIN 0x20
Definition at line 21 of file gpio_driver.c.
Referenced by ksdk_gpio_handle_interrupt().
Function Documentation
ksdk_gpio_clr_pin()
void ksdk_gpio_clr_pin (pinID_t aPinId)
Definition at line 133 of file gpio_driver.c.
References gpioHandleKSDK::base, and gpioHandleKSDK::mask.
ksdk_gpio_get_version()
GENERIC_DRIVER_VERSION ksdk_gpio_get_version (void)
Definition at line 43 of file gpio_driver.c.
ksdk_gpio_handle_interrupt()
void ksdk_gpio_handle_interrupt (GPIO_Type * apBase, port_number_t aPortNumber)
Definition at line 181 of file gpio_driver.c.
References GPIO_NUMBER_OF_PIN, and gpioIsrObj::isrHandle.
Referenced by GPIOA_IRQHandler(), GPIOB_IRQHandler(), PORTA_IRQHandler(), PORTAE_IRQHandler(), PORTB_IRQHandler(), PORTB_PORTC_IRQHandler(), PORTB_PORTC_PORTD_PORTE_IRQHandler(), PORTBCD_IRQHandler(), PORTC_IRQHandler(), PORTD_IRQHandler(), and PORTE_IRQHandler().
ksdk_gpio_pin_init()
void ksdk_gpio_pin_init (pinID_t aPinId, gpio_direction_t dir, void * apPinConfig, gpio_isr_handler_t aIsrHandler, void * apUserData)
Definition at line 83 of file gpio_driver.c.
ksdk_gpio_read_pin()
uint32_t ksdk_gpio_read_pin (pinID_t aPinId)
Definition at line 169 of file gpio_driver.c.
References gpioHandleKSDK::base, and gpioHandleKSDK::pinNumber.
ksdk_gpio_set_interrupt()
void ksdk_gpio_set_interrupt (GPIO_Type * base, uint32_t mask, uint8_t interruptMode)
Definition at line 54 of file gpio_driver.c.
References kGPIO_InterruptFallingEdge, kGPIO_InterruptLogic_0, kGPIO_InterruptLogic_1, and kGPIO_InterruptRisingEdge.
ksdk_gpio_set_pin()
void ksdk_gpio_set_pin (pinID_t aPinId)
Definition at line 121 of file gpio_driver.c.
References gpioHandleKSDK::base, and gpioHandleKSDK::mask.
ksdk_gpio_toggle_pin()
void ksdk_gpio_toggle_pin (pinID_t aPinId)
Definition at line 145 of file gpio_driver.c.
References gpioHandleKSDK::base, and gpioHandleKSDK::mask.
ksdk_gpio_write_pin()
void ksdk_gpio_write_pin (pinID_t aPinId, uint8_t aValue)
Definition at line 157 of file gpio_driver.c.
References gpioHandleKSDK::base, and gpioHandleKSDK::pinNumber.
Variable Documentation
Driver_GPIO_KSDK
GENERIC_DRIVER_GPIO Driver_GPIO_KSDK
Initial value:
= {
    ksdk_gpio_get_version, ksdk_gpio_pin_init,  ksdk_gpio_set_pin,  ksdk_gpio_clr_pin,
    ksdk_gpio_toggle_pin,  ksdk_gpio_write_pin, ksdk_gpio_read_pin,
}
Definition at line 202 of file gpio_driver.c.