ISSDK: drivers/gpio/i.mx/gpio_driver_irq.c File Reference
gpio_driver_irq.c File Reference
#include "fsl_gpio.h"
#include "gpio_driver.h"
Functions
void imxsdk_gpio_handle_interrupt (GPIO_Type *base, port_number_t gpioPortNumber)
void GPIO1_Combined_0_15_IRQHandler (void)
void GPIO1_Combined_16_31_IRQHandler (void)
void GPIO2_Combined_0_15_IRQHandler (void)
void GPIO2_Combined_16_31_IRQHandler (void)
void GPIO3_Combined_0_15_IRQHandler (void)
void GPIO3_Combined_16_31_IRQHandler (void)
void GPIO4_Combined_0_15_IRQHandler (void)
void GPIO4_Combined_16_31_IRQHandler (void)
void GPIO5_Combined_0_15_IRQHandler (void)
void GPIO5_Combined_16_31_IRQHandler (void)
Function Documentation
GPIO1_Combined_0_15_IRQHandler()
void GPIO1_Combined_0_15_IRQHandler (void)
Definition at line 22 of file gpio_driver_irq.c.
References GPIO1_NUM, and imxsdk_gpio_handle_interrupt().
GPIO1_Combined_16_31_IRQHandler()
void GPIO1_Combined_16_31_IRQHandler (void)
Definition at line 27 of file gpio_driver_irq.c.
References GPIO1_NUM, and imxsdk_gpio_handle_interrupt().
GPIO2_Combined_0_15_IRQHandler()
void GPIO2_Combined_0_15_IRQHandler (void)
Definition at line 32 of file gpio_driver_irq.c.
References GPIO2_NUM, and imxsdk_gpio_handle_interrupt().
GPIO2_Combined_16_31_IRQHandler()
void GPIO2_Combined_16_31_IRQHandler (void)
Definition at line 37 of file gpio_driver_irq.c.
References GPIO2_NUM, and imxsdk_gpio_handle_interrupt().
GPIO3_Combined_0_15_IRQHandler()
void GPIO3_Combined_0_15_IRQHandler (void)
Definition at line 42 of file gpio_driver_irq.c.
References GPIO3_NUM, and imxsdk_gpio_handle_interrupt().
GPIO3_Combined_16_31_IRQHandler()
void GPIO3_Combined_16_31_IRQHandler (void)
Definition at line 47 of file gpio_driver_irq.c.
References GPIO3_NUM, and imxsdk_gpio_handle_interrupt().
GPIO4_Combined_0_15_IRQHandler()
void GPIO4_Combined_0_15_IRQHandler (void)
Definition at line 53 of file gpio_driver_irq.c.
References GPIO4_NUM, and imxsdk_gpio_handle_interrupt().
GPIO4_Combined_16_31_IRQHandler()
void GPIO4_Combined_16_31_IRQHandler (void)
Definition at line 58 of file gpio_driver_irq.c.
References GPIO4_NUM, and imxsdk_gpio_handle_interrupt().
GPIO5_Combined_0_15_IRQHandler()
void GPIO5_Combined_0_15_IRQHandler (void)
Definition at line 64 of file gpio_driver_irq.c.
References GPIO5_NUM, and imxsdk_gpio_handle_interrupt().
GPIO5_Combined_16_31_IRQHandler()
void GPIO5_Combined_16_31_IRQHandler (void)
Definition at line 69 of file gpio_driver_irq.c.
References GPIO5_NUM, and imxsdk_gpio_handle_interrupt().
imxsdk_gpio_handle_interrupt()
void imxsdk_gpio_handle_interrupt (GPIO_Type * base, port_number_t gpioPortNumber)
Definition at line 156 of file gpio_driver.c.
Referenced by GPIO1_0_IRQHandler(), GPIO1_1_IRQHandler(), GPIO1_Combined_0_15_IRQHandler(), GPIO1_Combined_16_31_IRQHandler(), GPIO2_0_IRQHandler(), GPIO2_1_IRQHandler(), GPIO2_Combined_0_15_IRQHandler(), GPIO2_Combined_16_31_IRQHandler(), GPIO3_0_IRQHandler(), GPIO3_1_IRQHandler(), GPIO3_Combined_0_15_IRQHandler(), GPIO3_Combined_16_31_IRQHandler(), GPIO4_0_IRQHandler(), GPIO4_1_IRQHandler(), GPIO4_Combined_0_15_IRQHandler(), GPIO4_Combined_16_31_IRQHandler(), GPIO5_0_IRQHandler(), GPIO5_1_IRQHandler(), GPIO5_Combined_0_15_IRQHandler(), and GPIO5_Combined_16_31_IRQHandler().