ISSDK: drivers/gpio/qn/gpio_driver_irq.c File Reference
gpio_driver_irq.c File Reference
#include "fsl_gpio.h"
#include "gpio_driver.h"
Functions
void ksdk_gpio_handle_interrupt (GPIO_Type *base, port_number_t portNumber)
void GPIOA_IRQHandler (void)
void GPIOB_IRQHandler (void)
Function Documentation
GPIOA_IRQHandler()
void GPIOA_IRQHandler (void)
Definition at line 22 of file gpio_driver_irq.c.
References ksdk_gpio_handle_interrupt(), and PORTA_NUM.
GPIOB_IRQHandler()
void GPIOB_IRQHandler (void)
Definition at line 26 of file gpio_driver_irq.c.
References ksdk_gpio_handle_interrupt(), and PORTB_NUM.
ksdk_gpio_handle_interrupt()
void ksdk_gpio_handle_interrupt (GPIO_Type * base, port_number_t portNumber)
Definition at line 153 of file gpio_driver.c.
References GPIO_NUMBER_OF_PIN, and gpioIsrObj::isrHandle.
Referenced by ksdk_gpio_read_pin().