list(APPEND CMAKE_MODULE_PATH
    ${CMAKE_CURRENT_LIST_DIR}/.
    ${CMAKE_CURRENT_LIST_DIR}/../../CMSIS/Include
    ${CMAKE_CURRENT_LIST_DIR}/../../components/fxos8700cq
    ${CMAKE_CURRENT_LIST_DIR}/../../components/lists
    ${CMAKE_CURRENT_LIST_DIR}/../../components/osa
    ${CMAKE_CURRENT_LIST_DIR}/../../components/serial_manager
    ${CMAKE_CURRENT_LIST_DIR}/../../components/slcd_engine
    ${CMAKE_CURRENT_LIST_DIR}/../../components/slcd_engine/LCD-S401M16KR
    ${CMAKE_CURRENT_LIST_DIR}/../../components/uart
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/adc16
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/cmp
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/common
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/cop
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/dac
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/dma
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/dmamux
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/flash
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/flexio
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/gpio
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/i2c
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/llwu
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/lptmr
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/lpuart
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/pit
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/pmc
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/port
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/rcm
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/rtc
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/sim
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/slcd
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/smc
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/spi
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/tpm
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/uart
    ${CMAKE_CURRENT_LIST_DIR}/../../middleware
    ${CMAKE_CURRENT_LIST_DIR}/../../middleware/usb
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/assert
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/debug_console
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/debug_console_lite
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/misc_utilities
    ${CMAKE_CURRENT_LIST_DIR}/drivers
    ${CMAKE_CURRENT_LIST_DIR}/utilities
)


# Copy the cmake components into projects
mcux_include_from_kconfig(driver_llwu)
mcux_include_from_kconfig(CMSIS_Include_dsp)
mcux_include_from_kconfig(component_lpuart_adapter)
mcux_include_from_kconfig(driver_i2c)
mcux_include_from_kconfig(driver_port)
mcux_include_from_kconfig(driver_dmamux)
mcux_include_from_kconfig(driver_lptmr)
mcux_include_from_kconfig(driver_gpio)
mcux_include_from_kconfig(component_lists)
mcux_include_from_kconfig(driver_dac)
mcux_include_from_kconfig(driver_cop)
mcux_include_from_kconfig(driver_tpm)
mcux_include_from_kconfig(driver_cmp)
mcux_include_from_kconfig(device_startup)
mcux_include_from_kconfig(driver_adc16)
mcux_include_from_kconfig(driver_clock)
mcux_include_from_kconfig(component_serial_manager_K32L2B31A)
mcux_include_from_kconfig(utility_debug_console_lite)
mcux_include_from_kconfig(driver_flexio_uart)
mcux_include_from_kconfig(component_osa)
mcux_include_from_kconfig(driver_fxos8700cq)
mcux_include_from_kconfig(driver_lpuart)
mcux_include_from_kconfig(driver_flexio_spi)
mcux_include_from_kconfig(driver_flexio)
mcux_include_from_kconfig(middleware_usb_device_common_header)
mcux_include_from_kconfig(utility_notifier)
mcux_include_from_kconfig(device_system)
mcux_include_from_kconfig(CMSIS_Include_core_cm0plus)
mcux_include_from_kconfig(driver_flexio_i2c_master)
mcux_include_from_kconfig(driver_pmc)
mcux_include_from_kconfig(middleware_baremetal)
mcux_include_from_kconfig(driver_spi)
mcux_include_from_kconfig(driver_flash)
mcux_include_from_kconfig(utility_assert)
mcux_include_from_kconfig(driver_sim)
mcux_include_from_kconfig(utility_debug_console)
mcux_include_from_kconfig(device_CMSIS)
mcux_include_from_kconfig(driver_uart)
mcux_include_from_kconfig(driver_flexio_uart_dma)
mcux_include_from_kconfig(utility_assert_lite_K32L2B31A)
mcux_include_from_kconfig(utilities_misc_utilities)
mcux_include_from_kconfig(CMSIS_Include_common)
mcux_include_from_kconfig(driver_common)
mcux_include_from_kconfig(driver_rtc)
mcux_include_from_kconfig(driver_uart_dma)
mcux_include_from_kconfig(driver_smc)
mcux_include_from_kconfig(driver_spi_dma)
mcux_include_from_kconfig(driver_dma)
mcux_include_from_kconfig(driver_i2c_dma)
mcux_include_from_kconfig(driver_slcd)
mcux_include_from_kconfig(driver_lpuart_dma)
mcux_include_from_kconfig(driver_pit)
mcux_include_from_kconfig(driver_flexio_spi_dma)
mcux_include_from_kconfig(driver_rcm)
mcux_include_from_kconfig(driver_slcd_engine)
mcux_include_from_kconfig(utility_shell)
mcux_include_from_kconfig(middleware_usb_common_header)
mcux_include_from_kconfig(component_serial_manager_uart_K32L2B31A)
mcux_include_from_kconfig(driver_slcd_lcd_s401m16kr)
