if(NOT UTILITY_DEBUG_CONSOLE_INCLUDED)

    set(UTILITY_DEBUG_CONSOLE_INCLUDED true CACHE BOOL "utility_debug_console component is included.")

    target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE
        ${CMAKE_CURRENT_LIST_DIR}/str/fsl_str.c
        ${CMAKE_CURRENT_LIST_DIR}/debug_console/fsl_debug_console.c
    )

    target_include_directories(${MCUX_SDK_PROJECT_NAME} PRIVATE
        ${CMAKE_CURRENT_LIST_DIR}/debug_console
        ${CMAKE_CURRENT_LIST_DIR}/str
    )

    #OR Logic component
    if(${MCUX_DEVICE} STREQUAL "MIMXRT1052")
        include(component_serial_manager_MIMXRT1052)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMXRT1064")
        include(component_serial_manager_MIMXRT1064)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MK28FA15")
        include(component_serial_manager_MK28FA15)
    endif()
    if(${MCUX_DEVICE} STREQUAL "LPC54114_cm4")
        include(component_serial_manager_LPC54114_cm4)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMX8MM6")
        include(component_serial_manager_MIMX8MM6)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MKE15Z7")
        include(component_serial_manager_MKE15Z7)
    endif()
    if(${MCUX_DEVICE} STREQUAL "K32L2B31A")
        include(component_serial_manager_K32L2B31A)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MK64F12")
        include(component_serial_manager_MK64F12)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MK66F18")
        include(component_serial_manager_MK66F18)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MKE16Z4")
        include(component_serial_manager_MKE16Z4)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMX8QM6_cm4_core0")
        include(component_serial_manager_MIMX8QM6_cm4_core0)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMX8QM6_cm4_core1")
        include(component_serial_manager_MIMX8QM6_cm4_core1)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MKV11Z7")
        include(component_serial_manager_MKV11Z7)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MKV31F51212")
        include(component_serial_manager_MKV31F51212)
    endif()
    if(${MCUX_DEVICE} STREQUAL "LPC54628")
        include(component_serial_manager_LPC54628)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MK22F51212")
        include(component_serial_manager_MK22F51212)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MKE06Z4")
        include(component_serial_manager_MKE06Z4)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMX8QX6")
        include(component_serial_manager_MIMX8QX6)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMXRT1021")
        include(component_serial_manager_MIMXRT1021)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MKE02Z4")
        include(component_serial_manager_MKE02Z4)
    endif()
    if(${MCUX_DEVICE} STREQUAL "LPC55S16")
        include(component_serial_manager_LPC55S16)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMXRT1062")
        include(component_serial_manager_MIMXRT1062)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMX8MN6")
        include(component_serial_manager_MIMX8MN6)
    endif()
    if(${MCUX_DEVICE} STREQUAL "LPC54S018")
        include(component_serial_manager_LPC54S018)
    endif()
    if(${MCUX_DEVICE} STREQUAL "K32L3A60_cm0plus")
        include(component_serial_manager_K32L3A60_cm0plus)
    endif()
    if(${MCUX_DEVICE} STREQUAL "K32L3A60_cm4")
        include(component_serial_manager_K32L3A60_cm4)
    endif()
    if(${MCUX_DEVICE} STREQUAL "LPC54S018M")
        include(component_serial_manager_LPC54S018M)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MKM35Z7")
        include(component_serial_manager_MKM35Z7)
    endif()
    if(${MCUX_DEVICE} STREQUAL "LPC51U68")
        include(component_serial_manager_LPC51U68)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MKL27Z644")
        include(component_serial_manager_MKL27Z644)
    endif()
    if(${MCUX_DEVICE} STREQUAL "LPC55S69_cm33_core0")
        include(component_serial_manager_LPC55S69_cm33_core0)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MCIMX7U5")
        include(component_serial_manager_MCIMX7U5)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMXRT1024")
        include(component_serial_manager_MIMXRT1024)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMXRT1011")
        include(component_serial_manager_MIMXRT1011)
    endif()
    if(${MCUX_DEVICE} STREQUAL "LPC55S28")
        include(component_serial_manager_LPC55S28)
    endif()
    if(${MCUX_DEVICE} STREQUAL "K32L2A41A")
        include(component_serial_manager_K32L2A41A)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMXRT685S_cm33")
        include(component_serial_manager_MIMXRT685S_cm33)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMXRT1015")
        include(component_serial_manager_MIMXRT1015)
    endif()

    include(driver_common)

endif()