if(NOT UTILITY_DEBUG_CONSOLE_INCLUDED)

    set(UTILITY_DEBUG_CONSOLE_INCLUDED true CACHE BOOL "utility_debug_console component is included.")

    target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE
        ${CMAKE_CURRENT_LIST_DIR}/str/fsl_str.c
        ${CMAKE_CURRENT_LIST_DIR}/debug_console/fsl_debug_console.c
    )

    target_include_directories(${MCUX_SDK_PROJECT_NAME} PRIVATE
        ${CMAKE_CURRENT_LIST_DIR}/debug_console
        ${CMAKE_CURRENT_LIST_DIR}/str
    )

    #OR Logic component
    if(${MCUX_DEVICE} STREQUAL "MIMXRT1052")
        include(component_serial_manager_MIMXRT1052)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMXRT1064")
        include(component_serial_manager_MIMXRT1064)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MK28FA15")
        include(component_serial_manager_MK28FA15)
    endif()
    if(${MCUX_DEVICE} STREQUAL "LPC54114_cm4")
        include(component_serial_manager_LPC54114_cm4)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMX8MM6")
        include(component_serial_manager_MIMX8MM6)
    endif()
    if(${MCUX_DEVICE} STREQUAL "LPC54628")
        include(component_serial_manager_LPC54628)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMXRT1021")
        include(component_serial_manager_MIMXRT1021)
    endif()
    if(${MCUX_DEVICE} STREQUAL "LPC55S16")
        include(component_serial_manager_LPC55S16)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMXRT1062")
        include(component_serial_manager_MIMXRT1062)
    endif()
    if(${MCUX_DEVICE} STREQUAL "LPC54S018")
        include(component_serial_manager_LPC54S018)
    endif()
    if(${MCUX_DEVICE} STREQUAL "LPC54S018M")
        include(component_serial_manager_LPC54S018M)
    endif()
    if(${MCUX_DEVICE} STREQUAL "LPC51U68")
        include(component_serial_manager_LPC51U68)
    endif()
    if(${MCUX_DEVICE} STREQUAL "LPC55S69_cm33_core0")
        include(component_serial_manager_LPC55S69_cm33_core0)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMXRT1024")
        include(component_serial_manager_MIMXRT1024)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMXRT1011")
        include(component_serial_manager_MIMXRT1011)
    endif()
    if(${MCUX_DEVICE} STREQUAL "LPC55S28")
        include(component_serial_manager_LPC55S28)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMXRT685S_cm33")
        include(component_serial_manager_MIMXRT685S_cm33)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMXRT1015")
        include(component_serial_manager_MIMXRT1015)
    endif()

    include(driver_common)

endif()