list(APPEND CMAKE_MODULE_PATH
    ${CMAKE_CURRENT_LIST_DIR}/.
    ${CMAKE_CURRENT_LIST_DIR}/../../CMSIS/Include
    ${CMAKE_CURRENT_LIST_DIR}/../../components/codec
    ${CMAKE_CURRENT_LIST_DIR}/../../components/codec/port/wm8524
    ${CMAKE_CURRENT_LIST_DIR}/../../components/codec/wm8524
    ${CMAKE_CURRENT_LIST_DIR}/../../components/lists
    ${CMAKE_CURRENT_LIST_DIR}/../../components/uart
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/cache/lmem
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/common
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/ecspi
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/gpt
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/igpio
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/ii2c
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/ipwm
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/iuart
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/qspi
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/rdc
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/rdc_sema42
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/sai
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/sema4
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/tmu
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/wdog01
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/assert
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/debug_console_lite
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/misc_utilities
    ${CMAKE_CURRENT_LIST_DIR}/drivers
)


# Copy the cmake components into projects
mcux_include_from_kconfig(CMSIS_Include_dsp)
mcux_include_from_kconfig(driver_rdc)
mcux_include_from_kconfig(driver_ii2c)
mcux_include_from_kconfig(component_lists)
mcux_include_from_kconfig(device_system)
mcux_include_from_kconfig(driver_codec_MIMX8MQ6)
mcux_include_from_kconfig(device_startup)
mcux_include_from_kconfig(driver_clock)
mcux_include_from_kconfig(utility_debug_console_lite)
mcux_include_from_kconfig(driver_gpt)
mcux_include_from_kconfig(driver_iuart)
mcux_include_from_kconfig(driver_ipwm)
mcux_include_from_kconfig(driver_ecspi)
mcux_include_from_kconfig(driver_cache_lmem)
mcux_include_from_kconfig(driver_rdc_sema42)
mcux_include_from_kconfig(utility_assert_lite_MIMX8MQ6)
mcux_include_from_kconfig(device_CMSIS)
mcux_include_from_kconfig(driver_wdog01)
mcux_include_from_kconfig(component_iuart_adapter)
mcux_include_from_kconfig(component_wm8524_adapter)
mcux_include_from_kconfig(utilities_misc_utilities)
mcux_include_from_kconfig(CMSIS_Include_core_cm4)
mcux_include_from_kconfig(CMSIS_Include_common)
mcux_include_from_kconfig(driver_common)
mcux_include_from_kconfig(driver_sema4)
mcux_include_from_kconfig(driver_tmu)
mcux_include_from_kconfig(driver_igpio)
mcux_include_from_kconfig(driver_sai)
mcux_include_from_kconfig(driver_wm8524)
mcux_include_from_kconfig(driver_qspi)
