if(NOT DRIVER_EDMA_INCLUDED)

    set(DRIVER_EDMA_INCLUDED true CACHE BOOL "driver_edma component is included.")

    target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE
        ${CMAKE_CURRENT_LIST_DIR}/fsl_edma.c
    )

    target_include_directories(${MCUX_SDK_PROJECT_NAME} PRIVATE
        ${CMAKE_CURRENT_LIST_DIR}/.
    )

    #OR Logic component
    if(${MCUX_DEVICE} STREQUAL "MIMXRT1052")
        include(driver_dmamux)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMXRT1064")
        include(driver_dmamux)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MK28FA15")
        include(driver_dmamux)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MKE15Z7")
        include(driver_dmamux)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MK64F12")
        include(driver_dmamux)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MK66F18")
        include(driver_dmamux)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MKV11Z7")
        include(driver_dmamux)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MKV31F51212")
        include(driver_dmamux)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MK22F51212")
        include(driver_dmamux)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMXRT1021")
        include(driver_dmamux)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMXRT1062")
        include(driver_dmamux)
    endif()
    if(${MCUX_DEVICE} STREQUAL "K32L3A60_cm0plus")
        include(driver_dmamux)
    endif()
    if(${MCUX_DEVICE} STREQUAL "K32L3A60_cm4")
        include(driver_dmamux)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MCIMX7U5")
        include(driver_dmamux)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMXRT1024")
        include(driver_dmamux)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMXRT1011")
        include(driver_dmamux)
    endif()
    if(${MCUX_DEVICE} STREQUAL "K32L2A41A")
        include(driver_dmamux)
    endif()
    if(${MCUX_DEVICE} STREQUAL "MIMXRT1015")
        include(driver_dmamux)
    endif()

    include(driver_common)

endif()