# Copyright 2021 NXP
# SPDX-License-Identifier: BSD-3-Clause

function(include_ifdef feature_toggle module)
  if(${${feature_toggle}})
    include(${module})
  endif()
endfunction()

include_ifdef(CONFIG_MCUX_SDK_DRIVER_ADC16			driver_adc16)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_CLOCK			driver_clock)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_CMP			driver_cmp)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_CMP_1			driver_cmp_1)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_CMT			driver_cmt)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_COMMON			driver_common)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_CRC			driver_crc)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_DAC			driver_dac)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_DMAMUX			driver_dmamux)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_DSPI			driver_dspi)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_DSPI_EDMA			driver_dspi_edma)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_EDMA			driver_edma)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_EWM			driver_ewm)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_FLASH			driver_flash)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_FLEXCAN			driver_flexcan)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_FLEXCOMM			driver_flexcomm)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_FLEXCOMM_I2C		driver_flexcomm_i2c)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_FLEXCOMM_I2C_DMA		driver_flexcomm_i2c_dma)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_FLEXCOMM_I2S		driver_flexcomm_i2s)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_FLEXCOMM_I2S_DMA		driver_flexcomm_i2s_dma)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_FLEXCOMM_SPI		driver_flexcomm_spi)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_FLEXCOMM_SPI_DMA		driver_flexcomm_spi_dma)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_FLEXCOMM_USART		driver_flexcomm_usart)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_FLEXCOMM_USART_DMA		driver_flexcomm_usart_dma)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_FTM			driver_ftm)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_GPIO			driver_gpio)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_I2C			driver_i2c)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_I2C_EDMA			driver_i2c_edma)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_INPUTMUX			driver_inputmux)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_LPADC			driver_lpadc)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_LPC_CRC			driver_lpc_crc)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_LPC_DMA			driver_lpc_dma)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_LPC_GPIO			driver_lpc_gpio)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_LPC_IOCON			driver_lpc_iocon)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_LPTMR			driver_lptmr)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_PDB			driver_pdb)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_PINT			driver_pint)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_PIT			driver_pit)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_PORT			driver_port)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_PUF			driver_puf)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_RCM			driver_rcm)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_RNGA			driver_rnga)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_RTC			driver_rtc)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_SIM			driver_sim)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_SMC			driver_smc)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_SYSMPU			driver_sysmpu)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_UART			driver_uart)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_UART_EDMA			driver_uart_edma)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_VREF			driver_vref)
include_ifdef(CONFIG_MCUX_SDK_DRIVER_WDOG			driver_wdog)
