list(APPEND CMAKE_MODULE_PATH
    ${CMAKE_CURRENT_LIST_DIR}/.
    ${CMAKE_CURRENT_LIST_DIR}/../../CMSIS/Include
    ${CMAKE_CURRENT_LIST_DIR}/../../components/fxos8700cq
    ${CMAKE_CURRENT_LIST_DIR}/../../components/lists
    ${CMAKE_CURRENT_LIST_DIR}/../../components/serial_manager
    ${CMAKE_CURRENT_LIST_DIR}/../../components/uart
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/cau3
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/common
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/crc
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/dac_1
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/dmamux
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/edma
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/ewm
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/flash
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/flexio
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/gpio
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/intmux
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/lpadc
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/lpcmp
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/lpi2c
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/lpit
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/lpspi
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/lptmr
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/lpuart
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/mmdvsq
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/msmc
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/mu
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/port
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/rtc
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/sema42
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/sim
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/tpm
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/trng
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/tstmr
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/xrdc
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/assert
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/debug_console
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/debug_console_lite
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/misc_utilities
    ${CMAKE_CURRENT_LIST_DIR}/drivers
    ${CMAKE_CURRENT_LIST_DIR}/drivers/cm0plus
    ${CMAKE_CURRENT_LIST_DIR}/utilities
)


# Copy the cmake components into projects
mcux_include_from_kconfig(device_CMSIS_K32L3A60_cm0plus)
mcux_include_from_kconfig(driver_flexio_spi_edma)
mcux_include_from_kconfig(CMSIS_Include_dsp)
mcux_include_from_kconfig(component_lpuart_adapter)
mcux_include_from_kconfig(driver_flexio_uart)
mcux_include_from_kconfig(component_serial_manager_uart_K32L3A60_cm0plus)
mcux_include_from_kconfig(driver_dmamux)
mcux_include_from_kconfig(driver_lpspi)
mcux_include_from_kconfig(driver_lpi2c_edma)
mcux_include_from_kconfig(driver_gpio)
mcux_include_from_kconfig(component_lists)
mcux_include_from_kconfig(driver_flexio_uart_edma)
mcux_include_from_kconfig(driver_lpit)
mcux_include_from_kconfig(driver_cau3)
mcux_include_from_kconfig(driver_lpadc)
mcux_include_from_kconfig(driver_port)
mcux_include_from_kconfig(driver_clock)
mcux_include_from_kconfig(utility_debug_console_lite)
mcux_include_from_kconfig(component_serial_manager_K32L3A60_cm0plus)
mcux_include_from_kconfig(driver_edma)
mcux_include_from_kconfig(driver_ewm)
mcux_include_from_kconfig(driver_trng)
mcux_include_from_kconfig(driver_lpuart)
mcux_include_from_kconfig(driver_flexio_spi)
mcux_include_from_kconfig(driver_xrdc)
mcux_include_from_kconfig(driver_flexio)
mcux_include_from_kconfig(utility_shell)
mcux_include_from_kconfig(driver_msmc)
mcux_include_from_kconfig(CMSIS_Include_core_cm0plus)
mcux_include_from_kconfig(driver_flexio_i2c_master)
mcux_include_from_kconfig(driver_sim)
mcux_include_from_kconfig(driver_flash)
mcux_include_from_kconfig(utility_assert)
mcux_include_from_kconfig(driver_mmdvsq)
mcux_include_from_kconfig(driver_sema42)
mcux_include_from_kconfig(utility_debug_console)
mcux_include_from_kconfig(driver_lpspi_edma)
mcux_include_from_kconfig(driver_lpcmp)
mcux_include_from_kconfig(driver_cache_lplmem)
mcux_include_from_kconfig(driver_tstmr)
mcux_include_from_kconfig(utilities_misc_utilities)
mcux_include_from_kconfig(driver_lpi2c)
mcux_include_from_kconfig(CMSIS_Include_common)
mcux_include_from_kconfig(driver_common)
mcux_include_from_kconfig(driver_rtc)
mcux_include_from_kconfig(utility_assert_lite_K32L3A60_cm0plus)
mcux_include_from_kconfig(driver_crc)
mcux_include_from_kconfig(device_system_K32L3A60_cm0plus)
mcux_include_from_kconfig(driver_fxos8700cq)
mcux_include_from_kconfig(driver_lptmr)
mcux_include_from_kconfig(device_startup_K32L3A60_cm0plus)
mcux_include_from_kconfig(driver_mu)
mcux_include_from_kconfig(driver_intmux)
mcux_include_from_kconfig(driver_tpm)
mcux_include_from_kconfig(driver_dac_1)
