/*
 * Copyright 2019 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
    kPIN_MUX_DirectionInput = 0U,        /* Input direction */
    kPIN_MUX_DirectionOutput = 1U,       /* Output direction */
    kPIN_MUX_DirectionInputOrOutput = 2U /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PIO0_7 (number 17), CN5[4]/CN3[27]/CN6[2]/LD17/LD18/PIO0_7_GPIO3-LED
  @{ */
/*!
 * @brief Device name: GPIO */
#define BOARD_USER_LED_PERIPHERAL GPIO
/*!
 * @brief GPIO signal: PIO0 */
#define BOARD_USER_LED_SIGNAL PIO0
/*!
 * @brief GPIO device name: GPIO */
#define BOARD_USER_LED_GPIO GPIO
/*!
 * @brief PIO0 pin index: 7 */
#define BOARD_USER_LED_GPIO_PIN 7U
/*!
 * @brief PORT device name: 0U */
#define BOARD_USER_LED_PORT 0U
/*!
 * @brief 0U pin index: 7 */
#define BOARD_USER_LED_PIN 7U
/*!
 * @brief GPIO PIO0 channel: 7 */
#define BOARD_USER_LED_CHANNEL 7
/*!
 * @brief Pin name */
#define BOARD_USER_LED_PIN_NAME PIO0_7
/*!
 * @brief Label */
#define BOARD_USER_LED_LABEL "CN5[4]/CN3[27]/CN6[2]/LD17/LD18/PIO0_7_GPIO3-LED"
/*!
 * @brief Identifier name */
#define BOARD_USER_LED_NAME "USER_LED"
/*!
 * @brief Direction */
#define BOARD_USER_LED_DIRECTION kPIN_MUX_DirectionOutput
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M0P */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
