#Description: ENET CMSIS Driver; user_visible: True
include_guard(GLOBAL)
message("driver_cmsis_enet component is included.")

target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/fsl_enet_cmsis.c
    ${CMAKE_CURRENT_LIST_DIR}/fsl_enet_phy_cmsis.c
)

target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
    ${CMAKE_CURRENT_LIST_DIR}/.
)

#OR Logic component
if(${MCUX_DEVICE} STREQUAL "MIMXRT1166_cm4")
    include(driver_phy-common_MIMXRT1166_cm4)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1166_cm7")
    include(driver_phy-common_MIMXRT1166_cm7)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1052")
    include(driver_phy-common_MIMXRT1052)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1064")
    include(driver_phy-common_MIMXRT1064)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MM6")
    include(driver_phy-common_MIMX8MM6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MM1")
    include(driver_phy-common_MIMX8MM6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MM5")
    include(driver_phy-common_MIMX8MM6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MM2")
    include(driver_phy-common_MIMX8MM6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8ML3")
    include(driver_phy-common_MIMX8ML8)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1173_cm4")
    include(driver_phy-common_MIMXRT1176_cm4)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1173_cm7")
    include(driver_phy-common_MIMXRT1176_cm7)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1021")
    include(driver_phy-common_MIMXRT1021)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MM3")
    include(driver_phy-common_MIMX8MM6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1062")
    include(driver_phy-common_MIMXRT1062)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8ML6")
    include(driver_phy-common_MIMX8ML8)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1042")
    include(driver_phy-common_MIMXRT1042)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1176_cm4")
    include(driver_phy-common_MIMXRT1176_cm4)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1176_cm7")
    include(driver_phy-common_MIMXRT1176_cm7)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1175_cm4")
    include(driver_phy-common_MIMXRT1176_cm4)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1175_cm7")
    include(driver_phy-common_MIMXRT1176_cm7)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1165_cm4")
    include(driver_phy-common_MIMXRT1166_cm4)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1165_cm7")
    include(driver_phy-common_MIMXRT1166_cm7)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8ML4")
    include(driver_phy-common_MIMX8ML8)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1024")
    include(driver_phy-common_MIMXRT1024)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8MM4")
    include(driver_phy-common_MIMX8MM6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8ML8")
    include(driver_phy-common_MIMX8ML8)
endif()
if(${MCUX_DEVICE} STREQUAL "MK64F12")
    include(driver_phy-common_MK64F12)
endif()
if(${MCUX_DEVICE} STREQUAL "MK66F18")
    include(driver_phy-common_MK66F18)
endif()

include(CMSIS_Driver_Include_Ethernet_PHY)
include(driver_enet)
include(CMSIS_Driver_Include_Ethernet_MAC)
