calibration_storage.c File Reference
calibration_storage.c File Reference
Functions
void SaveMagCalibrationToNVM (SensorFusionGlobals *sfg)
void SaveGyroCalibrationToNVM (SensorFusionGlobals *sfg)
void SaveAccelCalibrationToNVM (SensorFusionGlobals *sfg)
void EraseMagCalibrationFromNVM (void)
void EraseGyroCalibrationFromNVM (void)
void EraseAccelCalibrationFromNVM (void)
Detailed Description
Users who are not using NXP hardware will need to supply their own drivers in place of those defined here.
Definition in file calibration_storage.c.
Function Documentation
void EraseAccelCalibrationFromNVM (void)
Definition at line 188 of file calibration_storage.c.
Referenced by DecodeCommandBytes().
 {
     uint8_t *pSrc, *pDst;                   // scratch pointers
     int16_t i;                          // loop counter
     uint8_t iNVMBuffer[256];                // NVM write buffer
     // copy existing magnetic, gyro and accelerometer calibrations to buffer
     pSrc = (uint8 *) CALIBRATION_NVM_ADDR;
     pDst = iNVMBuffer;
     for (i = 0; i < 256; i++)
         *(pDst++) = *(pSrc++);
     // set no gyroscope calibration in header
     iNVMBuffer[ACCEL_NVM_OFFSET] = iNVMBuffer[ACCEL_NVM_OFFSET + 1] = iNVMBuffer[ACCEL_NVM_OFFSET + 2] = iNVMBuffer[ACCEL_NVM_OFFSET + 3] = 0xFF;
     // write the buffer to flash
     NVM_SetBlockFlash(iNVMBuffer, CALIBRATION_NVM_ADDR, 256);
     return;
 }
void EraseGyroCalibrationFromNVM (void)
Definition at line 167 of file calibration_storage.c.
Referenced by DecodeCommandBytes().
 {
     uint8_t *pSrc, *pDst;                   // scratch pointers
     int16_t i;                          // loop counter
     uint8_t iNVMBuffer[256];                // NVM write buffer
     // copy existing magnetic, gyro and accelerometer calibrations to buffer
     pSrc = (uint8 *) CALIBRATION_NVM_ADDR;
     pDst = iNVMBuffer;
     for (i = 0; i < 256; i++)
         *(pDst++) = *(pSrc++);
     // set no gyroscope calibration in header
     iNVMBuffer[GYRO_NVM_OFFSET] = iNVMBuffer[GYRO_NVM_OFFSET + 1] = iNVMBuffer[GYRO_NVM_OFFSET + 2] = iNVMBuffer[GYRO_NVM_OFFSET + 3] = 0xFF;
     // write the buffer to flash
     NVM_SetBlockFlash(iNVMBuffer, CALIBRATION_NVM_ADDR, 256);
     return;
 }
void EraseMagCalibrationFromNVM (void)
Definition at line 146 of file calibration_storage.c.
Referenced by DecodeCommandBytes().
 {
     uint8_t *pSrc, *pDst;                   // scratch pointers
     int16_t i;                      // loop counter
     uint8_t iNVMBuffer[256];                // NVM write buffer
     // copy existing magnetic, gyro and accelerometer calibrations to buffer
     pSrc = (uint8 *) CALIBRATION_NVM_ADDR;
     pDst = iNVMBuffer;
     for (i = 0; i < 256; i++)
         *(pDst++) = *(pSrc++);
     // set no magnetic calibration in header
     iNVMBuffer[MAG_NVM_OFFSET] = iNVMBuffer[MAG_NVM_OFFSET + 1] = iNVMBuffer[MAG_NVM_OFFSET + 2] = iNVMBuffer[MAG_NVM_OFFSET + 3] = 0xFF;
     // write the buffer to flash
     NVM_SetBlockFlash(iNVMBuffer, CALIBRATION_NVM_ADDR, 256);
     return;
 }
void SaveAccelCalibrationToNVM (SensorFusionGlobals * sfg)
Definition at line 112 of file calibration_storage.c.
Referenced by DecodeCommandBytes().
 {
 #if F_USING_ACCEL
     uint8_t *pSrc, *pDst;                   // scratch pointers
     int16_t i;                          // loop counter
     uint8_t iNVMBuffer[256];                // NVM write buffer
         uint32_t itmp32;
     // copy existing magnetic, gyro and accelerometer calibrations to buffer
     pSrc = (uint8 *) CALIBRATION_NVM_ADDR;
     pDst = iNVMBuffer;
     for (i = 0; i < 256; i++)
         *(pDst++) = *(pSrc++);
     // default to no gyroscope calibration in header
     iNVMBuffer[ACCEL_NVM_OFFSET] = iNVMBuffer[ACCEL_NVM_OFFSET + 1] = iNVMBuffer[ACCEL_NVM_OFFSET + 2] = iNVMBuffer[ACCEL_NVM_OFFSET + 3] = 0xFF;
     // [0-3]: four byte header denoting accelerometer calibration present
     itmp32 = 0x12345678;
     pSrc = (uint8 *) &itmp32;
     pDst = iNVMBuffer + ACCEL_NVM_OFFSET;
     for (i = 0; i < 4; i++)
         *(pDst++) = *(pSrc++);
     // [4-87]: 21 precision accelerometer calibration floats totalling 84 bytes
     pSrc = (uint8 *) &(sfg->AccelCal);
     for (i = 0; i < 84; i++)
         *(pDst++) = *(pSrc++);
     // write the buffer contents to NVM
     NVM_SetBlockFlash(iNVMBuffer, CALIBRATION_NVM_ADDR, 256);
 #endif
     return;
 }
void SaveGyroCalibrationToNVM (SensorFusionGlobals * sfg)
Definition at line 73 of file calibration_storage.c.
Referenced by DecodeCommandBytes().
 {
 #if F_USING_GYRO && (F_9DOF_GBY_KALMAN || F_6DOF_GY_KALMAN)
     uint8_t *pSrc, *pDst;                   // scratch pointers
     int16_t i;                      // loop counter
     uint8_t iNVMBuffer[256];                // NVM write buffer
         uint32_t itmp32;
     // copy existing magnetic, gyro and accelerometer calibrations to buffer
     pSrc = (uint8 *) CALIBRATION_NVM_ADDR;
     pDst = iNVMBuffer;
     for (i = 0; i < 256; i++)
         *(pDst++) = *(pSrc++);
     // default to no gyroscope calibration in header
     iNVMBuffer[GYRO_NVM_OFFSET] = iNVMBuffer[GYRO_NVM_OFFSET + 1] = iNVMBuffer[GYRO_NVM_OFFSET + 2] = iNVMBuffer[GYRO_NVM_OFFSET + 3] = 0xFF;
     // define the four header bytes
     // [0-3]: four byte header denoting gyro calibration present
     itmp32 = 0x12345678;
     pSrc = (uint8 *) &itmp32;
     pDst = iNVMBuffer + GYRO_NVM_OFFSET;
     for (i = 0; i < 4; i++)
         *(pDst++) = *(pSrc++);
     // [4-15]: 3 gyro offset floats totalling 12 bytes
 #if F_9DOF_GBY_KALMAN
     pSrc = (uint8 *) sfg->SV_9DOF_GBY_KALMAN.fbPl;
 #elif F_6DOF_GY_KALMAN
     pSrc = (uint8 *) sfg->SV_6DOF_GY_KALMAN.fbPl;
 #endif
     for (i = 0; i < 12; i++)
         *(pDst++) = *(pSrc++);
     // write the buffer contents to NVM
     NVM_SetBlockFlash(iNVMBuffer, CALIBRATION_NVM_ADDR, 256);
 #endif
     return;
 }
void SaveMagCalibrationToNVM (SensorFusionGlobals * sfg)
Definition at line 39 of file calibration_storage.c.
Referenced by DecodeCommandBytes().
 {
 #if F_USING_MAG
     uint8_t *pSrc, *pDst;                   // scratch pointers
     int16_t i;                      // loop counter
     uint8_t iNVMBuffer[256];                // NVM write buffer (smallest size writeable to flash)
         uint32_t itmp32;
     // copy existing magnetic, gyro and accelerometer calibrations to buffer
     pSrc = (uint8 *) CALIBRATION_NVM_ADDR;
     pDst = iNVMBuffer;
     for (i = 0; i < 256; i++)
         *(pDst++) = *(pSrc++);
     // default to no magnetic calibration in header
     iNVMBuffer[MAG_NVM_OFFSET] = iNVMBuffer[MAG_NVM_OFFSET + 1] = iNVMBuffer[MAG_NVM_OFFSET + 2] = iNVMBuffer[MAG_NVM_OFFSET + 3] = 0xFF;
     // fill the buffer with the magnetic calibration in bytes 0 to 67 (total 68 bytes)
     // [0-3]: four byte header denoting magnetic calibration present
     itmp32 = 0x12345678;
     pSrc = (uint8 *) &itmp32;
     pDst = iNVMBuffer + MAG_NVM_OFFSET;
     for (i = 0; i < 4; i++)
         *(pDst++) = *(pSrc++);
     // [4-67]: magnetic calibration: 15x float + 1x int32 total 64 bytes
     pSrc = (uint8 *) &(sfg->MagCal);
     for (i = 0; i < 64; i++)
         *(pDst++) = *(pSrc++);
     // write the whole buffer contents to NVM
     NVM_SetBlockFlash(iNVMBuffer, CALIBRATION_NVM_ADDR, 256);
 #endif // if F_USING_MAG
     return;
 }