control.c File Reference
control.c File Reference
Macros
#define F_USE_WIRELESS_UART 0x0001
#define F_USE_WIRED_UART 0x0002
#define CONTROL_BAUDRATE 115200
Functions
void myUART_WriteByte (UART_Type *base, uint8_t data)
int8_t writeControlPort (ControlSubsystem *pComm, uint8_t buffer[], uint16_t nbytes)
int8_t writeWirelessPort (uint8_t buffer[], uint16_t nbytes)
void WIRELESS_UART_IRQHandler (void)
void BlueRadios_Init (void)
void echo (uint8_t data)
void WIRED_UART_IRQHandler (void)
int8_t initializeControlPort (ControlSubsystem *pComm)
Variables
uart_handle_t wired_uartHandle
uart_handle_t wireless_uartHandle
uint8_t sUARTOutputBuffer [256]
SensorFusionGlobals sfg
Detailed Description
This file contains a UART implementation of the control subsystem. The command interpreter and streaming functions are contained in two separate files. So you can easily swap those out with only minor changes here.
Definition in file control.c.
Macro Definition Documentation
#define CONTROL_BAUDRATE 115200
Baudrate to be used for serial communications.
Definition at line 53 of file control.c.
Referenced by initializeControlPort().
#define F_USE_WIRED_UART 0x0002
0x0002 to include, 0x0000 otherwise
Definition at line 50 of file control.c.
#define F_USE_WIRELESS_UART 0x0001
0x0001 to include, 0x0000 otherwise
Definition at line 47 of file control.c.
Function Documentation
void BlueRadios_Init (void)
Used to initialize the Blue Radios Bluetooth module found on the FRDM-FXS-MULT2-B sensor shield from NXP.
Definition at line 132 of file control.c.
Referenced by initializeControlPort().
 {
     uint16_t ilen;      // command string length
     // transmit "ATSRM,2,0\r" to minimize traffic from the module
     // command "ATSRM": sets the module response mode which configures how verbose the module will be
     // 2: response mode at to minimal
     // 0: disconnected mode is command mode
     // \r: carriage return escape sequence
     strcpy((char *)sUARTOutputBuffer, "ATSRM,2,0\r");
     ilen = strlen((char *)sUARTOutputBuffer);
         writeWirelessPort(sUARTOutputBuffer, ilen);
     return;
 }
void echo (uint8_t data)
Definition at line 149 of file control.c.
 {
     /* Send data only when UART TX register is empty and ring buffer has data to send out. */
     if (kUART_TxDataRegEmptyFlag & UART_GetStatusFlags(WIRED_UART))
     {
         UART_WriteByte(WIRED_UART, data);
     }
 }
int8_t initializeControlPort (ControlSubsystem * pComm)
Initialize the control subsystem and all related hardware.
Call this once to initialize structures, ports, etc.
Parameters
pComm pointer to the control subystem structure
Definition at line 182 of file control.c.
Referenced by main().
 {
     uart_config_t   config;
     if (pComm)
     {
         pComm->DefaultQuaternionPacketType = Q3;    // default to simplest algorithm
         pComm->QuaternionPacketType = Q3;           // default to simplest algorithm
         pComm->AngularVelocityPacketOn = true;      // transmit angular velocity packet
         pComm->DebugPacketOn = true;                // transmit debug packet
         pComm->RPCPacketOn = true;                  // transmit roll, pitch, compass packet
         pComm->AltPacketOn = true;                 // Altitude packet
         pComm->AccelCalPacketOn = 0;
         pComm->write = writeControlPort;
         pComm->stream = CreateAndSendPackets;
 #if F_USE_WIRED_UART
         /* Initialize WIRED UART pins below - currently duplicates code in pin_mux.c */
         CLOCK_EnableClock(WIRED_UART_PORT_CLKEN);
         PORT_SetPinMux(WIRED_UART_PORT, WIRED_UART_RX_PIN, WIRED_UART_MUX);
         PORT_SetPinMux(WIRED_UART_PORT, WIRED_UART_TX_PIN, WIRED_UART_MUX);
         UART_GetDefaultConfig(&config);
         config.baudRate_Bps = CONTROL_BAUDRATE;
         config.enableTx = true;
         config.enableRx = true;
         config.rxFifoWatermark = 1;
         UART_Init(WIRED_UART, &config, CLOCK_GetFreq(WIRED_UART_CLKSRC));
         /* Enable RX interrupt. */
         UART_EnableInterrupts(WIRED_UART, kUART_RxDataRegFullInterruptEnable |
                               kUART_RxOverrunInterruptEnable);
         EnableIRQ(WIRED_UART_IRQn);
 #endif
 #if F_USE_WIRELESS_UART
         /* Initialize WIRELESS UART pins below */
         CLOCK_EnableClock(WIRELESS_UART_PORT_CLKEN);
         PORT_SetPinMux(WIRELESS_UART_PORT, WIRELESS_UART_RX_PIN,
                        WIRELESS_UART_MUX);
         PORT_SetPinMux(WIRELESS_UART_PORT, WIRELESS_UART_TX_PIN,
                        WIRELESS_UART_MUX);
         UART_Init(WIRELESS_UART, &config, CLOCK_GetFreq(WIRELESS_UART_CLKSRC));
         BlueRadios_Init();
         /* Enable RX interrupt. */
         UART_EnableInterrupts(WIRELESS_UART, kUART_RxDataRegFullInterruptEnable |
                               kUART_RxOverrunInterruptEnable);
         EnableIRQ(WIRELESS_UART_IRQn);
 #endif
         return (0);
     }
     else
     {
         return (1);
     }
 }
void myUART_WriteByte (UART_Type * base, uint8_t data)
Definition at line 68 of file control.c.
Referenced by writeControlPort(), and writeWirelessPort().
 {
     uint8_t flag = 0;
     while (!flag)
     {
         flag = base->S1 & 0x80;
     }
     UART_WriteByte(base, data);
 }
void WIRED_UART_IRQHandler (void)
Definition at line 158 of file control.c.
 {
     uint8_t     data;
     status_t    sts;
     uint32_t    nbytes;        // number of bytes received
     uint32_t    flags;
     static char iCommandBuffer_A[5] = "~~~~";   // 5 bytes long to include the unused terminating \0
     sfg.setStatus(&sfg, RECEIVING_WIRED);
     flags = UART_GetStatusFlags(WIRED_UART);
     /* If new data arrived. */
     if ((kUART_RxDataRegFullFlag | kUART_RxOverrunFlag) & flags)
     {
         sts = UART_TransferGetReceiveCount(WIRED_UART, &wired_uartHandle, &nbytes);
         if (sts == kStatus_Success)
         {
             data = UART_ReadByte(WIRED_UART);
             DecodeCommandBytes(&sfg, iCommandBuffer_A, &data, 1);
         }
     }
 }
void WIRELESS_UART_IRQHandler (void)
Definition at line 110 of file control.c.
 {
     uint8_t     data;
     status_t    sts;
     uint32_t    nbytes;             // number of bytes received
     uint32_t    flags;
     static char iCommandBuffer_B[5] = "~~~~";   // 5 bytes long to include the unused terminating \0
     sfg.setStatus(&sfg, RECEIVING_WIRELESS);
     flags = UART_GetStatusFlags(WIRELESS_UART);
     /* If new data arrived. */
     if ((kUART_RxDataRegFullFlag | kUART_RxOverrunFlag) & flags)
     {
         sts = UART_TransferGetReceiveCount(WIRELESS_UART, &wireless_uartHandle, &nbytes);
         if (sts == kStatus_Success)
         {
             data = UART_ReadByte(WIRELESS_UART);
             DecodeCommandBytes(&sfg, iCommandBuffer_B, &data, 1);
         }
     }
 }
int8_t writeControlPort (ControlSubsystem * pComm, uint8_t buffer[], uint16_t nbytes)
Definition at line 79 of file control.c.
Referenced by initializeControlPort().
 {
     uint16_t    i;
     for (i = 0; i < nbytes; i++)
     {
 #if F_USE_WIRED_UART
         myUART_WriteByte(WIRED_UART, buffer[i]);
 #endif
 #if F_USE_WIRELESS_UART
         myUART_WriteByte(WIRELESS_UART, buffer[i]);
 #endif
     }
     return (0);
 }
int8_t writeWirelessPort (uint8_t buffer[], uint16_t nbytes)
Definition at line 99 of file control.c.
Referenced by BlueRadios_Init().
 {
     uint16_t    i;
     for (i = 0; i < nbytes; i++)
     {
         myUART_WriteByte(WIRELESS_UART, buffer[i]);
     }
     return (0);
 }
Variable Documentation
SensorFusionGlobals sfg
This is the primary sensor fusion data structure.
Definition at line 62 of file main_agm01_freertos_two_tasks.c.
Referenced by FXOS8700_Init(), and initializeSensors().
uint8_t sUARTOutputBuffer[256]
main output buffer defined in control.c
Definition at line 59 of file control.c.
Referenced by BlueRadios_Init(), fusion_task(), main(), and read_task().
uart_handle_t wired_uartHandle
Definition at line 55 of file control.c.
Referenced by WIRED_UART_IRQHandler().
uart_handle_t wireless_uartHandle
Definition at line 56 of file control.c.
Referenced by WIRELESS_UART_IRQHandler().