driver_KSDK_NVM.h File Reference
driver_KSDK_NVM.h File Reference
Functions
byte NVM_SetBlockFlash (uint8_t *Source, uint32_t Dest, uint16_t Count)
Function Documentation
byte NVM_SetBlockFlash (uint8_t * Source, uint32_t Dest, uint16_t Count)
Definition at line 34 of file driver_KSDK_NVM.c.
Referenced by EraseAccelCalibrationFromNVM(), EraseGyroCalibrationFromNVM(), EraseMagCalibrationFromNVM(), SaveAccelCalibrationToNVM(), SaveGyroCalibrationToNVM(), and SaveMagCalibrationToNVM().
 {
     status_t result;
     uint32_t pflashSectorSize = 0;
     flash_config_t flashDriver;                                            /* Flash driver Structure */
     byte retVal=0;
     /* Clean up Flash driver Structure*/
     memset(&flashDriver, 0, sizeof(flash_config_t));
     /* Setup flash driver structure for device and initialize variables. */
     result = FLASH_Init(&flashDriver);
     if (kStatus_FLASH_Success == result)
     {
 #ifdef KSDK_2_0_SDK
         FLASH_GetProperty(&flashDriver, kFLASH_propertyPflashSectorSize, &pflashSectorSize);
         result = FLASH_Erase(&flashDriver, Dest, pflashSectorSize, kFLASH_apiEraseKey);
 #else
         FLASH_GetProperty(&flashDriver, kFLASH_PropertyPflashSectorSize, &pflashSectorSize);
         result = FLASH_Erase(&flashDriver, Dest, pflashSectorSize, kFLASH_ApiEraseKey);
 #endif
         if (kStatus_FLASH_Success == result) {
             result = FLASH_Program(&flashDriver, Dest, (uint32_t*) Source, Count);
             if (kStatus_FLASH_Success == result) {
               retVal=SUCCESS;
             } else {
               retVal=ERROR;
             }
         } else {
             retVal=ERROR;
         }
     } else {
         retVal=ERROR;
     }
     return(retVal);
 }