driver_MAG3110.c File Reference
driver_MAG3110.c File Reference
Macros
#define MAG3110_COUNTSPERUT 10
Functions
int8_t MAG3110_Init (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t MAG3110_Read (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t MAG3110_Idle (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
Variables
const registerreadlist_t MAG3110_WHO_AM_I_READ []
const registerreadlist_t MAG3110_DR_STATUS_READ []
registerreadlist_t MAG3110_DATA_READ []
const registerwritelist_t MAG3110_Initialization []
const registerwritelist_t MAG3110_IDLE []
Macro Definition Documentation
#define MAG3110_COUNTSPERUT 10
Definition at line 40 of file driver_MAG3110.c.
Referenced by MAG3110_Init().
Function Documentation
int8_t MAG3110_Idle (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
Definition at line 168 of file driver_MAG3110.c.
Referenced by fusion_task().
 {
     int32_t     status;
     if(sensor->isInitialized == F_USING_MAG) {
         status = Sensor_I2C_Write(sensor->bus_driver, sensor->addr, MAG3110_IDLE );
         sensor->isInitialized = 0;
         sfg->Mag.isEnabled = false;
     } else {
       return SENSOR_ERROR_INIT;
     }
     return status;
 }
int8_t MAG3110_Init (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
Definition at line 103 of file driver_MAG3110.c.
Referenced by fusion_task(), and main().
 {
     int32_t status;
     uint8_t reg;
     status = Register_I2C_Read(sensor->bus_driver, sensor->addr, MAG3110_WHO_AM_I, 1, &reg);
     if (status==SENSOR_ERROR_NONE) {
         sfg->Mag.iWhoAmI = reg;
         if (reg!=MAG3110_WHOAMI_VALUE) {
              return(SENSOR_ERROR_INIT);
         }
     } else {
         // iWhoAmI will return default value of zero
         // return with error
         return(SENSOR_ERROR_INIT);
     }
     // Configure and start the MAG3110 sensor.  This does multiple register writes
     // (see MAG3110_Initialization definition above)
     status = Sensor_I2C_Write(sensor->bus_driver, sensor->addr, MAG3110_Initialization );
     // Stash some needed constants in the SF data structure for this sensor
     sfg->Mag.iCountsPeruT = MAG3110_COUNTSPERUT;
     sfg->Mag.fCountsPeruT = (float)MAG3110_COUNTSPERUT; // IAR optimized this out without the #pragma before the function
     sfg->Mag.fuTPerCount = 1.0F / MAG3110_COUNTSPERUT;  // IAR optimized this out without the #pragma before the function
     sensor->isInitialized = F_USING_MAG;        // IAR optimized this out without the #pragma before the function
     sfg->Mag.isEnabled = true;                  // IAR optimized this out without the #pragma before the function
     return (status);
 }
int8_t MAG3110_Read (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
Definition at line 134 of file driver_MAG3110.c.
Referenced by main().
 {
     uint8_t                     I2C_Buffer[6];  // I2C read buffer
     int8_t                      status;         // I2C transaction status
     int16_t                     sample[3];      // Reconstructed sample
     if(sensor->isInitialized != F_USING_MAG)
     {
         return SENSOR_ERROR_INIT;
     }
     status =  Sensor_I2C_Read(sensor->bus_driver, sensor->addr, MAG3110_DATA_READ, I2C_Buffer );
     sample[CHX] = (I2C_Buffer[0] << 8) | I2C_Buffer[1];
     sample[CHY] = (I2C_Buffer[2] << 8) | I2C_Buffer[3];
     sample[CHZ] = (I2C_Buffer[4] << 8) | I2C_Buffer[5];
     if (status==SENSOR_ERROR_NONE) {
         conditionSample(sample);  // truncate negative values to -32767
         sample[CHZ] = -sample[CHZ];  // +Z should point up (MAG3110 Z positive is down)
         addToFifo((FifoSensor*) &(sfg->Mag), MAG_FIFO_SIZE, sample);
     }
     return (status);
 }
Variable Documentation
registerreadlist_t MAG3110_DATA_READ[]
Initial value:
=
{
    { .readFrom = MAG3110_OUT_X_MSB, .numBytes = 6 }, __END_READ_DATA__
}
Definition at line 57 of file driver_MAG3110.c.
Referenced by MAG3110_Read().
const registerreadlist_t MAG3110_DR_STATUS_READ[]
Initial value:
=
{
    { .readFrom = MAG3110_DR_STATUS, .numBytes = 1 }, __END_READ_DATA__
}
Definition at line 51 of file driver_MAG3110.c.
const registerwritelist_t MAG3110_IDLE[]
Initial value:
=
{
  { MAG3110_CTRL_REG1, 0x00, 0x00 },
    __END_WRITE_DATA__
}
Definition at line 160 of file driver_MAG3110.c.
Referenced by MAG3110_Idle().
const registerwritelist_t MAG3110_Initialization[]
Definition at line 63 of file driver_MAG3110.c.
Referenced by MAG3110_Init().
const registerreadlist_t MAG3110_WHO_AM_I_READ[]
Initial value:
=
{
    { .readFrom = MAG3110_WHO_AM_I, .numBytes = 1 }, __END_READ_DATA__
}
Definition at line 45 of file driver_MAG3110.c.