driver_systick.c File Reference
driver_systick.c File Reference
Macros
#define SYST_CSR SysTick->CTRL
#define SYST_RVR SysTick->LOAD
#define SYST_CVR SysTick->VAL
Functions
void ARM_systick_enable (void)
void ARM_systick_start_ticks (int32 *pstart)
int32 ARM_systick_elapsed_ticks (int32 start_ticks)
void ARM_systick_delay_ms (uint32 iSystemCoreClock, uint32 delay_ms)
Macro Definition Documentation
#define SYST_CSR SysTick->CTRL
Definition at line 38 of file driver_systick.c.
Referenced by ARM_systick_enable().
#define SYST_CVR SysTick->VAL
Definition at line 40 of file driver_systick.c.
Referenced by ARM_systick_elapsed_ticks(), and ARM_systick_start_ticks().
#define SYST_RVR SysTick->LOAD
Definition at line 39 of file driver_systick.c.
Referenced by ARM_systick_elapsed_ticks(), and ARM_systick_enable().
Function Documentation
void ARM_systick_delay_ms (uint32 iSystemCoreClock, uint32 delay_ms)
Definition at line 75 of file driver_systick.c.
Referenced by initializeFusionEngine().
 {
     int32 istart_ticks; // start ticks on entry
     int32 ielapsed_ticks;   // elapsed ticks
     int16 i;        // loop counter
     // loop for requested number of ms
     for (i = 0; i < delay_ms; i++)
     {
         // loop until 1ms has elapsed
         ARM_systick_start_ticks(&istart_ticks);
         do
         {
             ielapsed_ticks = ARM_systick_elapsed_ticks(istart_ticks);
         } while (ielapsed_ticks < iSystemCoreClock / 1000);
     }
     return;
 }
int32 ARM_systick_elapsed_ticks (int32 start_ticks)
Definition at line 64 of file driver_systick.c.
Referenced by ARM_systick_delay_ms(), and fFuseSensors().
 {
     int32 elapsed_ticks;
     // subtract the stored start ticks and check for wraparound down through zero
     elapsed_ticks = start_ticks - (SYST_CVR & 0x00FFFFFF);
     if (elapsed_ticks < 0) elapsed_ticks += SYST_RVR;
     return elapsed_ticks;
 }
void ARM_systick_enable (void)
Definition at line 47 of file driver_systick.c.
Referenced by initializeFusionEngine().
 {
     SYST_CSR = 0x5u;        // enable systick from internal clock
     SYST_RVR = 0x00FFFFFFu; // set reload to maximum 24 bit value
     return;
 }
void ARM_systick_start_ticks (int32 * pstart)
Definition at line 55 of file driver_systick.c.
Referenced by ARM_systick_delay_ms(), and fFuseSensors().
 {
     // store the 24 bit systick timer
     *pstart = SYST_CVR & 0x00FFFFFF;
     return;
 }