drivers.h File Reference
drivers.h File Reference
Functions
SysTick Macros
The ARM SysTick counter is used to time various fusion options. Timings are then conveyed to the NXP Sensor Fusion Toolbox, where they are displayed for the developer. These functions should be portable to any ARM M0+, M3, M4 or M4F device. If you are using a different CPU architecture, you will need to provide an equivalent set of macros, remove the macro calls from the fusion routines, or define a set of empty macros.
void ARM_systick_enable (void)
void ARM_systick_start_ticks (int32_t *pstart)
int32_t ARM_systick_elapsed_ticks (int32_t start_ticks)
void ARM_systick_delay_ms (uint32_t iSystemCoreClock, uint32_t delay_ms)
Sensor Drivers
Each physical sensor must be provided with one initialization function and one "read" function. These must be installed by the user using the installSensor method defined in SensorFusionGlobals. By "physical sensor", we mean either individual sensor type (such as a 3-axis accelerometer) or a combo-sensor such as the NXP FXOS8700 6-axis accel plus mag. The init() function for each sensor is responsible for initializing all sensors contained in that package. The read() function is responsible for reading those same sensors and moving the results into the standard structures contained within the SensorFusionGlobals object.
int8_t MPL3115_Init (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t FXOS8700_Init (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t FXAS21002_Init (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t MMA8652_Init (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t FXLS8952_Init (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t MAG3110_Init (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t MMA8451_Init (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t FXLS8471Q_Init (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t MPL3115_Read (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t FXOS8700_Read (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t FXAS21002_Read (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t MMA8652_Read (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t FXLS8952_Read (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t MAG3110_Read (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t MMA8451_Read (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t FXLS8471Q_Read (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t MPL3115_Idle (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t FXOS8700_Idle (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t FXAS21002_Idle (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t MMA8652_Idle (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t FXLS8952_Idle (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t MAG3110_Idle (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t MMA8451_Idle (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
int8_t FXLS8471Q_Idle (PhysicalSensor *sensor, SensorFusionGlobals *sfg)
Detailed Description
Users who are not using NXP hardware will need to supply their own drivers in place of those defined here.
Definition in file drivers.h.
Function Documentation
void ARM_systick_delay_ms (uint32_t iSystemCoreClock, uint32_t delay_ms)
Definition at line 75 of file driver_systick.c.
Referenced by initializeFusionEngine().
 {
     int32 istart_ticks; // start ticks on entry
     int32 ielapsed_ticks;   // elapsed ticks
     int16 i;        // loop counter
     // loop for requested number of ms
     for (i = 0; i < delay_ms; i++)
     {
         // loop until 1ms has elapsed
         ARM_systick_start_ticks(&istart_ticks);
         do
         {
             ielapsed_ticks = ARM_systick_elapsed_ticks(istart_ticks);
         } while (ielapsed_ticks < iSystemCoreClock / 1000);
     }
     return;
 }
int32_t ARM_systick_elapsed_ticks (int32_t start_ticks)
Definition at line 64 of file driver_systick.c.
Referenced by ARM_systick_delay_ms(), and fFuseSensors().
 {
     int32 elapsed_ticks;
     // subtract the stored start ticks and check for wraparound down through zero
     elapsed_ticks = start_ticks - (SYST_CVR & 0x00FFFFFF);
     if (elapsed_ticks < 0) elapsed_ticks += SYST_RVR;
     return elapsed_ticks;
 }
void ARM_systick_enable (void)
Definition at line 47 of file driver_systick.c.
Referenced by initializeFusionEngine().
 {
     SYST_CSR = 0x5u;        // enable systick from internal clock
     SYST_RVR = 0x00FFFFFFu; // set reload to maximum 24 bit value
     return;
 }
void ARM_systick_start_ticks (int32_t * pstart)
Definition at line 55 of file driver_systick.c.
Referenced by ARM_systick_delay_ms(), and fFuseSensors().
 {
     // store the 24 bit systick timer
     *pstart = SYST_CVR & 0x00FFFFFF;
     return;
 }
int8_t FXAS21002_Idle (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
Referenced by fusion_task().
int8_t FXAS21002_Init (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
Referenced by fusion_task(), and main().
int8_t FXAS21002_Read (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
Referenced by main().
int8_t FXLS8471Q_Idle (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
Definition at line 234 of file driver_FXLS8471Q.c.
 {
     int32_t     status;
     if(sensor->isInitialized == F_USING_ACCEL) {
         if (sensor->addr == SPI_ADDR) {
             status = Sensor_SPI_Write(sensor->bus_driver, &(sensor->slaveParams), FXLS8471Q_IDLE );
         } else {
             status = Sensor_I2C_Write(sensor->bus_driver, sensor->addr, FXLS8471Q_IDLE );
         }
         sensor->isInitialized = 0;
         sfg->Accel.isEnabled = false;
     } else {
       return SENSOR_ERROR_INIT;
     }
     return status;
 }
int8_t FXLS8471Q_Init (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
Definition at line 135 of file driver_FXLS8471Q.c.
 {
     GENERIC_DRIVER_GPIO *pGPIODriver = &Driver_GPIO_KSDK;
     int32_t status;
     uint8_t reg;
     if (sensor->addr == SPI_ADDR) {
         // Initialize the Slave Select Pin.
         pGPIODriver->pin_init(&FXLS8471_SPI_CS, GPIO_DIRECTION_OUT, NULL, NULL, NULL);
         // Initialize SPI parameters used by ISSDK SPI routines
         sensor->slaveParams.pReadPreprocessFN  = FXLS8471Q_SPI_ReadPreprocess;
         sensor->slaveParams.pWritePreprocessFN = FXLS8471Q_SPI_WritePreprocess;
         sensor->slaveParams.pTargetSlavePinID = &FXLS8471_SPI_CS;
         sensor->slaveParams.spiCmdLen = FXLS8471Q_SPI_CMD_LEN;
         sensor->slaveParams.ssActiveValue = FXLS8471Q_SS_ACTIVE_VALUE;
         // Read the WhoAmI
         status = Register_SPI_Read(sensor->bus_driver, &(sensor->slaveParams), FXLS8471Q_WHO_AM_I, 1, &reg);
     } else {
         status = Register_I2C_Read(sensor->bus_driver, sensor->addr, FXLS8471Q_WHO_AM_I, 1, &reg);
     }
     if (status==SENSOR_ERROR_NONE) {
         sfg->Accel.iWhoAmI = reg;
         if (reg!=FXLS8471Q_WHO_AM_I_WHOAMI_VALUE) return(SENSOR_ERROR_INIT);
     } else {
        return(status);
     }
     // Configure and start the FXLS8471Q sensor.  This does multiple register writes
     if (sensor->addr == SPI_ADDR)
         status = Sensor_SPI_Write(sensor->bus_driver, &(sensor->slaveParams), FXLS8471Q_Initialization );
     else
         status = Sensor_I2C_Write(sensor->bus_driver, sensor->addr, FXLS8471Q_Initialization );
     // Stash some needed constants in the SF data structure for this sensor
     sfg->Accel.iCountsPerg = FXLS8471Q_COUNTSPERG;
     sfg->Accel.fgPerCount = 1.0F / FXLS8471Q_COUNTSPERG;
     sensor->isInitialized = F_USING_ACCEL;
     sfg->Accel.isEnabled = true;
     return (status);
 }
int8_t FXLS8471Q_Read (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
Definition at line 177 of file driver_FXLS8471Q.c.
 {
     uint8_t                     Data_Buffer[6 * FXLS8471Q_ACCEL_FIFO_SIZE];    // I2C read buffer
     int8_t                      status=0;       // I2C transaction status
     int8_t                      j;              // scratch
     uint16_t                     sensor_fifo_count = 1;
     int16_t                     sample[3];
     if(sensor->isInitialized != F_USING_ACCEL)
     {
         return SENSOR_ERROR_INIT;
     }
     // read the F_STATUS register (mapped to STATUS) and extract number of measurements available (lower 6 bits)
     if (sensor->addr == SPI_ADDR)
         status =  Sensor_SPI_Read(sensor->bus_driver, &(sensor->slaveParams), FXLS8471Q_F_STATUS_READ, Data_Buffer );
     else
         status =  Sensor_I2C_Read(sensor->bus_driver, sensor->addr, FXLS8471Q_F_STATUS_READ, Data_Buffer );
     sensor_fifo_count = Data_Buffer[0] & 0x3F;
     if (status==SENSOR_ERROR_NONE) {
         // return if there are no measurements in the sensor FIFO.
         // this will only occur when the FAST_LOOP_HZ equals or exceeds ACCEL_ODR_HZ
         if  (sensor_fifo_count == 0) return SENSOR_ERROR_READ;
     } else {
         return(status);
     }
     FXLS8471Q_DATA_READ->numBytes = 6 * sensor_fifo_count;
     if (sensor->addr == SPI_ADDR)
         status =  Sensor_SPI_Read(sensor->bus_driver, &sensor->slaveParams, FXLS8471Q_DATA_READ, &(Data_Buffer[0]) );
     else
         status =  Sensor_I2C_Read(sensor->bus_driver, sensor->addr, FXLS8471Q_DATA_READ, &(Data_Buffer[0]) );
     if (status==SENSOR_ERROR_NONE) {
         for (j=0; j<sensor_fifo_count; j++) {
             sample[CHX] = (Data_Buffer[6*j    ] << 8) | Data_Buffer[6*j + 1] ;
             sample[CHY] = (Data_Buffer[6*j + 2] << 8) | Data_Buffer[6*j + 3] ;
             sample[CHZ] = (Data_Buffer[6*j + 4] << 8) | Data_Buffer[6*j + 5] ;
             conditionSample(sample);  // truncate negative values to -32767
             addToFifo((FifoSensor*) &(sfg->Accel), ACCEL_FIFO_SIZE, sample);
         }
     }
     return (status);
 }
int8_t FXLS8952_Idle (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
int8_t FXLS8952_Init (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
Referenced by main().
int8_t FXLS8952_Read (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
Referenced by main().
int8_t FXOS8700_Idle (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
Definition at line 296 of file driver_FXOS8700.c.
 {
     int32_t     status;
     if(sensor->isInitialized == (F_USING_ACCEL|F_USING_MAG)) {
         status = Sensor_I2C_Write(sensor->bus_driver, sensor->addr, FXOS8700_FULL_IDLE );
         sensor->isInitialized = 0;
 #if F_USING_ACCEL
         sfg->Accel.isEnabled = false;
 #endif
 #if F_USING_MAG
         sfg->Mag.isEnabled = false;
 #endif
     } else {
       return SENSOR_ERROR_INIT;
     }
     return status;
 }
int8_t FXOS8700_Init (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
Definition at line 151 of file driver_FXOS8700.c.
Referenced by main().
 {
     int32_t status;
     uint8_t reg;
     status = Register_I2C_Read(sensor->bus_driver, sensor->addr, FXOS8700_WHO_AM_I, 1, &reg);
     if (status==SENSOR_ERROR_NONE) {
 #if F_USING_ACCEL
        sfg->Accel.iWhoAmI = reg;
        sfg->Accel.iCountsPerg = FXOS8700_COUNTSPERG;
        sfg->Accel.fgPerCount = 1.0F / FXOS8700_COUNTSPERG;
 #endif
 #if F_USING_MAG
        sfg->Mag.iWhoAmI = reg;
        sfg->Mag.iCountsPeruT = FXOS8700_COUNTSPERUT;
        sfg->Mag.fCountsPeruT = (float) FXOS8700_COUNTSPERUT;
        sfg->Mag.fuTPerCount = 1.0F / FXOS8700_COUNTSPERUT;
 #endif
        if (reg != FXOS8700_WHO_AM_I_PROD_VALUE) {
           return SENSOR_ERROR_INIT;  // The whoAmI did not match
        }
     } else {
         // whoAmI will rettain default value of zero
         // return with error
         return status;
     }
     // Configure and start the fxos8700 sensor.  This does multiple register writes
     // (see FXOS8700_Initialization definition above)
     status = Sensor_I2C_Write(sensor->bus_driver, sensor->addr, FXOS8700_Initialization );
     sensor->isInitialized = F_USING_ACCEL | F_USING_MAG;
 #if F_USING_ACCEL
     sfg->Accel.isEnabled = true;
 #endif
 #if F_USING_MAG
     sfg->Mag.isEnabled = true;
 #endif
     return (status);
 }
int8_t FXOS8700_Read (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
Definition at line 265 of file driver_FXOS8700.c.
Referenced by main().
 {
     int8_t  sts1 = 0;
     int8_t  sts2 = 0;
 #if F_USING_ACCEL
         sts1 = FXOS8700_ReadAccData(sensor, sfg);
 #endif
 #if F_USING_MAG
         sts2 = FXOS8700_ReadMagData(sensor, sfg);
 #endif
     if (sts1)
         return (sts1);
     else
         return (sts2);
 }
int8_t MAG3110_Idle (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
Definition at line 168 of file driver_MAG3110.c.
Referenced by fusion_task().
 {
     int32_t     status;
     if(sensor->isInitialized == F_USING_MAG) {
         status = Sensor_I2C_Write(sensor->bus_driver, sensor->addr, MAG3110_IDLE );
         sensor->isInitialized = 0;
         sfg->Mag.isEnabled = false;
     } else {
       return SENSOR_ERROR_INIT;
     }
     return status;
 }
int8_t MAG3110_Init (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
Definition at line 103 of file driver_MAG3110.c.
Referenced by fusion_task(), and main().
 {
     int32_t status;
     uint8_t reg;
     status = Register_I2C_Read(sensor->bus_driver, sensor->addr, MAG3110_WHO_AM_I, 1, &reg);
     if (status==SENSOR_ERROR_NONE) {
         sfg->Mag.iWhoAmI = reg;
         if (reg!=MAG3110_WHOAMI_VALUE) {
              return(SENSOR_ERROR_INIT);
         }
     } else {
         // iWhoAmI will return default value of zero
         // return with error
         return(SENSOR_ERROR_INIT);
     }
     // Configure and start the MAG3110 sensor.  This does multiple register writes
     // (see MAG3110_Initialization definition above)
     status = Sensor_I2C_Write(sensor->bus_driver, sensor->addr, MAG3110_Initialization );
     // Stash some needed constants in the SF data structure for this sensor
     sfg->Mag.iCountsPeruT = MAG3110_COUNTSPERUT;
     sfg->Mag.fCountsPeruT = (float)MAG3110_COUNTSPERUT; // IAR optimized this out without the #pragma before the function
     sfg->Mag.fuTPerCount = 1.0F / MAG3110_COUNTSPERUT;  // IAR optimized this out without the #pragma before the function
     sensor->isInitialized = F_USING_MAG;        // IAR optimized this out without the #pragma before the function
     sfg->Mag.isEnabled = true;                  // IAR optimized this out without the #pragma before the function
     return (status);
 }
int8_t MAG3110_Read (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
Definition at line 134 of file driver_MAG3110.c.
Referenced by main().
 {
     uint8_t                     I2C_Buffer[6];  // I2C read buffer
     int8_t                      status;         // I2C transaction status
     int16_t                     sample[3];      // Reconstructed sample
     if(sensor->isInitialized != F_USING_MAG)
     {
         return SENSOR_ERROR_INIT;
     }
     status =  Sensor_I2C_Read(sensor->bus_driver, sensor->addr, MAG3110_DATA_READ, I2C_Buffer );
     sample[CHX] = (I2C_Buffer[0] << 8) | I2C_Buffer[1];
     sample[CHY] = (I2C_Buffer[2] << 8) | I2C_Buffer[3];
     sample[CHZ] = (I2C_Buffer[4] << 8) | I2C_Buffer[5];
     if (status==SENSOR_ERROR_NONE) {
         conditionSample(sample);  // truncate negative values to -32767
         sample[CHZ] = -sample[CHZ];  // +Z should point up (MAG3110 Z positive is down)
         addToFifo((FifoSensor*) &(sfg->Mag), MAG_FIFO_SIZE, sample);
     }
     return (status);
 }
int8_t MMA8451_Idle (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
int8_t MMA8451_Init (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
int8_t MMA8451_Read (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
int8_t MMA8652_Idle (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
int8_t MMA8652_Init (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
int8_t MMA8652_Read (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
int8_t MPL3115_Idle (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
int8_t MPL3115_Init (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
Referenced by main().
int8_t MPL3115_Read (PhysicalSensor * sensor, SensorFusionGlobals * sfg)
Referenced by main().