hal_frdm_fxs_mult2_b.c File Reference
hal_frdm_fxs_mult2_b.c File Reference
Functions
void ApplyAccelHAL (AccelSensor *Accel)
void ApplyMagHAL (MagSensor *Mag)
void ApplyGyroHAL (GyroSensor *Gyro)
Function Documentation
void ApplyAccelHAL (AccelSensor * Accel)
Apply the accelerometer Hardware Abstraction Layer.
Parameters
Accel pointer to accelerometer logical sensor
Definition at line 44 of file hal_frdm_fxs_mult2_b.c.
Referenced by initializeSensors().
 {
     int8 i;             // loop counter
     // apply HAL to all measurements read from FIFO buffer
     for (i = 0; i < Accel->iFIFOCount; i++)
     {
         // apply HAL mapping to coordinate system used
 #if THISCOORDSYSTEM == NED
         int16 itmp16 = Accel->iGsFIFO[i][CHX];
         Accel->iGsFIFO[i][CHX] = Accel->iGsFIFO[i][CHY];
         Accel->iGsFIFO[i][CHY] = itmp16;
 #endif // NED
 #if THISCOORDSYSTEM == ANDROID
         Accel->iGsFIFO[i][CHX] = -Accel->iGsFIFO[i][CHX];
         Accel->iGsFIFO[i][CHY] = -Accel->iGsFIFO[i][CHY];
 #endif // Android
 #if (THISCOORDSYSTEM == WIN8)
         Accel->iGsFIFO[i][CHZ] = -Accel->iGsFIFO[i][CHZ];
 #endif // Win8
     } // end of loop over FIFO count
     return;
 }
void ApplyGyroHAL (GyroSensor * Gyro)
Apply the gyroscope Hardware Abstraction Layer.
Parameters
Gyro pointer to gyroscope logical sensor
Definition at line 99 of file hal_frdm_fxs_mult2_b.c.
Referenced by processMagData().
 {
     int8 i;             // loop counter
     // apply HAL to all measurements read from FIFO buffer
     for (i = 0; i < Gyro->iFIFOCount; i++)
     {
         // apply HAL mapping to coordinate system used
 #if THISCOORDSYSTEM == NED
         int16 itmp16 = Gyro->iYsFIFO[i][CHX];
         Gyro->iYsFIFO[i][CHX] = -Gyro->iYsFIFO[i][CHY];
         Gyro->iYsFIFO[i][CHY] = -itmp16;
         Gyro->iYsFIFO[i][CHZ] = -Gyro->iYsFIFO[i][CHZ];
 #endif // NED
 #if THISCOORDSYSTEM == ANDROID
         Gyro->iYsFIFO[i][CHX] = -Gyro->iYsFIFO[i][CHX];
         Gyro->iYsFIFO[i][CHY] = -Gyro->iYsFIFO[i][CHY];
 #endif // Android
 #if THISCOORDSYSTEM == WIN8
         Gyro->iYsFIFO[i][CHX] = -Gyro->iYsFIFO[i][CHX];
         Gyro->iYsFIFO[i][CHY] = -Gyro->iYsFIFO[i][CHY];
 #endif // Win8
     } // end of loop over FIFO count
     return;
 }
void ApplyMagHAL (MagSensor * Mag)
Apply the magnetometer Hardware Abstraction Layer.
Parameters
Mag pointer to magnetometer logical sensor
Definition at line 71 of file hal_frdm_fxs_mult2_b.c.
Referenced by processMagData().
 {
     int8 i;             // loop counter
     // apply HAL to all measurements read from FIFO buffer
     for (i = 0; i < Mag->iFIFOCount; i++)
     {
         // apply HAL mapping to coordinate system used
 #if THISCOORDSYSTEM == NED
         int16 itmp16 = Mag->iBsFIFO[i][CHX];
         Mag->iBsFIFO[i][CHX] = -Mag->iBsFIFO[i][CHY];
         Mag->iBsFIFO[i][CHY] = -itmp16;
         Mag->iBsFIFO[i][CHZ] = -Mag->iBsFIFO[i][CHZ];
 #endif // NED
 #if THISCOORDSYSTEM == ANDROID
         Mag->iBsFIFO[i][CHX] = -Mag->iBsFIFO[i][CHX];
         Mag->iBsFIFO[i][CHY] = -Mag->iBsFIFO[i][CHY];
 #endif // Android
 #if THISCOORDSYSTEM == WIN8
         Mag->iBsFIFO[i][CHX] = -Mag->iBsFIFO[i][CHX];
         Mag->iBsFIFO[i][CHY] = -Mag->iBsFIFO[i][CHY];
 #endif
     } // end of loop over FIFO count
     return;
 }