status.c File Reference
status.c File Reference
Macros
#define N 0x00
#define R 0x04
#define G 0x02
#define B 0x01
Functions
void ssSetLeds (int8_t RGB)
void ssSetStatusNow (StatusSubsystem *pStatus, fusion_status_t status)
void ssTest (StatusSubsystem *pStatus)
void ssQueueStatus (StatusSubsystem *pStatus, fusion_status_t status)
void ssUpdateStatus (StatusSubsystem *pStatus)
void ssSetStatus (StatusSubsystem *pStatus, fusion_status_t status)
void initializeStatusSubsystem (StatusSubsystem *pStatus)
Detailed Description
Applications may change how they choose to display status information. The default implementation here uses LEDs on NXP Freedom boards. You may swap out implementations as long as the "Required" methods and states are retained.
Definition in file status.c.
Macro Definition Documentation
#define B 0x01
Definition at line 50 of file status.c.
Referenced by ssSetLeds().
#define G 0x02
Definition at line 49 of file status.c.
Referenced by ssSetLeds(), and ssSetStatusNow().
#define N 0x00
Definition at line 47 of file status.c.
Referenced by ssSetStatusNow().
#define R 0x04
Definition at line 48 of file status.c.
Referenced by ssSetLeds(), and ssSetStatusNow().
Function Documentation
void initializeStatusSubsystem (StatusSubsystem * pStatus)
initializeStatusSubsystem() should be called once at startup to initialize the data structure and to put hardware into the proper state for communicating status.
Parameters
pStatus pointer to the status subsystem
Definition at line 185 of file status.c.
Referenced by main().
 {
     pStatus->set = ssSetStatus;
     pStatus->queue = ssQueueStatus;
     pStatus->update = ssUpdateStatus;
     pStatus->test = ssTest;
     pStatus->previous = OFF;
     pStatus->set(pStatus, OFF);
     pStatus->queue(pStatus, OFF);
     pStatus->toggle = false;
     /* Un-gate the port clocks */
     CLOCK_EnableClock(RED_LED.clockName);
     CLOCK_EnableClock(GREEN_LED.clockName);
     //CLOCK_EnableClock(BLUE_LED.clockName);
     /* Led pin mux Configuration */
     PORT_SetPinMux(BOARD_LED_RED_GPIO_PORT, BOARD_LED_RED_GPIO_PIN,
                    kPORT_MuxAsGpio);
     PORT_SetPinMux(BOARD_LED_GREEN_GPIO_PORT, BOARD_LED_GREEN_GPIO_PIN,
                    kPORT_MuxAsGpio);
     //PORT_SetPinMux(BOARD_LED_BLUE_GPIO_PORT, BOARD_LED_BLUE_GPIO_PIN,
     //               kPORT_MuxAsGpio);
     /* set initial values */
     LED_RED_INIT(LOGIC_LED_OFF);
     LED_GREEN_INIT(LOGIC_LED_OFF);
     //LED_BLUE_INIT(LOGIC_LED_OFF);
 }
void ssQueueStatus (StatusSubsystem * pStatus, fusion_status_t status)
Definition at line 164 of file status.c.
Referenced by initializeStatusSubsystem().
 {
     pStatus->next = status;
 }
void ssSetLeds (int8_t RGB)
Definition at line 53 of file status.c.
Referenced by ssSetStatusNow().
 {
     if (RGB & R)
         LED_RED_ON();
     else
         LED_RED_OFF();
     if (RGB & G)
         LED_GREEN_ON();
     else
         LED_GREEN_OFF();
     if (RGB & B)
         LED_BLUE_ON();
     else
         LED_BLUE_OFF();
 }
void ssSetStatus (StatusSubsystem * pStatus, fusion_status_t status)
Definition at line 177 of file status.c.
Referenced by initializeStatusSubsystem().
 {
     pStatus->next = status;
     ssUpdateStatus(pStatus);
 }
void ssSetStatusNow (StatusSubsystem * pStatus, fusion_status_t status)
Definition at line 70 of file status.c.
Referenced by ssTest(), and ssUpdateStatus().
 {
     pStatus->status = status;
     pStatus->next = status;
     uint8_t blink = false;
     uint8_t RGB = N;
     // This is where we actually change the visual indicator
     // We are not using the blue LED because it is not available on some
     // board combinations.
     switch (status)
     {
         case INITIALIZING:      // solid GREEN
             RGB = G;
             break;
         case NORMAL:            // blinking GREEN
             RGB = G;
             blink = true;
             break;
         case LOWPOWER:          // blinking YELLOW
             RGB = R|G;
             blink = true;
             break;
         case SOFT_FAULT:        // solid RED (usually momentary)
         case HARD_FAULT:        // solid RED
             RGB = R;
             break;
         default:                // default = off;
             RGB = N;
     }
     if ((!blink) | (status != pStatus->previous))
     {
         ssSetLeds(RGB);
         pStatus->toggle = true;
     }
     else
     {
         if (pStatus->toggle)
         {
             ssSetLeds(N);
         }
         else
         {
             ssSetLeds(RGB);
         }
         pStatus->toggle = !pStatus->toggle;
     }
     while (status == HARD_FAULT) ; // Never return on hard fault
     // while (status == SOFT_FAULT) ; // DEBUG ONLY Never return on soft fault
 }
void ssTest (StatusSubsystem * pStatus)
Definition at line 125 of file status.c.
Referenced by initializeStatusSubsystem().
 {
     switch (pStatus->status)
     {
         case OFF:
             ssSetStatusNow(pStatus, INITIALIZING);
             break;
         case INITIALIZING:
             ssSetStatusNow(pStatus, LOWPOWER);
             break;
         case LOWPOWER:
             ssSetStatusNow(pStatus, NORMAL);
             break;
         case NORMAL:
             ssSetStatusNow(pStatus, RECEIVING_WIRED);
             break;
         case RECEIVING_WIRED:
             ssSetStatusNow(pStatus, RECEIVING_WIRELESS);
             break;
         case RECEIVING_WIRELESS:
             ssSetStatusNow(pStatus, SOFT_FAULT);
             break;
         case SOFT_FAULT:
             ssSetStatusNow(pStatus, HARD_FAULT);
             break;
         case HARD_FAULT:
             ssSetStatusNow(pStatus, OFF);
             break;
     }
 }
void ssUpdateStatus (StatusSubsystem * pStatus)
Definition at line 170 of file status.c.
Referenced by initializeStatusSubsystem(), and ssSetStatus().
 {
     pStatus->previous = pStatus->status;
     ssSetStatusNow(pStatus, pStatus->next);
 }