/*
 * Copyright 2023 NXP
 *
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef ___MCUXCLPSADRIVER_ORACLE_INTERFACE_BUILTIN_KEY_ID_H__
#define ___MCUXCLPSADRIVER_ORACLE_INTERFACE_BUILTIN_KEY_ID_H__

#define TFM_BUILTIN_KEY_ID_EL2GO_CONN_AUTH 0x7FFF816Cu

#endif /* ___MCUXCLPSADRIVER_ORACLE_INTERFACE_BUILTIN_KEY_ID_H__ */
