#Description: Driver wm8960; user_visible: True
include_guard(GLOBAL)
message("driver_wm8960 component is included.")

target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/fsl_wm8960.c
)

target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
    ${CMAKE_CURRENT_LIST_DIR}/.
)

#OR Logic component
if(${MCUX_DEVICE} STREQUAL "MIMXRT1062")
    include(component_codec_i2c_MIMXRT1062)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1042")
    include(component_codec_i2c_MIMXRT1042)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1176_cm4")
    include(component_codec_i2c_MIMXRT1176_cm4)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1173_cm4")
    include(component_codec_i2c_MIMXRT1176_cm4)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1175_cm4")
    include(component_codec_i2c_MIMXRT1176_cm4)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1176_cm7")
    include(component_codec_i2c_MIMXRT1176_cm7)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1171_cm7")
    include(component_codec_i2c_MIMXRT1176_cm7)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1173_cm7")
    include(component_codec_i2c_MIMXRT1176_cm7)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1172_cm7")
    include(component_codec_i2c_MIMXRT1176_cm7)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1175_cm7")
    include(component_codec_i2c_MIMXRT1176_cm7)
endif()
if(${MCUX_DEVICE} STREQUAL "MCIMX7U5")
    include(component_codec_i2c_MCIMX7U5)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1024")
    include(component_codec_i2c_MIMXRT1024)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1011")
    include(component_codec_i2c_MIMXRT1011)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8ML8")
    include(component_codec_i2c_MIMX8ML8)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1015")
    include(component_codec_i2c_MIMXRT1015)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8QM6_cm4_core0")
    include(component_codec_i2c_MIMX8QM6_cm4_core0)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8QM6_cm4_core1")
    include(component_codec_i2c_MIMX8QM6_cm4_core1)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8QX6")
    include(component_codec_i2c_MIMX8QX6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8UX6")
    include(component_codec_i2c_MIMX8QX6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8UX5")
    include(component_codec_i2c_MIMX8QX6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8QX2")
    include(component_codec_i2c_MIMX8QX6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8QX3")
    include(component_codec_i2c_MIMX8QX6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8QX5")
    include(component_codec_i2c_MIMX8QX6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8QX4")
    include(component_codec_i2c_MIMX8QX6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8DX4")
    include(component_codec_i2c_MIMX8QX6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8DX2")
    include(component_codec_i2c_MIMX8QX6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8QX1")
    include(component_codec_i2c_MIMX8QX6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8DX3")
    include(component_codec_i2c_MIMX8QX6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8DX6")
    include(component_codec_i2c_MIMX8QX6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8DX5")
    include(component_codec_i2c_MIMX8QX6)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMX8DX1")
    include(component_codec_i2c_MIMX8QX6)
endif()

