/*
 * Copyright 2021-2022 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v12.0
processor: MIMXRT1042xxxxB
package_id: MIMXRT1042XJM5B
mcu_data: ksdk2_0
processor_version: 0.12.11
board: MIMXRT1040-EVK
expansion_headers:
- id: single_row_arduino
  name: Arduino UNO R3 Compatible Header
  connectors:
  - id: C1
    name: J16
    pins:
    - {id: 1, name: D0, pin_num: M6, pin_signal: GPIO_SD_B1_01}
    - {id: 2, name: D1, pin_num: L6, pin_signal: GPIO_SD_B1_00}
    - {id: 3, name: D2, pin_num: H11, pin_signal: GPIO_AD_B0_11}
    - {id: 4, name: D3, pin_num: K5, pin_signal: GPIO_SD_B1_02}
    - {id: 5, name: D4, pin_num: G12, pin_signal: GPIO_AD_B0_09}
    - {id: 6, name: D5, pin_num: G10, pin_signal: GPIO_AD_B0_10}
    - {id: 7, name: D6, pin_num: K11, pin_signal: GPIO_AD_B1_02}
    - {id: 8, name: D7, pin_num: L12, pin_signal: GPIO_AD_B1_03}
  - id: C2
    name: J17
    pins:
    - {id: 1, name: D8, pin_num: E13, pin_signal: GPIO_B1_14}
    - {id: 2, name: D9, pin_num: D13, pin_signal: GPIO_B1_15}
    - {id: 3, name: D10, pin_num: K3, pin_signal: GPIO_SD_B0_01}
    - {id: 4, name: D11, pin_num: J3, pin_signal: GPIO_SD_B0_02}
    - {id: 5, name: D12, pin_num: J2, pin_signal: GPIO_SD_B0_03}
    - {id: 6, name: D13, pin_num: H3, pin_signal: GPIO_SD_B0_00}
    - {id: 7, name: GND, external_signal_types: ground}
    - {id: 8, name: AREF, external_signal_types: aref}
    - {id: 9, name: D14, pin_num: K12, pin_signal: GPIO_AD_B1_01}
    - {id: 10, name: D15, pin_num: H9, pin_signal: GPIO_AD_B1_00}
  - id: C3
    name: J32
    pins:
    - {id: 2, name: 3.3V, external_signal_types: power_supply_3.3V}
    - {id: 3, name: 3.3V, external_signal_types: power_supply_3.3V}
    - {id: 4, name: 3.3V, external_signal_types: power_supply_3.3V}
    - {id: 5, name: 5V, external_signal_types: power_supply_5V}
    - {id: 6, name: GND, external_signal_types: ground}
    - {id: 7, name: GND, external_signal_types: ground}
    - {id: 8, name: 5V, external_signal_types: power_supply_5V}
  - id: C4
    name: J33
    pins:
    - {id: 1, name: A0, pin_num: J13, pin_signal: GPIO_AD_B0_14}
    - {id: 2, name: A1, pin_num: K10, pin_signal: GPIO_AD_B0_15}
    - {id: 3, name: A2, pin_num: L13, pin_signal: GPIO_AD_B1_04}
    - {id: 4, name: A3, pin_num: K13, pin_signal: GPIO_AD_B1_05}
    - {id: 5, name: A4, pin_num: H10, pin_signal: GPIO_AD_B1_06}
    - {id: 6, name: A5, pin_num: J10, pin_signal: GPIO_AD_B1_07}
pin_labels:
- {pin_num: E3, pin_signal: GPIO_EMC_00, label: 'SEMC_D0/U16[2]', identifier: SEMC_D0}
- {pin_num: F3, pin_signal: GPIO_EMC_01, label: 'SEMC_D1/U16[4]', identifier: SEMC_D1}
- {pin_num: F2, pin_signal: GPIO_EMC_02, label: 'SEMC_D2/U16[5]', identifier: SEMC_D2}
- {pin_num: H4, pin_signal: GPIO_EMC_04, label: 'SEMC_D4/U16[8]', identifier: SEMC_D4}
- {pin_num: F4, pin_signal: GPIO_EMC_03, label: 'SEMC_D3/U16[7]', identifier: SEMC_D3}
- {pin_num: G3, pin_signal: GPIO_EMC_05, label: 'SEMC_D5/U16[10]', identifier: SEMC_D5}
- {pin_num: G4, pin_signal: GPIO_EMC_06, label: 'SEMC_D6/U16[11]', identifier: SEMC_D6}
- {pin_num: G5, pin_signal: GPIO_EMC_07, label: 'SEMC_D7/U16[13]', identifier: SEMC_D7}
- {pin_num: H1, pin_signal: GPIO_EMC_08, label: 'SEMC_DM0/U16[15]', identifier: SEMC_DM0}
- {pin_num: C1, pin_signal: GPIO_EMC_09, label: 'SEMC_A0/U16[23]', identifier: SEMC_A0}
- {pin_num: G1, pin_signal: GPIO_EMC_10, label: 'SEMC_A1/U16[24]', identifier: SEMC_A1}
- {pin_num: G2, pin_signal: GPIO_EMC_11, label: 'SEMC_A2/U16[25]', identifier: SEMC_A2}
- {pin_num: H5, pin_signal: GPIO_EMC_12, label: 'SEMC_A3/U16[26]', identifier: SEMC_A3}
- {pin_num: A6, pin_signal: GPIO_EMC_13, label: 'SEMC_A4/U16[29]', identifier: SEMC_A4}
- {pin_num: A7, pin_signal: GPIO_EMC_14, label: 'SEMC_A5/U16[30]', identifier: SEMC_A5}
- {pin_num: C2, pin_signal: GPIO_EMC_15, label: 'SEMC_A6/U16[31]', identifier: SEMC_A6}
- {pin_num: A5, pin_signal: GPIO_EMC_16, label: 'SEMC_A7/U16[32]', identifier: SEMC_A7}
- {pin_num: A4, pin_signal: GPIO_EMC_17, label: 'SEMC_A8/U16[33]', identifier: SEMC_A8}
- {pin_num: D3, pin_signal: GPIO_EMC_18, label: 'SEMC_A9/U16[34]', identifier: SEMC_A9}
- {pin_num: A3, pin_signal: GPIO_EMC_19, label: 'SEMC_A11/U16[35]', identifier: SEMC_A11}
- {pin_num: H2, pin_signal: GPIO_EMC_23, label: 'SEMC_A10/U16[22]', identifier: SEMC_A10}
- {pin_num: A2, pin_signal: GPIO_EMC_20, label: 'SEMC_A12/U16[36]', identifier: SEMC_A12}
- {pin_num: E2, pin_signal: GPIO_EMC_21, label: 'SEMC_BA0/U16[20]', identifier: SEMC_BA0}
- {pin_num: F1, pin_signal: GPIO_EMC_22, label: 'SEMC_BA1/U16[21]', identifier: SEMC_BA1}
- {pin_num: D2, pin_signal: GPIO_EMC_24, label: 'SEMC_CAS/U16[17]', identifier: SEMC_CAS}
- {pin_num: D1, pin_signal: GPIO_EMC_25, label: 'SEMC_RAS/U16[18]', identifier: SEMC_RAS}
- {pin_num: B2, pin_signal: GPIO_EMC_26, label: 'SEMC_CLK/U16[38]', identifier: SEMC_CLK}
- {pin_num: C3, pin_signal: GPIO_EMC_27, label: 'SEMC_CKE/U16[37]', identifier: SEMC_CKE}
- {pin_num: B1, pin_signal: GPIO_EMC_28, label: 'SEMC_WE/U16[16]', identifier: SEMC_WE}
- {pin_num: E1, pin_signal: GPIO_EMC_29, label: 'SEMC_CS0/U16[19]', identifier: SEMC_CS0}
- {pin_num: B7, pin_signal: GPIO_EMC_30, label: 'SEMC_D8/U16[42]', identifier: SEMC_D8}
- {pin_num: C5, pin_signal: GPIO_EMC_31, label: 'SEMC_D9/U16[44]', identifier: SEMC_D9}
- {pin_num: D5, pin_signal: GPIO_EMC_32, label: 'SEMC_D10/U16[45]', identifier: SEMC_D10}
- {pin_num: D4, pin_signal: GPIO_EMC_33, label: 'SEMC_D11/U16[47]', identifier: SEMC_D11}
- {pin_num: B4, pin_signal: GPIO_EMC_34, label: 'SEMC_D12/U16[48]', identifier: SEMC_D12}
- {pin_num: C4, pin_signal: GPIO_EMC_35, label: 'SEMC_D13/U16[50]', identifier: SEMC_D13}
- {pin_num: B3, pin_signal: GPIO_EMC_36, label: 'SEMC_D14/U16[51]', identifier: SEMC_D14}
- {pin_num: E5, pin_signal: GPIO_EMC_37, label: 'SEMC_D15/U16[53]', identifier: SEMC_D15}
- {pin_num: B6, pin_signal: GPIO_EMC_38, label: 'SEMC_DM1/U16[39]', identifier: SEMC_DM1}
- {pin_num: C6, pin_signal: GPIO_EMC_39, label: SEMC_DQS, identifier: SEMC_DQS}
- {pin_num: C7, pin_signal: GPIO_EMC_40, label: 'ENET_MDC/U18[12]', identifier: ENET_MDC}
- {pin_num: D6, pin_signal: GPIO_EMC_41, label: 'ENET_MDIO/U18[11]', identifier: ENET_MDIO}
- {pin_num: D7, pin_signal: GPIO_B0_00, label: 'LCDIF_CLK/J49[A30]', identifier: LCDIF_CLK}
- {pin_num: D8, pin_signal: GPIO_B0_01, label: 'LCDIF_ENABLE/J49[A34]', identifier: LCDIF_ENABLE}
- {pin_num: E8, pin_signal: GPIO_B0_02, label: 'LCDIF_HSYNC/J49[A32]', identifier: LCDIF_HSYNC}
- {pin_num: E7, pin_signal: GPIO_B0_03, label: 'LCDIF_VSYNC/J49[A33]', identifier: LCDIF_VSYNC}
- {pin_num: C8, pin_signal: GPIO_B0_04, label: 'LCDIF_D0/J49[A24]/BT_CFG[0]', identifier: LCDIF_D0}
- {pin_num: A8, pin_signal: GPIO_B0_05, label: 'LCDIF_D1/J49[A25]/BT_CFG[1]', identifier: LCDIF_D1}
- {pin_num: B8, pin_signal: GPIO_B0_06, label: 'LCDIF_D2/J49[A26]/BT_CFG[2]', identifier: LCDIF_D2}
- {pin_num: A9, pin_signal: GPIO_B0_07, label: 'LCDIF_D3/J49[A27]/BT_CFG[3]', identifier: LCDIF_D3}
- {pin_num: A10, pin_signal: GPIO_B0_08, label: 'LCDIF_D4/J49[A28]/BT_CFG[4]', identifier: LCDIF_D4}
- {pin_num: C9, pin_signal: GPIO_B0_09, label: 'LCDIF_D5/J49[A15]/BT_CFG[5]', identifier: LCDIF_D5}
- {pin_num: D9, pin_signal: GPIO_B0_10, label: 'LCDIF_D6/J49[A16]/BT_CFG[6]', identifier: LCDIF_D6}
- {pin_num: B9, pin_signal: GPIO_B0_11, label: 'LCDIF_D7/J49[A17]/BT_CFG[7]', identifier: LCDIF_D7}
- {pin_num: D10, pin_signal: GPIO_B0_12, label: 'LCDIF_D8/J49[A18]/BT_CFG[8]', identifier: LCDIF_D8}
- {pin_num: C10, pin_signal: GPIO_B0_13, label: 'LCDIF_D9/J49[A19]/BT_CFG[9]', identifier: LCDIF_D9}
- {pin_num: C11, pin_signal: GPIO_B0_14, label: 'LCDIF_D10/J49[A20]/BT_CFG[10]', identifier: LCDIF_D10}
- {pin_num: D11, pin_signal: GPIO_B0_15, label: 'LCDIF_D11/J49[A8]/BT_CFG[11]', identifier: LCDIF_D11}
- {pin_num: A11, pin_signal: GPIO_B1_00, label: 'LCDIF_D12/J49[A9]', identifier: LCDIF_D12}
- {pin_num: A12, pin_signal: GPIO_B1_01, label: 'LCDIF_D13/J49[A10]', identifier: LCDIF_D13}
- {pin_num: E12, pin_signal: GPIO_B1_02, label: 'LCDIF_D14/J49[A11]', identifier: LCDIF_D14}
- {pin_num: E10, pin_signal: GPIO_B1_03, label: 'LCDIF_D15/J49[A12]', identifier: LCDIF_D15}
- {pin_num: F10, pin_signal: GPIO_B1_04, label: 'ENET_RXD0/U18[16]', identifier: ENET_RXD0}
- {pin_num: E11, pin_signal: GPIO_B1_05, label: 'ENET_RXD1/U18[15]', identifier: ENET_RXD1}
- {pin_num: C13, pin_signal: GPIO_B1_06, label: 'ENET_CRS_DV/U18[18]', identifier: ENET_CRS_DV}
- {pin_num: B12, pin_signal: GPIO_B1_07, label: 'ENET_TXD0/U18[24]', identifier: ENET_TXD0}
- {pin_num: B11, pin_signal: GPIO_B1_08, label: 'ENET_TXD1/U18[25]', identifier: ENET_TXD1}
- {pin_num: B13, pin_signal: GPIO_B1_09, label: 'ENET_TXEN/U18[23]', identifier: ENET_TXEN}
- {pin_num: C12, pin_signal: GPIO_B1_10, label: 'ENET_TX_REF_CLK/U18[9]', identifier: ENET_TX_REF_CLK}
- {pin_num: D12, pin_signal: GPIO_B1_11, label: 'ENET_RXER/U18[20]', identifier: ENET_RXER}
- {pin_num: F13, pin_signal: GPIO_B1_12, label: 'SD_CD_SW/J22[9]', identifier: SD_CD_SW}
- {pin_num: F12, pin_signal: GPIO_B1_13, label: 'WDOG_B/U27[3]', identifier: WDOG_B}
- {pin_num: E13, pin_signal: GPIO_B1_14, label: 'SD0_VSELECT/J17[1]', identifier: SD0_VSELECT}
- {pin_num: D13, pin_signal: GPIO_B1_15, label: 'BACKLIGHT_CTL/J17[2]/U14[4]', identifier: BACKLIGHT_CTL}
- {pin_num: F11, pin_signal: GPIO_AD_B0_04, label: 'BT_PCM_SYNC/U9[8]/U10[16]/BOOT_MODE[0]', identifier: BT_PCM_SYNC}
- {pin_num: H12, pin_signal: GPIO_AD_B0_05, label: 'BT_PCM_BCLK/U9[7]/U10[17]/CAN_STBY/U23[8]/BOOT_MODE[1]', identifier: CAN_STBY}
- {pin_num: G13, pin_signal: GPIO_AD_B0_06, label: 'JTAG_TMS/J2[7]/SWD_DIO/J10[2]'}
- {pin_num: H13, pin_signal: GPIO_AD_B0_07, label: 'JTAG_TCK/J2[9]/SWD_CLK/J9[2]'}
- {pin_num: G11, pin_signal: GPIO_AD_B0_08, label: 'JTAG_MOD/BT_PCM_RXD/U10[18]/USER_LED'}
- {pin_num: G12, pin_signal: GPIO_AD_B0_09, label: 'J16[5]/JTAG_TDI/J2[5]/J4[2]/BT_PCM_TXD/U9[6]'}
- {pin_num: G10, pin_signal: GPIO_AD_B0_10, label: 'J16[6]/JTAG_TDO/J2[13]/J3[2]/INT1_COMBO/U66[8]/ENET_INT/U18[21]', identifier: INT1_COMBO}
- {pin_num: H11, pin_signal: GPIO_AD_B0_11, label: 'J16[3]/JTAG_nTRST/J2[3]/INT2_COMBO/U66[6]/LCD_TOUCH_INT/J49[B3]', identifier: INT2_COMBO}
- {pin_num: J12, pin_signal: GPIO_AD_B0_12, label: 'UART1_TXD/J13[2]', identifier: UART1_TXD}
- {pin_num: J11, pin_signal: GPIO_AD_B0_13, label: 'UART1_RXD/J11[2]', identifier: UART1_RXD}
- {pin_num: J13, pin_signal: GPIO_AD_B0_14, label: 'J33[1]/CAN2_TX/U23[1]', identifier: CAN2_TX}
- {pin_num: K10, pin_signal: GPIO_AD_B0_15, label: 'J33[2]/CAN2_RX/U23[4]', identifier: CAN2_RX}
- {pin_num: H9, pin_signal: GPIO_AD_B1_00, label: 'J17[10]/I2C1_SCL/J49[B4]/U25[17]', identifier: I2C1_SCL}
- {pin_num: K12, pin_signal: GPIO_AD_B1_01, label: 'J17[9]/I2C1_SDA/J49[B5]/U25[18]', identifier: I2C1_SDA}
- {pin_num: K11, pin_signal: GPIO_AD_B1_02, label: 'J16[7]/SPDIF_OUT/SDIO0_SD1_SEL/U63[9]/U64[9]/U65[9]', identifier: SPDIF_OUT}
- {pin_num: L12, pin_signal: GPIO_AD_B1_03, label: 'J16[8]/SPDIF_IN/J20[1]/LCD_RST/J49[B2]', identifier: SPDIF_IN}
- {pin_num: L13, pin_signal: GPIO_AD_B1_04, label: 'J33[3]/SD_PWREN/Q5[1]', identifier: SD_PWREN}
- {pin_num: K13, pin_signal: GPIO_AD_B1_05, label: 'J33[4]/PERI_PWREN/Q3[1]', identifier: PERI_PWREN}
- {pin_num: H10, pin_signal: GPIO_AD_B1_06, label: 'J33[5]/I2C3_SDA/J23[15]/J24[5]/U66[4]', identifier: I2C3_SDA}
- {pin_num: J10, pin_signal: GPIO_AD_B1_07, label: 'J33[6]/I2C3_SCL/J23[13]/J24[3]/U66[5]', identifier: I2C3_SCL}
- {pin_num: H3, pin_signal: GPIO_SD_B0_00, label: 'J17[6]/U63[8]', identifier: GPIO_SD_B0_00}
- {pin_num: K3, pin_signal: GPIO_SD_B0_01, label: 'J17[3]/U63[7]', identifier: GPIO_SD_B0_01}
- {pin_num: J3, pin_signal: GPIO_SD_B0_02, label: 'J17[4]/U64[8]', identifier: GPIO_SD_B0_02}
- {pin_num: J2, pin_signal: GPIO_SD_B0_03, label: 'J17[5]/U64[7]', identifier: GPIO_SD_B0_03}
- {pin_num: J4, pin_signal: GPIO_SD_B0_04, label: 'U65[8]', identifier: GPIO_SD_B0_04}
- {pin_num: J1, pin_signal: GPIO_SD_B0_05, label: 'U65[7]', identifier: GPIO_SD_B0_05}
- {pin_num: L6, pin_signal: GPIO_SD_B1_00, label: 'J16[2]/USB_OTG1_PWR/U30[A1]/BT_DEV_WAKE/U9[9]', identifier: USB_OTG1_PWR}
- {pin_num: M6, pin_signal: GPIO_SD_B1_01, label: 'J16[1]/USB_OTG1_ID/U30[A1]/WL_DEV_WAKE/U9[10]', identifier: USB_OTG1_ID}
- {pin_num: K5, pin_signal: GPIO_SD_B1_02, label: 'J16[4]/USB_OTG1_OC/U30[A2]/WL_RST#/J8[56]', identifier: USB_OTG1_OC}
- {pin_num: N3, pin_signal: GPIO_SD_B1_03, label: 'BT_RST#/J8[54]', identifier: BT_RST#}
- {pin_num: N2, pin_signal: GPIO_SD_B1_04, label: 'WIFI_RST_B/U9[3]', identifier: WIFI_EST_B}
- {pin_num: M4, pin_signal: GPIO_SD_B1_05, label: FlexSPI_DQS, identifier: FlexSPI_DQS}
- {pin_num: M5, pin_signal: GPIO_SD_B1_06, label: 'FlexSPI_SS0/U24[1]', identifier: FlexSPI_SS0}
- {pin_num: L4, pin_signal: GPIO_SD_B1_07, label: 'FlexSPI_CLK/U24[6]', identifier: FlexSPI_CLK}
- {pin_num: N4, pin_signal: GPIO_SD_B1_08, label: 'FlexSPI_D0_A/U24[5]', identifier: FlexSPI_D0_A}
- {pin_num: K6, pin_signal: GPIO_SD_B1_09, label: 'FlexSPI_D1_A/U24[2]', identifier: FlexSPI_D1_A}
- {pin_num: N5, pin_signal: GPIO_SD_B1_10, label: 'FlexSPI_D2_A/U24[3]', identifier: FlexSPI_D2_A}
- {pin_num: N6, pin_signal: GPIO_SD_B1_11, label: 'FlexSPI_D3_A/U24[7]', identifier: FlexSPI_D3_A}
- {pin_num: M7, pin_signal: USB_OTG1_DN, label: OTG1_DN, identifier: OTG1_DN}
- {pin_num: N7, pin_signal: USB_OTG1_DP, label: OTG1_DP, identifier: OTG1_DP}
- {pin_num: L7, pin_signal: VDD_USB_CAP, label: VDD_USB_3V}
- {pin_num: N8, pin_signal: USB_OTG1_VBUS, label: 5V_USB_OTG}
- {pin_num: K7, pin_signal: POR_B, label: 'POR_B/J28[1]/RST_TGTMCU_B/J5[1]', identifier: POR_B}
- {pin_num: A1, pin_signal: VSS0, label: GND}
- {pin_num: N1, pin_signal: VSS1, label: GND}
- {pin_num: E4, pin_signal: VSS2, label: GND}
- {pin_num: B5, pin_signal: VSS3, label: GND}
- {pin_num: G7, pin_signal: VSS4, label: GND}
- {pin_num: H7, pin_signal: VSS5, label: GND}
- {pin_num: H8, pin_signal: VSS6, label: GND}
- {pin_num: M8, pin_signal: VSS7, label: GND}
- {pin_num: K9, pin_signal: VSS8, label: GND}
- {pin_num: B10, pin_signal: VSS9, label: GND}
- {pin_num: L11, pin_signal: VSS10, label: GND}
- {pin_num: A13, pin_signal: VSS11, label: GND}
- {pin_num: N13, pin_signal: VSS12, label: GND}
- {pin_num: K1, pin_signal: DCDC_IN0, label: DCDC_IN_1}
- {pin_num: L1, pin_signal: DCDC_LP0, label: DCDC_LP_1}
- {pin_num: M1, pin_signal: DCDC_GND0, label: DCDC_GND_1}
- {pin_num: K2, pin_signal: DCDC_IN1, label: DCDC_IN_2}
- {pin_num: L2, pin_signal: DCDC_LP1, label: DCDC_LP_2}
- {pin_num: M2, pin_signal: DCDC_GND1, label: DCDC_GND_2}
- {pin_num: L3, pin_signal: DCDC_IN_Q, label: DCDC_IN_Q}
- {pin_num: M3, pin_signal: DCDC_PSWITCH, label: DCDC_PSWITCH}
- {pin_num: K4, pin_signal: DCDC_SENSE, label: DCDC_SENSE}
- {pin_num: F5, pin_signal: NVCC_EMC0, label: NVCC_EMC_2}
- {pin_num: J5, pin_signal: NVCC_SD0, label: NVCC_SD0}
- {pin_num: L5, pin_signal: NVCC_SD1, label: NVCC_SD1}
- {pin_num: E6, pin_signal: NVCC_EMC1, label: NVCC_EMC_1}
- {pin_num: F6, pin_signal: VDD_SOC_IN0, label: VDD_SOC_IN_2}
- {pin_num: G6, pin_signal: VDD_SOC_IN1, label: VDD_SOC_IN_6}
- {pin_num: J6, pin_signal: ONOFF, label: ONOFF}
- {pin_num: H6, pin_signal: VDD_SOC_IN2, label: VDD_SOC_IN_7}
- {pin_num: F7, pin_signal: VDD_SOC_IN3, label: VDD_SOC_IN_3}
- {pin_num: J7, pin_signal: TEST_MODE, label: GND}
- {pin_num: F8, pin_signal: VDD_SOC_IN4, label: VDD_SOC_IN_4}
- {pin_num: G8, pin_signal: NVCC_GPIO0, label: NVCC_GPIO_1}
- {pin_num: J8, pin_signal: PMIC_ON_REQ, label: 'PMIC_ON_REQ/U29[8]'}
- {pin_num: K8, pin_signal: VDD_SNVS_IN, label: 'VDD_SNVS_IN/J30[2]'}
- {pin_num: L8, pin_signal: NGND_KEL0, label: GND}
- {pin_num: E9, pin_signal: VDD_SOC_IN5, label: VDD_SOC_IN_1}
- {pin_num: F9, pin_signal: VDD_SOC_IN6, label: VDD_SOC_IN_5}
- {pin_num: G9, pin_signal: NVCC_GPIO1, label: NVCC_GPIO_2}
- {pin_num: J9, pin_signal: WAKEUP, label: USER_BUTTON}
- {pin_num: L9, pin_signal: VDD_SNVS_CAP, label: VDD_SNVS_CAP}
- {pin_num: M9, pin_signal: RTC_XTALI, label: RTC_XTALI}
- {pin_num: N9, pin_signal: RTC_XTALO, label: RTC_XTALO}
- {pin_num: M10, pin_signal: GPANAIO, label: GPANAIO}
- {pin_num: L10, pin_signal: USB_OTG1_CHD_B, label: USB_OTG1_CHD_B}
- {pin_num: N10, pin_signal: VDD_HIGH_CAP, label: VDD_HIGH_CAP}
- {pin_num: M11, pin_signal: XTALO, label: XTALO}
- {pin_num: N11, pin_signal: XTALI, label: XTALI}
- {pin_num: M12, pin_signal: VDDA_ADC_3P3, label: VDDA_ADC_3P3_MCU}
- {pin_num: N12, pin_signal: NVCC_PLL, label: NVCC_PLL}
- {pin_num: M13, pin_signal: VDD_HIGH_IN, label: VDD_HIGH_IN_MCU}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
    BOARD_InitDEBUG_UARTPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDEBUG_UARTPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: J12, peripheral: LPUART1, signal: TX, pin_signal: GPIO_AD_B0_12, software_input_on: Disable, hysteresis_enable: Disable, pull_up_down_config: Pull_Down_100K_Ohm,
    pull_keeper_select: Keeper, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: J11, peripheral: LPUART1, signal: RX, pin_signal: GPIO_AD_B0_13, software_input_on: Disable, hysteresis_enable: Disable, pull_up_down_config: Pull_Down_100K_Ohm,
    pull_keeper_select: Keeper, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDEBUG_UARTPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitDEBUG_UARTPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_12_LPUART1_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_13_LPUART1_RX, 0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_12_LPUART1_TX, 0x10B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_13_LPUART1_RX, 0x10B0U); 
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSDRAMPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: C1, peripheral: SEMC, signal: 'ADDR, 00', pin_signal: GPIO_EMC_09}
  - {pin_num: G1, peripheral: SEMC, signal: 'ADDR, 01', pin_signal: GPIO_EMC_10}
  - {pin_num: G2, peripheral: SEMC, signal: 'ADDR, 02', pin_signal: GPIO_EMC_11}
  - {pin_num: H5, peripheral: SEMC, signal: 'ADDR, 03', pin_signal: GPIO_EMC_12}
  - {pin_num: A6, peripheral: SEMC, signal: 'ADDR, 04', pin_signal: GPIO_EMC_13}
  - {pin_num: A7, peripheral: SEMC, signal: 'ADDR, 05', pin_signal: GPIO_EMC_14}
  - {pin_num: C2, peripheral: SEMC, signal: 'ADDR, 06', pin_signal: GPIO_EMC_15}
  - {pin_num: A5, peripheral: SEMC, signal: 'ADDR, 07', pin_signal: GPIO_EMC_16}
  - {pin_num: A4, peripheral: SEMC, signal: 'ADDR, 08', pin_signal: GPIO_EMC_17}
  - {pin_num: D3, peripheral: SEMC, signal: 'ADDR, 09', pin_signal: GPIO_EMC_18}
  - {pin_num: H2, peripheral: SEMC, signal: 'ADDR, 10', pin_signal: GPIO_EMC_23}
  - {pin_num: A3, peripheral: SEMC, signal: 'ADDR, 11', pin_signal: GPIO_EMC_19}
  - {pin_num: A2, peripheral: SEMC, signal: 'ADDR, 12', pin_signal: GPIO_EMC_20}
  - {pin_num: E2, peripheral: SEMC, signal: 'BA, 0', pin_signal: GPIO_EMC_21}
  - {pin_num: F1, peripheral: SEMC, signal: 'BA, 1', pin_signal: GPIO_EMC_22}
  - {pin_num: D2, peripheral: SEMC, signal: semc_cas, pin_signal: GPIO_EMC_24}
  - {pin_num: C3, peripheral: SEMC, signal: semc_cke, pin_signal: GPIO_EMC_27}
  - {pin_num: B2, peripheral: SEMC, signal: semc_clk, pin_signal: GPIO_EMC_26}
  - {pin_num: E3, peripheral: SEMC, signal: 'DATA, 00', pin_signal: GPIO_EMC_00}
  - {pin_num: F3, peripheral: SEMC, signal: 'DATA, 01', pin_signal: GPIO_EMC_01}
  - {pin_num: F2, peripheral: SEMC, signal: 'DATA, 02', pin_signal: GPIO_EMC_02}
  - {pin_num: F4, peripheral: SEMC, signal: 'DATA, 03', pin_signal: GPIO_EMC_03}
  - {pin_num: H4, peripheral: SEMC, signal: 'DATA, 04', pin_signal: GPIO_EMC_04}
  - {pin_num: G3, peripheral: SEMC, signal: 'DATA, 05', pin_signal: GPIO_EMC_05}
  - {pin_num: G4, peripheral: SEMC, signal: 'DATA, 06', pin_signal: GPIO_EMC_06}
  - {pin_num: G5, peripheral: SEMC, signal: 'DATA, 07', pin_signal: GPIO_EMC_07}
  - {pin_num: B7, peripheral: SEMC, signal: 'DATA, 08', pin_signal: GPIO_EMC_30}
  - {pin_num: C5, peripheral: SEMC, signal: 'DATA, 09', pin_signal: GPIO_EMC_31}
  - {pin_num: D5, peripheral: SEMC, signal: 'DATA, 10', pin_signal: GPIO_EMC_32}
  - {pin_num: D4, peripheral: SEMC, signal: 'DATA, 11', pin_signal: GPIO_EMC_33}
  - {pin_num: B4, peripheral: SEMC, signal: 'DATA, 12', pin_signal: GPIO_EMC_34}
  - {pin_num: C4, peripheral: SEMC, signal: 'DATA, 13', pin_signal: GPIO_EMC_35}
  - {pin_num: B3, peripheral: SEMC, signal: 'DATA, 14', pin_signal: GPIO_EMC_36}
  - {pin_num: E5, peripheral: SEMC, signal: 'DATA, 15', pin_signal: GPIO_EMC_37}
  - {pin_num: H1, peripheral: SEMC, signal: 'DM, 0', pin_signal: GPIO_EMC_08}
  - {pin_num: B6, peripheral: SEMC, signal: 'DM, 1', pin_signal: GPIO_EMC_38}
  - {pin_num: D1, peripheral: SEMC, signal: semc_ras, pin_signal: GPIO_EMC_25}
  - {pin_num: B1, peripheral: SEMC, signal: semc_we, pin_signal: GPIO_EMC_28}
  - {pin_num: E1, peripheral: SEMC, signal: 'CS, 0', pin_signal: GPIO_EMC_29}
  - {pin_num: C6, peripheral: SEMC, signal: semc_dqs, pin_signal: GPIO_EMC_39}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSDRAMPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitSDRAMPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_00_SEMC_DATA00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_01_SEMC_DATA01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_02_SEMC_DATA02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_03_SEMC_DATA03, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_04_SEMC_DATA04, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_05_SEMC_DATA05, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_06_SEMC_DATA06, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_07_SEMC_DATA07, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_08_SEMC_DM00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_09_SEMC_ADDR00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_10_SEMC_ADDR01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_11_SEMC_ADDR02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_12_SEMC_ADDR03, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_13_SEMC_ADDR04, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_14_SEMC_ADDR05, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_15_SEMC_ADDR06, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_16_SEMC_ADDR07, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_17_SEMC_ADDR08, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_18_SEMC_ADDR09, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_19_SEMC_ADDR11, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_20_SEMC_ADDR12, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_21_SEMC_BA0, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_22_SEMC_BA1, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_23_SEMC_ADDR10, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_24_SEMC_CAS, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_25_SEMC_RAS, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_26_SEMC_CLK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_27_SEMC_CKE, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_28_SEMC_WE, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_29_SEMC_CS0, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_30_SEMC_DATA08, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_31_SEMC_DATA09, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_32_SEMC_DATA10, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_33_SEMC_DATA11, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_34_SEMC_DATA12, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_35_SEMC_DATA13, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_36_SEMC_DATA14, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_37_SEMC_DATA15, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_38_SEMC_DM01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_39_SEMC_DQS, 0U); 
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLCDPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: D7, peripheral: LCDIF, signal: lcdif_clk, pin_signal: GPIO_B0_00, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: D8, peripheral: LCDIF, signal: lcdif_enable, pin_signal: GPIO_B0_01, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: E8, peripheral: LCDIF, signal: lcdif_hsync, pin_signal: GPIO_B0_02, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: E7, peripheral: LCDIF, signal: lcdif_vsync, pin_signal: GPIO_B0_03, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: C8, peripheral: LCDIF, signal: 'lcdif_data, 00', pin_signal: GPIO_B0_04, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: A8, peripheral: LCDIF, signal: 'lcdif_data, 01', pin_signal: GPIO_B0_05, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: B8, peripheral: LCDIF, signal: 'lcdif_data, 02', pin_signal: GPIO_B0_06, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: A9, peripheral: LCDIF, signal: 'lcdif_data, 03', pin_signal: GPIO_B0_07, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: A10, peripheral: LCDIF, signal: 'lcdif_data, 04', pin_signal: GPIO_B0_08, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: C9, peripheral: LCDIF, signal: 'lcdif_data, 05', pin_signal: GPIO_B0_09, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: D9, peripheral: LCDIF, signal: 'lcdif_data, 06', pin_signal: GPIO_B0_10, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: B9, peripheral: LCDIF, signal: 'lcdif_data, 07', pin_signal: GPIO_B0_11, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: D10, peripheral: LCDIF, signal: 'lcdif_data, 08', pin_signal: GPIO_B0_12, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: C10, peripheral: LCDIF, signal: 'lcdif_data, 09', pin_signal: GPIO_B0_13, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: C11, peripheral: LCDIF, signal: 'lcdif_data, 10', pin_signal: GPIO_B0_14, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: D11, peripheral: LCDIF, signal: 'lcdif_data, 11', pin_signal: GPIO_B0_15, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: A11, peripheral: LCDIF, signal: 'lcdif_data, 12', pin_signal: GPIO_B1_00, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: A12, peripheral: LCDIF, signal: 'lcdif_data, 13', pin_signal: GPIO_B1_01, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: E12, peripheral: LCDIF, signal: 'lcdif_data, 14', pin_signal: GPIO_B1_02, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: E10, peripheral: LCDIF, signal: 'lcdif_data, 15', pin_signal: GPIO_B1_03, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: D13, peripheral: GPIO2, signal: 'gpio_io, 31', pin_signal: GPIO_B1_15, software_input_on: Disable, hysteresis_enable: Disable, pull_up_down_config: Pull_Down_100K_Ohm,
    pull_keeper_select: Keeper, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLCDPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLCDPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_00_LCD_CLK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_01_LCD_ENABLE, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_02_LCD_HSYNC, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_03_LCD_VSYNC, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_04_LCD_DATA00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_05_LCD_DATA01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_06_LCD_DATA02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_07_LCD_DATA03, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_08_LCD_DATA04, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_09_LCD_DATA05, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_10_LCD_DATA06, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_11_LCD_DATA07, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_12_LCD_DATA08, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_13_LCD_DATA09, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_14_LCD_DATA10, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_15_LCD_DATA11, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_00_LCD_DATA12, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_01_LCD_DATA13, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_02_LCD_DATA14, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_03_LCD_DATA15, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_15_GPIO2_IO31, 0U); 
  IOMUXC_GPR->GPR27 = ((IOMUXC_GPR->GPR27 &
    (~(BOARD_INITLCDPINS_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL(0x00U) 
    );
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_00_LCD_CLK, 0x01B0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_01_LCD_ENABLE, 0x01B0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_02_LCD_HSYNC, 0x01B0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_03_LCD_VSYNC, 0x01B0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_04_LCD_DATA00, 0x01B0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_05_LCD_DATA01, 0x01B0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_06_LCD_DATA02, 0x01B0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_07_LCD_DATA03, 0x01B0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_08_LCD_DATA04, 0x01B0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_09_LCD_DATA05, 0x01B0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_10_LCD_DATA06, 0x01B0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_11_LCD_DATA07, 0x01B0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_12_LCD_DATA08, 0x01B0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_13_LCD_DATA09, 0x01B0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_14_LCD_DATA10, 0x01B0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_15_LCD_DATA11, 0x01B0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_00_LCD_DATA12, 0x01B0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_01_LCD_DATA13, 0x01B0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_02_LCD_DATA14, 0x01B0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_03_LCD_DATA15, 0x01B0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_15_GPIO2_IO31, 0x10B0U); 
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitCANPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: J13, peripheral: CAN2, signal: TX, pin_signal: GPIO_AD_B0_14}
  - {pin_num: K10, peripheral: CAN2, signal: RX, pin_signal: GPIO_AD_B0_15}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitCANPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitCANPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_14_FLEXCAN2_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_15_FLEXCAN2_RX, 0U); 
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitENETPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: F10, peripheral: ENET, signal: 'enet_rx_data, 0', pin_signal: GPIO_B1_04}
  - {pin_num: E11, peripheral: ENET, signal: 'enet_rx_data, 1', pin_signal: GPIO_B1_05}
  - {pin_num: C13, peripheral: ENET, signal: enet_rx_en, pin_signal: GPIO_B1_06}
  - {pin_num: B12, peripheral: ENET, signal: 'enet_tx_data, 0', pin_signal: GPIO_B1_07}
  - {pin_num: B11, peripheral: ENET, signal: 'enet_tx_data, 1', pin_signal: GPIO_B1_08}
  - {pin_num: B13, peripheral: ENET, signal: enet_tx_en, pin_signal: GPIO_B1_09}
  - {pin_num: C12, peripheral: ENET, signal: enet_ref_clk, pin_signal: GPIO_B1_10}
  - {pin_num: D12, peripheral: ENET, signal: enet_rx_er, pin_signal: GPIO_B1_11}
  - {pin_num: C7, peripheral: ENET, signal: enet_mdc, pin_signal: GPIO_EMC_40}
  - {pin_num: D6, peripheral: ENET, signal: enet_mdio, pin_signal: GPIO_EMC_41}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitENETPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitENETPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_04_ENET_RX_DATA00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_05_ENET_RX_DATA01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_06_ENET_RX_EN, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_07_ENET_TX_DATA00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_08_ENET_TX_DATA01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_09_ENET_TX_EN, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_10_ENET_REF_CLK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_11_ENET_RX_ER, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_40_ENET_MDC, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_41_ENET_MDIO, 0U); 
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitUSDHCPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: E13, peripheral: USDHC1, signal: usdhc_vselect, pin_signal: GPIO_B1_14}
  - {pin_num: H3, peripheral: USDHC1, signal: usdhc_cmd, pin_signal: GPIO_SD_B0_00}
  - {pin_num: K3, peripheral: USDHC1, signal: usdhc_clk, pin_signal: GPIO_SD_B0_01}
  - {pin_num: J3, peripheral: USDHC1, signal: 'usdhc_data, 0', pin_signal: GPIO_SD_B0_02}
  - {pin_num: J2, peripheral: USDHC1, signal: 'usdhc_data, 1', pin_signal: GPIO_SD_B0_03}
  - {pin_num: J4, peripheral: USDHC1, signal: 'usdhc_data, 2', pin_signal: GPIO_SD_B0_04}
  - {pin_num: J1, peripheral: USDHC1, signal: 'usdhc_data, 3', pin_signal: GPIO_SD_B0_05}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitUSDHCPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitUSDHCPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_14_USDHC1_VSELECT, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_00_USDHC1_CMD, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_01_USDHC1_CLK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_02_USDHC1_DATA0, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_03_USDHC1_DATA1, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_04_USDHC1_DATA2, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_05_USDHC1_DATA3, 0U); 
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitQSPIPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: M4, peripheral: FLEXSPI, signal: FLEXSPI_A_DQS, pin_signal: GPIO_SD_B1_05}
  - {pin_num: M5, peripheral: FLEXSPI, signal: FLEXSPI_A_SS0_B, pin_signal: GPIO_SD_B1_06}
  - {pin_num: L4, peripheral: FLEXSPI, signal: FLEXSPI_A_SCLK, pin_signal: GPIO_SD_B1_07}
  - {pin_num: N4, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA0, pin_signal: GPIO_SD_B1_08}
  - {pin_num: K6, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA1, pin_signal: GPIO_SD_B1_09}
  - {pin_num: N5, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA2, pin_signal: GPIO_SD_B1_10}
  - {pin_num: N6, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA3, pin_signal: GPIO_SD_B1_11}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitQSPIPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitQSPIPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_05_FLEXSPIA_DQS, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_06_FLEXSPIA_SS0_B, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_07_FLEXSPIA_SCLK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_08_FLEXSPIA_DATA00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_09_FLEXSPIA_DATA01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_10_FLEXSPIA_DATA02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_11_FLEXSPIA_DATA03, 0U); 
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
