/*
 * Copyright 2017-2020 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */


/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v8.0
processor: MIMX8QM6xxxFF
package_id: MIMX8QM6AVUFF
mcu_data: ksdk2_0
processor_version: 0.0.0
board: MIMX8QM-MEK-REV-B
pin_labels:
- {pin_num: B4, pin_signal: USDHC1_VSELECT, label: USDHC1_VSELECT, identifier: USDHC1_VSELECT}
- {pin_num: BD6, pin_signal: SPDIF0_EXT_CLK, label: BB_GPIO1(SPDIF0_EXT_CLK), identifier: BB_GPIO1}
- {pin_num: AP8, pin_signal: ADC_IN2, label: WIFI_WAKE_B(ADC_IN2), identifier: WIFI_WAKE_B}
- {pin_num: AP10, pin_signal: ADC_IN0, label: BB_GPIO_1V8(ADC_IN0), identifier: BB_GPIO_1V8}
- {pin_num: A11, pin_signal: ENET1_REFCLK_125M_25M, label: ENET1_REFCLK, identifier: ENET1_REFCLK}
- {pin_num: H26, pin_signal: USB_HSIC0_DATA, label: USB_HSIC0_DATA, identifier: USB_HSIC0_DATA}
- {pin_num: F28, pin_signal: USB_HSIC0_STROBE, label: USB_HSIC0_STROBE, identifier: USB_HSIC0_STROBE}
- {pin_num: H38, pin_signal: EMMC0_RESET_B, label: BB_GPIO_1V8(EMMC0_RESET_B)BB_GPIO_1V8(EMMC0_RESET_B), identifier: BB_GPIO_1V8}
- {pin_num: H40, pin_signal: USDHC1_DATA4, label: BB_GPIO_1V8(USDHC1_DATA4), identifier: BB_GPIO_1V8}
- {pin_num: G43, pin_signal: USDHC1_DATA5, label: BB_GPIO_1V8(USDHC1_DATA5), identifier: BB_GPIO_1V8}
- {pin_num: J39, pin_signal: USDHC1_CLK, label: USDHC1_CLK, identifier: USDHC1_CLK}
- {pin_num: G41, pin_signal: USDHC1_CMD, label: USDHC1_CMD, identifier: USDHC1_CMD}
- {pin_num: H42, pin_signal: USDHC1_DATA7, label: USDHC1_CD_B, identifier: USDHC1_CD_B}
- {pin_num: B8, pin_signal: USDHC2_CD_B, label: 'BB_USDHC2_CD_B/J20D[42]', identifier: BB_USDHC2_CD_B}
- {pin_num: F46, pin_signal: USDHC2_CLK, label: WIFI_BT_SDIO_CLK, identifier: WIFI_BT_SDIO_CLK}
- {pin_num: H44, pin_signal: USDHC2_CMD, label: WIFI_BT_SDIO_CMD, identifier: WIFI_BT_SDIO_CMD}
- {pin_num: BJ23, pin_signal: MIPI_CSI0_MCLK_OUT, label: MIPI_CSI0_MCLK_OUT, identifier: MIPI_CSI0_MCLK_OUT}
- {pin_num: BN23, pin_signal: MIPI_CSI1_MCLK_OUT, label: MIPI_CSI1_MCLK_OUT, identifier: MIPI_CSI1_MCLK_OUT}
- {pin_num: E17, pin_signal: QSPI0A_SCLK, label: QSPI0A_CLK, identifier: QSPI0A_CLK}
- {pin_num: E15, pin_signal: QSPI0A_SS0_B, label: QSPI0A_CS_B, identifier: QSPI0A_CS_B}
- {pin_num: G17, pin_signal: QSPI0A_DQS, label: QSPI0_DQS, identifier: QSPI0_DQS}
- {pin_num: G13, pin_signal: QSPI0A_DATA0, label: QSPI0_DAT0, identifier: QSPI0_DAT0}
- {pin_num: F14, pin_signal: QSPI0A_DATA1, label: QSPI0_DAT1, identifier: QSPI0_DAT1}
- {pin_num: H14, pin_signal: QSPI0A_DATA2, label: QSPI0_DAT2, identifier: QSPI0_DAT2}
- {pin_num: H16, pin_signal: QSPI0A_DATA3, label: QSPI0_DAT3, identifier: QSPI0_DAT3}
- {pin_num: F18, pin_signal: QSPI0B_SCLK, label: QSPI0B_CLK, identifier: QSPI0B_CLK}
- {pin_num: F22, pin_signal: QSPI0B_SS0_B, label: QSPI0B_CS_B, identifier: QSPI0B_CS_B}
- {pin_num: H18, pin_signal: QSPI0B_DATA0, label: QSPI0_DAT4, identifier: QSPI0_DAT4}
- {pin_num: H20, pin_signal: QSPI0B_DATA1, label: QSPI0_DAT5, identifier: QSPI0_DAT5}
- {pin_num: G19, pin_signal: QSPI0B_DATA2, label: QSPI0_DAT6, identifier: QSPI0_DAT6}
- {pin_num: F20, pin_signal: QSPI0B_DATA3, label: QSPI0_DAT7, identifier: QSPI0_DAT7}
- {pin_num: BB44, pin_signal: SCU_BOOT_MODE0, label: SCU_BOOT_MODE0, identifier: SCU_BOOT_MODE0}
- {pin_num: BC45, pin_signal: SCU_BOOT_MODE1, label: SCU_BOOT_MODE1, identifier: SCU_BOOT_MODE1}
- {pin_num: BJ53, pin_signal: SCU_BOOT_MODE2, label: SCU_BOOT_MODE2, identifier: SCU_BOOT_MODE2}
- {pin_num: BA43, pin_signal: SCU_BOOT_MODE3, label: SCU_BOOT_MODE3, identifier: SCU_BOOT_MODE3}
- {pin_num: AY42, pin_signal: SCU_BOOT_MODE4, label: SCU_BOOT_MODE4, identifier: SCU_BOOT_MODE4}
- {pin_num: BK52, pin_signal: SCU_BOOT_MODE5, label: SCU_BOOT_MODE5, identifier: SCU_BOOT_MODE5}
- {pin_num: BN9, pin_signal: HDMI_TX0_TS_SCL, label: I2C0_3V3_SCL, identifier: I2C0_3V3_SCL}
- {pin_num: BN7, pin_signal: HDMI_TX0_TS_SDA, label: I2C0_3V3_SDA, identifier: I2C0_3V3_SDA}
- {pin_num: AY46, pin_signal: PMIC_I2C_SCL, label: PMIC_I2C_SCL, identifier: PMIC_I2C_SCL}
- {pin_num: BG51, pin_signal: PMIC_I2C_SDA, label: PMIC_I2C_SDA, identifier: PMIC_I2C_SDA}
- {pin_num: BB50, pin_signal: SCU_WDOG_OUT, label: SCU_WDOG_OUT, identifier: SCU_WDOG_OUT}
- {pin_num: BF50, pin_signal: PMIC_EARLY_WARNING, label: PMIC_EWARN, identifier: PMIC_EWARN}
- {pin_num: BH50, pin_signal: PMIC_INT_B, label: PMIC_INT_B, identifier: PMIC_INT_B}
- {pin_num: BC53, pin_signal: SCU_PMIC_MEMC_ON, label: CPU_RST_1V8_B, identifier: CPU_RST_1V8_B}
- {pin_num: AU43, pin_signal: SCU_GPIO0_00, label: 'BB_USB_OTG1_FLT_B(SCU_UART0_RX)/J20B[36]', identifier: BB_USB_OTG1_FLT_B}
- {pin_num: AV44, pin_signal: SCU_GPIO0_01, label: GPIO_1V8(SCU_UART0_TX), identifier: GPIO_1V8}
- {pin_num: AW45, pin_signal: SCU_GPIO0_02, label: SCU_DEBUG_LED(SCU_GPIO0_02), identifier: SCU_DEBUG_LED}
- {pin_num: BB46, pin_signal: SCU_GPIO0_03, label: AUD_DET_1V8(SCU_GPIO0_03), identifier: AUD_DET_1V8}
- {pin_num: BC47, pin_signal: SCU_GPIO0_04, label: 'BB_MKBUS_INT_1V8(SCU_GPIO0_04)/J20D[27]', identifier: BB_MKBUS_INT_1V8}
- {pin_num: AY44, pin_signal: SCU_GPIO0_05, label: 'BB_SPI1_INT_1V8(SCU_GPIO0_05)/J20C[29]', identifier: BB_SPI1_INT_1V8}
- {pin_num: BG49, pin_signal: SCU_GPIO0_06, label: 'BB_EXP_INT_1V8(SCU_GPIO0_06)/J20C[28]', identifier: BB_EXP_INT_1V8}
- {pin_num: BF48, pin_signal: SCU_GPIO0_07, label: SUSCLK_32KHZ(SCU_GPIO0_07), identifier: SUSCLK_32KHZ}
- {pin_num: AW9, pin_signal: ESAI0_FSR, label: 'BB_ESAI0_FSR/J20D[24]', identifier: BB_ESAI0_FSR}
- {pin_num: BG9, pin_signal: ESAI0_FST, label: 'BB_ESAI0_FST/J20D[20]', identifier: BB_ESAI0_FST}
- {pin_num: BB8, pin_signal: ESAI0_SCKR, label: 'BB_ESAI0_SCKR/J20D[17]', identifier: BB_ESAI0_SCKR}
- {pin_num: AY8, pin_signal: ESAI0_SCKT, label: 'BB_ESAI0_SCKT/J20D[18]', identifier: BB_ESAI0_SCKT}
- {pin_num: BA9, pin_signal: ESAI0_TX0, label: 'BB_ESAI0_TX0/J20D[21]', identifier: BB_ESAI0_TX0}
- {pin_num: BA7, pin_signal: ESAI0_TX1, label: 'BB_ESAI0_TX1/J20D[15]', identifier: BB_ESAI0_TX1}
- {pin_num: AU9, pin_signal: ESAI0_TX2_RX3, label: 'BB_ESAI0_TX2_RX3/J20D[26]', identifier: BB_ESAI0_TX2_RX3}
- {pin_num: BC5, pin_signal: ESAI0_TX3_RX2, label: 'BB_ESAI0_TX3_RX2/J20D[14]', identifier: BB_ESAI0_TX3_RX2}
- {pin_num: AV8, pin_signal: ESAI0_TX4_RX1, label: 'BB_ESAI0_TX4_RX1/J20D[23]', identifier: BB_ESAI0_TX4_RX1}
- {pin_num: AU7, pin_signal: ESAI0_TX5_RX0, label: 'BB_ESAI0_TX5_RX0/J20D[12]', identifier: BB_ESAI0_TX5_RX0}
- {pin_num: BE11, pin_signal: ESAI1_FSR, label: 'BB_ESAI1_FSR/J20F[14]', identifier: BB_ESAI1_FSR}
- {pin_num: BF12, pin_signal: ESAI1_FST, label: 'BB_ESAI1_FST/J20F[12]', identifier: BB_ESAI1_FST}
- {pin_num: BD12, pin_signal: ESAI1_SCKR, label: 'BB_ESAI1_SCKR/J20F[15]', identifier: BB_ESAI1_SCKR}
- {pin_num: AY10, pin_signal: ESAI1_SCKT, label: 'BB_ESAI1_SCKT/J20F[20]', identifier: BB_ESAI1_SCKT}
- {pin_num: BF10, pin_signal: ESAI1_TX0, label: 'BB_ESAI1_TX0/J20F[11]', identifier: BB_ESAI1_TX0}
- {pin_num: BA11, pin_signal: ESAI1_TX1, label: 'BB_ESAI1_TX1/J20F[17]', identifier: BB_ESAI1_TX1}
- {pin_num: AU11, pin_signal: ESAI1_TX2_RX3, label: 'BB_ESAI1_TX2/J20F[24]', identifier: BB_ESAI1_TX2}
- {pin_num: AV10, pin_signal: ESAI1_TX3_RX2, label: 'BB_ESAI1_TX3/J20F[23]', identifier: BB_ESAI1_TX3}
- {pin_num: AY12, pin_signal: ESAI1_TX4_RX1, label: 'BB_ESAI1_RX1/J20F[18]', identifier: BB_ESAI1_RX1}
- {pin_num: AT10, pin_signal: ESAI1_TX5_RX0, label: 'BB_ESAI1_RX0/J20F[26]', identifier: BB_ESAI1_RX0}
- {pin_num: BC3, pin_signal: MCLK_IN0, label: 'BB_MCLK_IN(MCLK_IN0)/J20A[26]', identifier: BB_MCLK_IN}
- {pin_num: BD4, pin_signal: MCLK_OUT0, label: MCLK_OUT0, identifier: MCLK_OUT0}
- {pin_num: BB4, pin_signal: SPI0_SCK, label: 'BB_SPI0_SCLK/J20E[25]', identifier: BB_SPI0_SCLK}
- {pin_num: AY6, pin_signal: SPI0_SDO, label: 'BB_SPI0_MOSI/J20E[26]', identifier: BB_SPI0_MOSI}
- {pin_num: BA5, pin_signal: SPI0_SDI, label: 'BB_SPI0_MISO/J20E[28]', identifier: BB_SPI0_MISO}
- {pin_num: BC1, pin_signal: SPI0_CS0, label: 'BB_SPI0_CS0/J20E[29]', identifier: BB_SPI0_CS0}
- {pin_num: AW5, pin_signal: SPI2_SCK, label: 'BB_SPI2_SCLK/J20B[18]', identifier: BB_SPI2_SCLK}
- {pin_num: BA1, pin_signal: SPI2_SDO, label: 'BB_SPI2_MOSI/J20B[14]', identifier: BB_SPI2_MOSI}
- {pin_num: AY4, pin_signal: SPI2_SDI, label: 'BB_SPI2_MISO/J20B[15]', identifier: BB_SPI2_MISO}
- {pin_num: AW1, pin_signal: SPI2_CS0, label: 'BB_SPI2_CS0/J20B[17]', identifier: BB_SPI2_CS0}
- {pin_num: BF6, pin_signal: SPI3_SCK, label: 'BB_SPI3_SCLK/J20C[16]', identifier: BB_SPI3_SCLK}
- {pin_num: BF2, pin_signal: SPI3_SDO, label: 'BB_SPI3_MOSI/J20C[17]', identifier: BB_SPI3_MOSI}
- {pin_num: BE5, pin_signal: SPI3_SDI, label: 'BB_SPI3_MISO/J20C[19]', identifier: BB_SPI3_MISO}
- {pin_num: BG5, pin_signal: SPI3_CS0, label: 'BB_SPI3_CS0/J20C[20]', identifier: BB_SPI3_CS0}
- {pin_num: BD8, pin_signal: SPI3_CS1, label: 'BB_SPI3_CS1/J20C[22]', identifier: BB_SPI3_CS1}
- {pin_num: AV6, pin_signal: SAI1_RXC, label: BT_SAI0_TXD(SAI1_RXC), identifier: BT_SAI0_TXD}
- {pin_num: AV4, pin_signal: SAI1_RXD, label: SAI1_RXD, identifier: SAI1_RXD}
- {pin_num: AU3, pin_signal: SAI1_RXFS, label: BT_SAI0_RXD(SAI1_RXFS), identifier: BT_SAI0_RXD}
- {pin_num: AU5, pin_signal: SAI1_TXC, label: SAI1_TXC, identifier: SAI1_TXC}
- {pin_num: AU1, pin_signal: SAI1_TXD, label: SAI1_TXD, identifier: SAI1_TXD}
- {pin_num: AV2, pin_signal: SAI1_TXFS, label: SAI1_TXFS, identifier: SAI1_TXFS}
- {pin_num: BC7, pin_signal: SPDIF0_RX, label: BB_MCLKIN1(SPDIF0_RX), identifier: BB_MCLKIN1}
- {pin_num: BC9, pin_signal: SPDIF0_TX, label: BB_MCLKOUT1(SPDIF0_TX), identifier: BB_MCLKOUT1}
- {pin_num: D2, pin_signal: MLB_CLK, label: 'BB_MLB_CLK/J20F[47]', identifier: BB_MLB_CLK}
- {pin_num: E3, pin_signal: MLB_DATA, label: 'BB_MLB_DATA/J20F[45]', identifier: BB_MLB_DATA}
- {pin_num: E1, pin_signal: MLB_SIG, label: 'BB_MLB_SIG/J20F[50]', identifier: BB_MLB_SIG}
- {pin_num: C5, pin_signal: FLEXCAN0_RX, label: 'BB_CAN0_RX/J20C[25]', identifier: BB_CAN0_RX}
- {pin_num: H6, pin_signal: FLEXCAN0_TX, label: 'BB_CAN0_TX/J20C[26]', identifier: BB_CAN0_TX}
- {pin_num: E5, pin_signal: FLEXCAN1_RX, label: 'BB_CAN1_RX/J20C[11]', identifier: BB_CAN1_RX}
- {pin_num: G7, pin_signal: FLEXCAN1_TX, label: 'BB_CAN1_TX/J20C[10]', identifier: BB_CAN1_TX}
- {pin_num: C3, pin_signal: FLEXCAN2_RX, label: 'BB_CAN2_RX/J20C[14]', identifier: BB_CAN2_RX}
- {pin_num: E7, pin_signal: FLEXCAN2_TX, label: 'BB_CAN2_TX/J20C[13]', identifier: BB_CAN2_TX}
- {pin_num: AR9, pin_signal: ADC_IN3, label: 'BB_SPI1_CLK(ADC_IN3)/J20A[11]', identifier: BB_SPI1_CLK}
- {pin_num: AN9, pin_signal: ADC_IN4, label: 'BB_SPI1_SDO(ADC_IN4)/J20A[13]', identifier: BB_SPI1_SDO}
- {pin_num: AR7, pin_signal: ADC_IN5, label: 'BB_SPI1_SDI(ADC_IN5)/J20A[14]', identifier: BB_SPI1_SDI}
- {pin_num: AL9, pin_signal: ADC_IN6, label: 'BB_SPI1_CS0(ADC_IN6)/J20A[16]', identifier: BB_SPI1_CS0}
- {pin_num: AP6, pin_signal: ADC_IN7, label: 'BB_SPI1_CS1(ADC_IN7)/J20A[10]', identifier: BB_SPI1_CS1}
- {pin_num: AN11, pin_signal: ADC_IN1, label: 'BB_SPI3_INT_1V8(ADC_IN1)/J20A[25]', identifier: BB_SPI3_INT_1V8}
- {pin_num: AL45, pin_signal: SIM0_CLK, label: 'BB_SIM_CLK/J20E[11]', identifier: BB_SIM_CLK}
- {pin_num: AN45, pin_signal: SIM0_IO, label: 'BB_SIM_IO/J20E[14]', identifier: BB_SIM_IO}
- {pin_num: AP48, pin_signal: SIM0_RST, label: 'BB_SIM_RST/J20E[13]', identifier: BB_SIM_RST}
- {pin_num: AT48, pin_signal: SIM0_POWER_EN, label: 'BB_SIM_POWER_EN/J20E[16]', identifier: BB_SIM_POWER_EN}
- {pin_num: AL43, pin_signal: SIM0_PD, label: 'BB_SIM_PD/J20E[17]', identifier: BB_SIM_PD}
- {pin_num: AP46, pin_signal: SIM0_GPIO0_00, label: BB_SIM_INT_B, identifier: BB_SIM_INT_B}
- {pin_num: AU53, pin_signal: M40_GPIO0_01, label: 'BB_ARD_MIK_UART3_TX/J20A[35]', identifier: BB_ARD_MIK_UART3_TX}
- {pin_num: AR47, pin_signal: M40_GPIO0_00, label: 'BB_ARD_MIK_UART3_RX/J20A[34]', identifier: BB_ARD_MIK_UART3_RX}
- {pin_num: AM44, pin_signal: M40_I2C0_SCL, label: FTDI_M40_UART0_RX, identifier: FTDI_M40_UART0_RX}
- {pin_num: AU51, pin_signal: M40_I2C0_SDA, label: FTDI_M40_UART0_TX, identifier: FTDI_M40_UART0_TX}
- {pin_num: AP44, pin_signal: M41_GPIO0_00, label: 'BB_UART4_RX_AUDIN/J20C[34]', identifier: BB_UART4_RX_AUDIN}
- {pin_num: AU47, pin_signal: M41_GPIO0_01, label: 'BB_UART4_TX_AUDIN/J20C[35]', identifier: BB_UART4_TX_AUDIN}
- {pin_num: AR45, pin_signal: M41_I2C0_SCL, label: 'BB_M41_I2C0_1V8_SCL/J20A[22]', identifier: BB_M41_I2C0_1V8_SCL}
- {pin_num: AU49, pin_signal: M41_I2C0_SDA, label: 'BB_M41_I2C0_1V8_SDA/J20A[23]', identifier: BB_M41_I2C0_1V8_SDA}
- {pin_num: AY52, pin_signal: GPT0_CLK, label: I2C1_1V8_SCL, identifier: I2C1_1V8_SCL}
- {pin_num: AV52, pin_signal: GPT0_CAPTURE, label: I2C1_1V8_SDA, identifier: I2C1_1V8_SDA}
- {pin_num: AW53, pin_signal: GPT0_COMPARE, label: ENET0_INT_B, identifier: ENET0_INT_B}
- {pin_num: BA53, pin_signal: GPT1_CLK, label: 'BB_IOEXP_CAN_INT_B(GPT1_CLK)/J20B[11]', identifier: BB_IOEXP_CAN_INT_B}
- {pin_num: AY50, pin_signal: GPT1_CAPTURE, label: 'BB_IOEXP_INT_B(GPT1_CAPTURE)/J20D[50]', identifier: BB_IOEXP_INT_B}
- {pin_num: BA51, pin_signal: GPT1_COMPARE, label: 'BB_AUD_PWR_PWM(GPT1_COMPARE)/J20E[31]', identifier: BB_AUD_PWR_PWM}
- {pin_num: AV48, pin_signal: UART0_TX, label: FTDI_UART0_TX, identifier: FTDI_UART0_TX}
- {pin_num: AV50, pin_signal: UART0_RX, label: FTDI_UART0_RX, identifier: FTDI_UART0_RX}
- {pin_num: AU45, pin_signal: UART0_RTS_B, label: 'BB_UART2_RX/J20A[28]', identifier: BB_UART2_RX}
- {pin_num: AW49, pin_signal: UART0_CTS_B, label: 'BB_UART2_TX/J20A[29]', identifier: BB_UART2_TX}
- {pin_num: AT44, pin_signal: UART1_RX, label: BT_UART1_RX, identifier: BT_UART1_RX}
- {pin_num: AY48, pin_signal: UART1_TX, label: BT_UART1_TX, identifier: BT_UART1_TX}
- {pin_num: AR43, pin_signal: UART1_RTS_B, label: BT_UART1_RTS, identifier: BT_UART1_RTS}
- {pin_num: AV46, pin_signal: UART1_CTS_B, label: BT_UART1_CTS, identifier: BT_UART1_CTS}
- {pin_num: G37, pin_signal: EMMC0_STROBE, label: EMMC0_STRB, identifier: EMMC0_STRB}
- {pin_num: H28, pin_signal: EMMC0_CLK, label: EMMC0_CLK, identifier: EMMC0_CLK}
- {pin_num: J27, pin_signal: EMMC0_CMD, label: EMMC0_CMD, identifier: EMMC0_CMD}
- {pin_num: G29, pin_signal: EMMC0_DATA0, label: EMMC0_DAT0, identifier: EMMC0_DAT0}
- {pin_num: H30, pin_signal: EMMC0_DATA1, label: EMMC0_DAT1, identifier: EMMC0_DAT1}
- {pin_num: G31, pin_signal: EMMC0_DATA2, label: EMMC0_DAT2, identifier: EMMC0_DAT2}
- {pin_num: H32, pin_signal: EMMC0_DATA3, label: EMMC0_DAT3, identifier: EMMC0_DAT3}
- {pin_num: J33, pin_signal: EMMC0_DATA4, label: EMMC0_DAT4, identifier: EMMC0_DAT4}
- {pin_num: H34, pin_signal: EMMC0_DATA5, label: EMMC0_DAT5, identifier: EMMC0_DAT5}
- {pin_num: H36, pin_signal: EMMC0_DATA6, label: EMMC0_DAT6, identifier: EMMC0_DAT6}
- {pin_num: G35, pin_signal: EMMC0_DATA7, label: EMMC0_DAT7, identifier: EMMC0_DAT7}
- {pin_num: J43, pin_signal: USDHC1_STROBE, label: 'BB_MLB_INT_B(USDHC1_STROBE)/J20B[35]', identifier: BB_MLB_INT_B}
- {pin_num: E37, pin_signal: USDHC1_DATA0, label: USDHC1_DAT0, identifier: USDHC1_DAT0}
- {pin_num: F38, pin_signal: USDHC1_DATA1, label: USDHC1_DAT1, identifier: USDHC1_DAT1}
- {pin_num: E39, pin_signal: USDHC1_DATA2, label: USDHC1_DAT2, identifier: USDHC1_DAT2}
- {pin_num: F40, pin_signal: USDHC1_DATA3, label: USDHC1_DAT3, identifier: USDHC1_DAT3}
- {pin_num: F42, pin_signal: USDHC1_DATA6, label: USDHC1_WP, identifier: USDHC1_WP}
- {pin_num: C7, pin_signal: USDHC2_RESET_B, label: WIFI_EN(WIFI_RST_B), identifier: WIFI_EN}
- {pin_num: A7, pin_signal: USDHC2_VSELECT, label: USDHC2_VSELECT, identifier: USDHC2_VSELECT}
- {pin_num: D8, pin_signal: USDHC2_WP, label: SENSORS_INT_B(USDHC2_WP), identifier: SENSORS_INT_B}
- {pin_num: A5, pin_signal: USDHC1_RESET_B, label: USDHC1_RESET_B, identifier: USDHC1_RESET_B}
- {pin_num: H48, pin_signal: USDHC2_DATA0, label: WIFI_BT_SDIO_DAT0, identifier: WIFI_BT_SDIO_DAT0}
- {pin_num: G45, pin_signal: USDHC2_DATA1, label: WIFI_BT_SDIO_DAT1, identifier: WIFI_BT_SDIO_DAT1}
- {pin_num: L45, pin_signal: USDHC2_DATA2, label: WIFI_BT_SDIO_DAT2, identifier: WIFI_BT_SDIO_DAT2}
- {pin_num: J45, pin_signal: USDHC2_DATA3, label: WIFI_BT_SDIO_DAT3, identifier: WIFI_BT_SDIO_DAT3}
- {pin_num: F10, pin_signal: QSPI1A_SCLK, label: NX20P_ACK, identifier: NX20P_ACK}
- {pin_num: J11, pin_signal: QSPI1A_SS0_B, label: CBTL_EN, identifier: CBTL_EN}
- {pin_num: G11, pin_signal: QSPI1A_SS1_B, label: BB_GPIO_3V3(QSPI1A_SS1_B), identifier: BB_GPIO_3V3}
- {pin_num: H12, pin_signal: QSPI1A_DQS, label: BT_DISABLE_B, identifier: BT_DISABLE_B}
- {pin_num: D12, pin_signal: QSPI1A_DATA0, label: PTN5110_ALERT_B, identifier: PTN5110_ALERT_B}
- {pin_num: D14, pin_signal: QSPI1A_DATA1, label: 'BB_AUDIN_RST_B(QSPI1A_DATA1)/J20C[32]', identifier: BB_AUDIN_RST_B}
- {pin_num: E13, pin_signal: QSPI1A_DATA2, label: 'BB_GPIO_3V3(QSPI1A_DATA2)/J20C[43]', identifier: BB_GPIO_3V3_1}
- {pin_num: E11, pin_signal: QSPI1A_DATA3, label: 'BB_GPIO_3V3(QSPI1A_DATA3)/J20C[44]', identifier: BB_GPIO_3V3_2}
- {pin_num: J9, pin_signal: USB_SS3_TC0, label: 'BB_USB_OTG1_PWR_ON/J20A[32]', identifier: BB_USB_OTG1_PWR_ON}
- {pin_num: L9, pin_signal: USB_SS3_TC1, label: PTN51_DBG_ACC, identifier: PTN51_DBG_ACC}
- {pin_num: F8, pin_signal: USB_SS3_TC2, label: BT_WAKE(USB_SS3_TC2), identifier: BT_WAKE}
- {pin_num: H10, pin_signal: USB_SS3_TC3, label: CABLE_ORIENT, identifier: CABLE_ORIENT}
- {pin_num: A15, pin_signal: PCIE_CTRL0_WAKE_B, label: PCIE_WIBT_CTRL0_WAKE_B, identifier: PCIE_WIBT_CTRL0_WAKE_B}
- {pin_num: D20, pin_signal: PCIE_CTRL0_PERST_B, label: PCIE_WIBT_CTRL0_PERST_B, identifier: PCIE_WIBT_CTRL0_PERST_B}
- {pin_num: A17, pin_signal: PCIE_CTRL0_CLKREQ_B, label: PCIE_WIBT_CLKREQ_B, identifier: PCIE_WIBT_CLKREQ_B}
- {pin_num: A27, pin_signal: PCIE_CTRL1_WAKE_B, label: 'BB_PCIE_CTRL1_WAKE_B/J20B[21]', identifier: BB_PCIE_CTRL1_WAKE_B}
- {pin_num: G25, pin_signal: PCIE_CTRL1_PERST_B, label: 'BB_PCIE_CTRL1_PERST_B/J20B[23]', identifier: BB_PCIE_CTRL1_PERST_B}
- {pin_num: A25, pin_signal: PCIE_CTRL1_CLKREQ_B, label: 'BB_PCIE_CTRL1_CLKREQ_B/J20B[20]', identifier: BB_PCIE_CTRL1_CLKREQ_B}
- {pin_num: B10, pin_signal: ENET0_REFCLK_125M_25M, label: 'BB_ARD_MIK_RST_B/J20D[41]', identifier: BB_ARD_MIK_RST_B}
- {pin_num: A13, pin_signal: ENET1_MDC, label: I2C4_3V3_SCL, identifier: I2C4_3V3_SCL}
- {pin_num: C13, pin_signal: ENET1_MDIO, label: I2C4_3V3_SDA, identifier: I2C4_3V3_SDA}
- {pin_num: A9, pin_signal: ENET0_MDC, label: ENET0_MDC, identifier: ENET0_MDC}
- {pin_num: D10, pin_signal: ENET0_MDIO, label: ENET0_MDIO, identifier: ENET0_MDIO}
- {pin_num: A41, pin_signal: ENET0_RGMII_TXC, label: ETH0_RGMII_TXC, identifier: ETH0_RGMII_TXC}
- {pin_num: E41, pin_signal: ENET0_RGMII_TX_CTL, label: ETH0_RGMII_TX_CTL, identifier: ETH0_RGMII_TX_CTL}
- {pin_num: A43, pin_signal: ENET0_RGMII_TXD0, label: ETH0_RGMII_TXD0, identifier: ETH0_RGMII_TXD0}
- {pin_num: B42, pin_signal: ENET0_RGMII_TXD1, label: ETH0_RGMII_TXD1, identifier: ETH0_RGMII_TXD1}
- {pin_num: A45, pin_signal: ENET0_RGMII_TXD2, label: ETH0_RGMII_TXD2, identifier: ETH0_RGMII_TXD2}
- {pin_num: D42, pin_signal: ENET0_RGMII_TXD3, label: ETH0_RGMII_TXD3, identifier: ETH0_RGMII_TXD3}
- {pin_num: B44, pin_signal: ENET0_RGMII_RXC, label: ETH0_RGMII_RXC, identifier: ETH0_RGMII_RXC}
- {pin_num: E43, pin_signal: ENET0_RGMII_RX_CTL, label: ETH0_RGMII_RX_CTL, identifier: ETH0_RGMII_RX_CTL}
- {pin_num: A47, pin_signal: ENET0_RGMII_RXD0, label: ETH0_RGMII_RXD0, identifier: ETH0_RGMII_RXD0}
- {pin_num: D44, pin_signal: ENET0_RGMII_RXD1, label: ETH0_RGMII_RXD1, identifier: ETH0_RGMII_RXD1}
- {pin_num: C45, pin_signal: ENET0_RGMII_RXD2, label: ETH0_RGMII_RXD2, identifier: ETH0_RGMII_RXD2}
- {pin_num: E45, pin_signal: ENET0_RGMII_RXD3, label: ETH0_RGMII_RXD3, identifier: ETH0_RGMII_RXD3}
- {pin_num: D46, pin_signal: ENET1_RGMII_TXC, label: ENET1_RGMII_TXC, identifier: ENET1_RGMII_TXC}
- {pin_num: B48, pin_signal: ENET1_RGMII_TX_CTL, label: ENET1_RGMII_TX_CTL, identifier: ENET1_RGMII_TX_CTL}
- {pin_num: A49, pin_signal: ENET1_RGMII_TXD0, label: ENET1_RGMII_TXD0, identifier: ENET1_RGMII_TXD0}
- {pin_num: C47, pin_signal: ENET1_RGMII_TXD1, label: ENET1_RGMII_TXD1, identifier: ENET1_RGMII_TXD1}
- {pin_num: G47, pin_signal: ENET1_RGMII_TXD2, label: ENET1_RGMII_TXD2, identifier: ENET1_RGMII_TXD2}
- {pin_num: D48, pin_signal: ENET1_RGMII_TXD3, label: ENET1_RGMII_TXD3, identifier: ENET1_RGMII_TXD3}
- {pin_num: B50, pin_signal: ENET1_RGMII_RXC, label: 'BB_ENET1_RGMII_RXC/J20F[38]', identifier: BB_ENET1_RGMII_RXC}
- {pin_num: E49, pin_signal: ENET1_RGMII_RX_CTL, label: 'BB_ENET1_RGMII_RX_CTL/J20F[33]', identifier: BB_ENET1_RGMII_RX_CTL}
- {pin_num: E51, pin_signal: ENET1_RGMII_RXD0, label: 'BB_ENET1_RGMII_RXD0/J20F[30]', identifier: BB_ENET1_RGMII_RXD0}
- {pin_num: C51, pin_signal: ENET1_RGMII_RXD1, label: 'BB_ENET1_RGMII_RXD1/J20F[35]', identifier: BB_ENET1_RGMII_RXD1}
- {pin_num: D52, pin_signal: ENET1_RGMII_RXD2, label: 'BB_ENET1_RGMII_RXD2/J20F[32]', identifier: BB_ENET1_RGMII_RXD2}
- {pin_num: E53, pin_signal: ENET1_RGMII_RXD3, label: 'BB_ENET1_RGMII_RXD3/J20F[29]', identifier: BB_ENET1_RGMII_RXD3}
- {pin_num: BE39, pin_signal: LVDS0_GPIO00, label: LVDS0_BL_PWM, identifier: LVDS0_BL_PWM}
- {pin_num: BD40, pin_signal: LVDS0_GPIO01, label: LVDS0_TS_INT, identifier: LVDS0_TS_INT}
- {pin_num: BD38, pin_signal: LVDS0_I2C0_SCL, label: LVDS_EN, identifier: LVDS_EN}
- {pin_num: BD36, pin_signal: LVDS0_I2C0_SDA, label: MIPI_DSI0_1_EN, identifier: MIPI_DSI0_1_EN}
- {pin_num: BE37, pin_signal: LVDS0_I2C1_SCL, label: LVDS0_TS_SCL, identifier: LVDS0_TS_SCL}
- {pin_num: BE35, pin_signal: LVDS0_I2C1_SDA, label: LVDS0_TS_SDA, identifier: LVDS0_TS_SDA}
- {pin_num: BD34, pin_signal: LVDS1_GPIO00, label: LVDS1_BL_PWM, identifier: LVDS1_BL_PWM}
- {pin_num: BH36, pin_signal: LVDS1_GPIO01, label: LVDS1_TS_INT, identifier: LVDS1_TS_INT}
- {pin_num: BN35, pin_signal: LVDS1_I2C1_SDA, label: LVDS1_TS_SDA, identifier: LVDS1_TS_SDA}
- {pin_num: BE33, pin_signal: LVDS1_I2C0_SDA, label: WIBT_DISABLE_1V8(LVDS1_I2C0_SDA), identifier: WIBT_DISABLE_1V8}
- {pin_num: BD32, pin_signal: LVDS1_I2C1_SCL, label: LVDS1_TS_SCL, identifier: LVDS1_TS_SCL}
- {pin_num: BL23, pin_signal: MIPI_CSI0_GPIO0_00, label: MIPI_CSI0_RST_B, identifier: MIPI_CSI0_RST_B}
- {pin_num: BM22, pin_signal: MIPI_CSI0_GPIO0_01, label: MIPI_CSI0_EN, identifier: MIPI_CSI0_EN}
- {pin_num: BN15, pin_signal: MIPI_CSI1_GPIO0_00, label: MIPI_CSI1_RST_B, identifier: MIPI_CSI1_RST_B}
- {pin_num: BN13, pin_signal: MIPI_CSI1_GPIO0_01, label: MIPI_CSI1_EN, identifier: MIPI_CSI1_EN}
- {pin_num: BH24, pin_signal: MIPI_CSI0_I2C0_SCL, label: MIPI_CSI0_I2C0_SCL, identifier: MIPI_CSI0_I2C0_SCL}
- {pin_num: BN19, pin_signal: MIPI_CSI0_I2C0_SDA, label: MIPI_CSI0_I2C0_SDA, identifier: MIPI_CSI0_I2C0_SDA}
- {pin_num: BN17, pin_signal: MIPI_CSI1_I2C0_SCL, label: MIPI_CSI1_I2C0_SCL, identifier: MIPI_CSI1_I2C0_SCL}
- {pin_num: BE15, pin_signal: MIPI_CSI1_I2C0_SDA, label: MIPI_CSI1_I2C0_SDA, identifier: MIPI_CSI1_I2C0_SDA}
- {pin_num: BD30, pin_signal: MIPI_DSI0_GPIO0_00, label: MIPI_DSI0_BL_PWM, identifier: MIPI_DSI0_BL_PWM}
- {pin_num: BM24, pin_signal: MIPI_DSI1_GPIO0_00, label: MIPI_DSI1_BL_PWM, identifier: MIPI_DSI1_BL_PWM}
- {pin_num: BD28, pin_signal: MIPI_DSI0_GPIO0_01, label: MIPI_DSI0_TS_INT_B, identifier: MIPI_DSI0_TS_INT_B}
- {pin_num: BK24, pin_signal: MIPI_DSI1_GPIO0_01, label: MIPI_DSI1_TS_INT_B, identifier: MIPI_DSI1_TS_INT_B}
- {pin_num: BE29, pin_signal: MIPI_DSI0_I2C0_SCL, label: MIPI_DSI0_TS_SCL, identifier: MIPI_DSI0_TS_SCL}
- {pin_num: BE31, pin_signal: MIPI_DSI0_I2C0_SDA, label: MIPI_DSI0_TS_SDA, identifier: MIPI_DSI0_TS_SDA}
- {pin_num: BE27, pin_signal: MIPI_DSI1_I2C0_SCL, label: MIPI_DSI1_TS_SCL, identifier: MIPI_DSI1_TS_SCL}
- {pin_num: BG25, pin_signal: MIPI_DSI1_I2C0_SDA, label: MIPI_DSI1_TS_SDA, identifier: MIPI_DSI1_TS_SDA}
- {pin_num: BA3, pin_signal: SPI0_CS1, label: BT_SAI0_TXC(SPI0_CS1), identifier: BT_SAI0_TXC}
- {pin_num: AY2, pin_signal: SPI2_CS1, label: BT_SAI0_TXFS(SPI2_CS1), identifier: BT_SAI0_TXFS}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "pin_mux.h"
#include "fsl_common.h"
#include "main/imx8qm_pads.h"
#include "svc/pad/pad_api.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'false', coreID: cm4_core0}
- pin_list:
  - {pin_num: AM44, peripheral: M40__UART0, signal: uart_rx, pin_signal: M40_I2C0_SCL, PULL: PULL_0, sw_config: sw_config_0}
  - {pin_num: AU51, peripheral: M40__UART0, signal: uart_tx, pin_signal: M40_I2C0_SDA, PULL: PULL_0, sw_config: sw_config_0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(sc_ipc_t ipc)                          /*!< Function assigned for the core: Cortex-M4F[cm4_core0] */
{
  sc_err_t err = SC_ERR_NONE;

  err = sc_pad_set_all(ipc, BOARD_INITPINS_FTDI_M40_UART0_RX_PIN_FUNCTION_ID, 1U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x0 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_M40_I2C0_SCL register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
  err = sc_pad_set_all(ipc, BOARD_INITPINS_FTDI_M40_UART0_TX_PIN_FUNCTION_ID, 1U, SC_PAD_CONFIG_NORMAL, SC_PAD_ISO_OFF, 0x0 ,SC_PAD_WAKEUP_OFF);/* IOMUXD_M40_I2C0_SDA register modification value */
  if (SC_ERR_NONE != err)
  {
      assert(false);
  }
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
