#Description: Serial Manager USB CDC; user_visible: True
include_guard(GLOBAL)
message("component_serial_manager_usb_cdc component is included.")

target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/fsl_component_serial_port_usb.c
    ${CMAKE_CURRENT_LIST_DIR}/usb_cdc_adapter/usb_device_descriptor.c
)

target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
    ${CMAKE_CURRENT_LIST_DIR}/.
    ${CMAKE_CURRENT_LIST_DIR}/usb_cdc_adapter
)

#OR Logic component
if(${MCUX_DEVICE} STREQUAL "MIMXRT1166_cm4")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1166_cm7")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1052")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1064")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "K32L2B31A")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "MK64F12")
    include(driver_sysmpu)
endif()
if(${MCUX_DEVICE} STREQUAL "MK66F18")
    include(driver_sysmpu)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54628")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "MK22F51212")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1021")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC55S16")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1062")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54S018")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1176_cm4")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1176_cm7")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54S018M")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC55S69_cm33_core0")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1024")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1011")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC55S28")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "K32L2A41A")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT685S_cm33")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT595S_cm33")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT1015")
    include(driver_common)
endif()

include(middleware_usb_device_cdc_external)
