list(APPEND CMAKE_MODULE_PATH
    ${CMAKE_CURRENT_LIST_DIR}/.
    ${CMAKE_CURRENT_LIST_DIR}/../../CMSIS/Include
    ${CMAKE_CURRENT_LIST_DIR}/../../components/codec
    ${CMAKE_CURRENT_LIST_DIR}/../../components/codec/da7212
    ${CMAKE_CURRENT_LIST_DIR}/../../components/codec/i2c
    ${CMAKE_CURRENT_LIST_DIR}/../../components/codec/port/da7212
    ${CMAKE_CURRENT_LIST_DIR}/../../components/fxos8700cq
    ${CMAKE_CURRENT_LIST_DIR}/../../components/i2c
    ${CMAKE_CURRENT_LIST_DIR}/../../components/lists
    ${CMAKE_CURRENT_LIST_DIR}/../../components/osa
    ${CMAKE_CURRENT_LIST_DIR}/../../components/phy
    ${CMAKE_CURRENT_LIST_DIR}/../../components/phy/device/phyksz8081
    ${CMAKE_CURRENT_LIST_DIR}/../../components/phy/mdio/enet
    ${CMAKE_CURRENT_LIST_DIR}/../../components/serial_manager
    ${CMAKE_CURRENT_LIST_DIR}/../../components/uart
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/adc16
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/cache/lmem
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/cmp
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/cmt
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/common
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/crc
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/dac
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/dmamux
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/dspi
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/edma
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/enet
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/ewm
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/flash
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/flexcan
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/ftm
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/gpio
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/i2c
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/llwu
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/lptmr
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/lpuart
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/pdb
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/pit
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/pmc
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/port
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/rcm
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/rnga
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/rtc
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/sai
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/sdhc
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/sim
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/smc
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/sysmpu
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/tpm
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/uart
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/vref
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/wdog
    ${CMAKE_CURRENT_LIST_DIR}/../../middleware
    ${CMAKE_CURRENT_LIST_DIR}/../../middleware/mmcau
    ${CMAKE_CURRENT_LIST_DIR}/../../middleware/usb
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/assert
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/debug_console
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/debug_console_lite
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/misc_utilities
    ${CMAKE_CURRENT_LIST_DIR}/drivers
    ${CMAKE_CURRENT_LIST_DIR}/utilities
)


# Copy the cmake components into projects
mcux_include_from_kconfig(middleware_usb_device_common_header)
mcux_include_from_kconfig(driver_llwu)
mcux_include_from_kconfig(driver_dspi)
mcux_include_from_kconfig(driver_uart_edma)
mcux_include_from_kconfig(driver_sai)
mcux_include_from_kconfig(component_i2c_adapter)
mcux_include_from_kconfig(CMSIS_Include_dsp)
mcux_include_from_kconfig(driver_flexcan)
mcux_include_from_kconfig(driver_i2c)
mcux_include_from_kconfig(driver_port)
mcux_include_from_kconfig(driver_dmamux)
mcux_include_from_kconfig(driver_phy-common)
mcux_include_from_kconfig(driver_lptmr)
mcux_include_from_kconfig(driver_gpio)
mcux_include_from_kconfig(component_lists)
mcux_include_from_kconfig(driver_dac)
mcux_include_from_kconfig(device_system)
mcux_include_from_kconfig(driver_i2c_edma)
mcux_include_from_kconfig(driver_cmt)
mcux_include_from_kconfig(utility_debug_console)
mcux_include_from_kconfig(middleware_mmcau_common_files)
mcux_include_from_kconfig(utility_assert_lite_MK66F18)
mcux_include_from_kconfig(driver_cmp)
mcux_include_from_kconfig(device_startup)
mcux_include_from_kconfig(driver_pdb)
mcux_include_from_kconfig(driver_adc16)
mcux_include_from_kconfig(driver_clock)
mcux_include_from_kconfig(utility_notifier)
mcux_include_from_kconfig(utility_debug_console_lite)
mcux_include_from_kconfig(component_osa)
mcux_include_from_kconfig(driver_edma)
mcux_include_from_kconfig(driver_ewm)
mcux_include_from_kconfig(driver_codec_MK66F18)
mcux_include_from_kconfig(utility_assert)
mcux_include_from_kconfig(driver_lpuart)
mcux_include_from_kconfig(driver_phy-device-ksz8081)
mcux_include_from_kconfig(driver_rnga)
mcux_include_from_kconfig(driver_smc)
mcux_include_from_kconfig(driver_ftm)
mcux_include_from_kconfig(driver_rcm)
mcux_include_from_kconfig(driver_wdog)
mcux_include_from_kconfig(driver_cache_lmem)
mcux_include_from_kconfig(driver_sysmpu)
mcux_include_from_kconfig(middleware_baremetal)
mcux_include_from_kconfig(driver_vref)
mcux_include_from_kconfig(middleware_mmcau_cm4_cm7)
mcux_include_from_kconfig(driver_flash)
mcux_include_from_kconfig(component_uart_adapter)
mcux_include_from_kconfig(driver_mdio-enet)
mcux_include_from_kconfig(driver_sim)
mcux_include_from_kconfig(driver_lpuart_edma)
mcux_include_from_kconfig(device_CMSIS)
mcux_include_from_kconfig(driver_uart)
mcux_include_from_kconfig(component_serial_manager_uart_MK66F18)
mcux_include_from_kconfig(component_osa_bm)
mcux_include_from_kconfig(utilities_misc_utilities)
mcux_include_from_kconfig(CMSIS_Include_core_cm4)
mcux_include_from_kconfig(CMSIS_Include_common)
mcux_include_from_kconfig(driver_common)
mcux_include_from_kconfig(driver_rtc)
mcux_include_from_kconfig(driver_dialog7212)
mcux_include_from_kconfig(driver_crc)
mcux_include_from_kconfig(driver_mdio-common)
mcux_include_from_kconfig(driver_enet_MK66F18)
mcux_include_from_kconfig(driver_fxos8700cq)
mcux_include_from_kconfig(driver_pit)
mcux_include_from_kconfig(component_codec_i2c_MK66F18)
mcux_include_from_kconfig(driver_sai_edma)
mcux_include_from_kconfig(driver_sdhc)
mcux_include_from_kconfig(driver_pmc)
mcux_include_from_kconfig(component_da7212_adapter)
mcux_include_from_kconfig(driver_tpm)
mcux_include_from_kconfig(utility_shell)
mcux_include_from_kconfig(middleware_usb_common_header)
mcux_include_from_kconfig(component_serial_manager_MK66F18)
mcux_include_from_kconfig(driver_dspi_edma)
