list(APPEND CMAKE_MODULE_PATH
    ${CMAKE_CURRENT_LIST_DIR}/.
    ${CMAKE_CURRENT_LIST_DIR}/../../CMSIS/Driver/Include
    ${CMAKE_CURRENT_LIST_DIR}/../../CMSIS/Include
    ${CMAKE_CURRENT_LIST_DIR}/../../components/codec
    ${CMAKE_CURRENT_LIST_DIR}/../../components/codec/i2c
    ${CMAKE_CURRENT_LIST_DIR}/../../components/codec/port/wm8960
    ${CMAKE_CURRENT_LIST_DIR}/../../components/codec/wm8960
    ${CMAKE_CURRENT_LIST_DIR}/../../components/fxos8700cq
    ${CMAKE_CURRENT_LIST_DIR}/../../components/i2c
    ${CMAKE_CURRENT_LIST_DIR}/../../components/lists
    ${CMAKE_CURRENT_LIST_DIR}/../../components/pf1550
    ${CMAKE_CURRENT_LIST_DIR}/../../components/serial_manager
    ${CMAKE_CURRENT_LIST_DIR}/../../components/srtm
    ${CMAKE_CURRENT_LIST_DIR}/../../components/srtm/port
    ${CMAKE_CURRENT_LIST_DIR}/../../components/uart
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/acmp
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/cache/lmem
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/common
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/crc
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/dac12
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/dmamux
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/edma
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/ewm
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/flexio
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/gpio
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/llwu
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/lpadc
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/lpi2c
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/lpit
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/lpspi
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/lptmr
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/lpuart
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/ltc
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/msmc
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/mu
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/pmc0
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/port
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/qspi
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/sai
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/sema42
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/snvs_hp
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/snvs_lp
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/tpm
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/trgmux
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/trng
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/tstmr
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/wdog32
    ${CMAKE_CURRENT_LIST_DIR}/../../drivers/xrdc
    ${CMAKE_CURRENT_LIST_DIR}/../../middleware/issdk
    ${CMAKE_CURRENT_LIST_DIR}/../../middleware/mmcau
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/assert
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/debug_console
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/debug_console_lite
    ${CMAKE_CURRENT_LIST_DIR}/../../utilities/misc_utilities
    ${CMAKE_CURRENT_LIST_DIR}/drivers
    ${CMAKE_CURRENT_LIST_DIR}/utilities
)


# Copy the cmake components into projects
mcux_include_from_kconfig(driver_llwu)
mcux_include_from_kconfig(middleware_issdk_algorithms_pedometer_common)
mcux_include_from_kconfig(driver_pmc0)
mcux_include_from_kconfig(driver_ltc)
mcux_include_from_kconfig(driver_flexio_spi_edma)
mcux_include_from_kconfig(CMSIS_Include_dsp)
mcux_include_from_kconfig(component_lpuart_adapter)
mcux_include_from_kconfig(component_codec_i2c_MCIMX7U5)
mcux_include_from_kconfig(driver_port)
mcux_include_from_kconfig(driver_dmamux)
mcux_include_from_kconfig(driver_lpspi)
mcux_include_from_kconfig(driver_lpi2c_edma)
mcux_include_from_kconfig(driver_gpio)
mcux_include_from_kconfig(component_lists)
mcux_include_from_kconfig(component_serial_manager_MCIMX7U5)
mcux_include_from_kconfig(driver_snvs_hp)
mcux_include_from_kconfig(driver_snvs_lp)
mcux_include_from_kconfig(driver_lpit)
mcux_include_from_kconfig(driver_pf1550)
mcux_include_from_kconfig(utilities_misc_utilities)
mcux_include_from_kconfig(driver_acmp)
mcux_include_from_kconfig(device_startup)
mcux_include_from_kconfig(driver_clock)
mcux_include_from_kconfig(CMSIS_Driver_Include_SPI)
mcux_include_from_kconfig(utility_debug_console_lite)
mcux_include_from_kconfig(driver_flexio_uart)
mcux_include_from_kconfig(driver_edma)
mcux_include_from_kconfig(driver_ewm)
mcux_include_from_kconfig(driver_trng)
mcux_include_from_kconfig(utility_assert)
mcux_include_from_kconfig(driver_lpuart)
mcux_include_from_kconfig(driver_flexio_spi)
mcux_include_from_kconfig(driver_lpadc)
mcux_include_from_kconfig(middleware_mmcau_common_files)
mcux_include_from_kconfig(driver_flexio)
mcux_include_from_kconfig(utility_shell)
mcux_include_from_kconfig(driver_trgmux)
mcux_include_from_kconfig(CMSIS_Driver_Include_I2C)
mcux_include_from_kconfig(driver_wm8960)
mcux_include_from_kconfig(driver_dac12)
mcux_include_from_kconfig(component_serial_manager_uart_MCIMX7U5)
mcux_include_from_kconfig(driver_cache_lmem)
mcux_include_from_kconfig(utility_assert_lite_MCIMX7U5)
mcux_include_from_kconfig(utility_debug_console)
mcux_include_from_kconfig(middleware_mmcau_cm4_cm7)
mcux_include_from_kconfig(driver_lpi2c)
mcux_include_from_kconfig(driver_wdog32)
mcux_include_from_kconfig(driver_xrdc)
mcux_include_from_kconfig(driver_lpspi_edma)
mcux_include_from_kconfig(driver_codec_MCIMX7U5)
mcux_include_from_kconfig(driver_lpuart_edma)
mcux_include_from_kconfig(device_CMSIS)
mcux_include_from_kconfig(driver_sema42)
mcux_include_from_kconfig(CMSIS_Driver_Include_Common)
mcux_include_from_kconfig(driver_tstmr)
mcux_include_from_kconfig(driver_qspi_edma)
mcux_include_from_kconfig(CMSIS_Include_core_cm4)
mcux_include_from_kconfig(CMSIS_Include_common)
mcux_include_from_kconfig(driver_common)
mcux_include_from_kconfig(driver_msmc)
mcux_include_from_kconfig(driver_crc)
mcux_include_from_kconfig(driver_flexio_uart_edma)
mcux_include_from_kconfig(driver_srtm)
mcux_include_from_kconfig(middleware_issdk_algorithms_pedometer_lib_cm4)
mcux_include_from_kconfig(component_wm8960_adapter)
mcux_include_from_kconfig(middleware_issdk_sensor_allregdefs)
mcux_include_from_kconfig(driver_tpm)
mcux_include_from_kconfig(driver_fxos8700cq)
mcux_include_from_kconfig(driver_lptmr)
mcux_include_from_kconfig(component_lpi2c_adapter)
mcux_include_from_kconfig(driver_sai)
mcux_include_from_kconfig(driver_sai_edma)
mcux_include_from_kconfig(driver_flexio_i2c_master)
mcux_include_from_kconfig(driver_mu)
mcux_include_from_kconfig(driver_srtm_freertos)
mcux_include_from_kconfig(driver_ltc_edma)
mcux_include_from_kconfig(driver_qspi)
