#Description: DMA Driver; user_visible: True
include_guard(GLOBAL)
message("driver_lpc_dma component is included.")

target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/fsl_dma.c
)

target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
    ${CMAKE_CURRENT_LIST_DIR}/.
)

#OR Logic component
if(${MCUX_DEVICE} STREQUAL "RW612")
    include(driver_memory)
endif()
if(${MCUX_DEVICE} STREQUAL "RW610")
    include(driver_memory)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5506CPXXXX")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT633S_cm33")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC845")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5526")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5504CPXXXX")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54607")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54S016")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54606")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54616")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC55S04")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC55S06")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54016")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC832")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54018")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54628")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5502CPXXXX")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5512")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5516")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54605")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54618")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC824")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT555S_cm33")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54018M")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5506")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5514")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC55S16")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54S018")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54S018M")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC51U68")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5528")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC55S66_cm33_core0")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54S005")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC55S69_cm33_core0")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54005")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC834")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC822")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC55S28")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC844")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT533S_cm33")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC55S14")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC55S26")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5504")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54608")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT685S_cm33")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "MIMXRT595S_cm33")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC5502")
    include(driver_common)
endif()
if(${MCUX_DEVICE} STREQUAL "LPC54114_cm4")
    include(driver_common)
endif()

